### ISSUE TITLE
OMS Connection Issue Unclear

### ISSUE THREAD

**Issue by acgritt** [Azure/diagnostics-eventflow#104]
I am implementing EventFlow in a Service Fabric project that is using Serilog for the input and OMS for the output.  The Service was failing to start due to a "Bad Request" but no further information was given about the Error Code as "Bad Request" can have 9 different Sub-Codes as listed on https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-collector-api.  It would be nice if the error message also contained the response.Content data which specifies the Sub-Code so it would be easier to determine the issue.

**Comment by karolz-ms** [comment]
@acgritt sorry about that. Makes sense, we'll look into it.

Were you able to get your service running?

**Comment by acgritt** [comment]
@karolz-ms I was able to get my service running.  I ended up pulling down the code and building locally and linking to the debug assemblies to determine the exact nature of the configuration error I had which was I had an improperly formatted logTypeName as it had a space in it.  The response body of the message specified what the problem was which allowed me to fix it.

**Comment by karolz-ms** [comment]
Resolved with OMS output NuGet package version 1.1.1
