### ISSUE TITLE
When ES output is used - dependency collector collects communitation to ES as a dependency call

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Azure/diagnostics-eventflow#107]
There is an easy way to not collect the call to ES as a dependency. But you need to have SDK 2.4 to use it.

@karolz-ms is it ok to upgrade to ApplicaitonInsights 2.4?

**Comment by karolz-ms** [comment]
@SergeyKanzhelev Yes, absolutely. We take PRs :-)

**Comment by SergeyKanzhelev** [comment]
I tried to set a global flag in `EventFlowTelemetryProcessor`. But it seems by the time it reaches the processor it looses the `AsyncLocal` context. @karolz-ms is it expected or I'm doing something wrong?

**Comment by karolz-ms** [comment]
@SergeyKanzhelev hmm, not sure. There is nothing special about the `EventFlowTelemetryProcessor`, it is fully synchronous... Let me know what you find, I am curious.

**Comment by karolz-ms** [comment]
FYI--I have updated the Inputs.ApplicationInsights NuGet package on nuget.org. Many thanks!!

**Comment by karolz-ms** [comment]
@SergeyKanzhelev, any progress on this issue? Is there something I can help with?

**Comment by SergeyKanzhelev** [comment]
No, I tried that once and for some reason context wasn't propagated properly. I never had a chance to get back to this.

**Comment by karolz-ms** [comment]
This is sort of a limitation of AI.SDK -- it does not provide an easy way to distinguish between HTTP calls that are made as part of fulfilling core service duties vs. those that serve diagnostic needs.

You can use a TelemetryProcessor to filter out telemetry that is related to diagnostic endpoints--see example below. Ideally such telemetry should not be created in the first place, but it is not possible today, I had a conversation with @lmolkova  about this.

```csharp
    internal class UrlDependencyFilter : ITelemetryProcessor 
    {
        private string urlToFilter_;
        private ITelemetryProcessor next_;

        public UrlDependencyFilter(ITelemetryProcessor next, string urlToFilter) 
        {
            Requires.NotNull(next, nameof(next));
            Requires.That(Uri.IsWellFormedUriString(urlToFilter, UriKind.Absolute), nameof(urlToFilter), $"{nameof(urlToFilter)} parameter value should be a valid URL");

            next_ = next;
            urlToFilter_ = urlToFilter;
        }

        public void Process(ITelemetry item) {
            DependencyTelemetry telemetry = item as DependencyTelemetry;

            if (telemetry != null && telemetry.Target != null && telemetry.Data.StartsWith(urlToFilter_, StringComparison.Ordinal)) {
                return; // Drop it!
            }

            next_.Process(item);
        }
    }

    public class UrlDependencyFilterFactory : ITelemetryProcessorFactory 
    {
        private string urlToFilter_;

        public UrlDependencyFilterFactory(string urlToFilter)
        {
            Requires.That(Uri.IsWellFormedUriString(urlToFilter, UriKind.Absolute), nameof(urlToFilter), $"{nameof(urlToFilter)} parameter value should be a valid URL");

            urlToFilter_ = urlToFilter;
        }

        public ITelemetryProcessor Create(ITelemetryProcessor next) {
            return new UrlDependencyFilter(next, urlToFilter_);
        }
    }
```csharp
