### ISSUE TITLE
Warning re. duplicate "scope" keys in Service Fabric

### ISSUE THREAD

**Issue by mfmadsen** [Azure/diagnostics-eventflow#109]
We have set up a Service Fabric application hosted on Azure. In the application we have a ASP.Net Core stateless service configured with Event Flow logging with two input sources (EventSource and Microsoft.Extensions.Logging) and a single output destination (ApplicationInsights). The EventSource input only uses a single providerName (the one for the ServiceEventSource created by Service Fabric).
The diagnostics pipeline is hooked into the logger factory as per the documentation.

Generally it works great, but we are quite often (but not all the time) seeing a warning in the Service Fabric Explorer similar to this:
Unhealthy event: SourceId='...-DiagnosticsPipeline', Property='Connectivity', HealthState='Warning', ConsiderWarningAsError=false.
The property with the key 'Scope' already exist in the event payload. Value was added under key 'Scope_8'

Inspecting the Application Insights traces it seems to be related to the events logged using the ILogger by the ASP.Net Core parts of the code.

Inspecting the issues list it seems others have previously had similar issues, but that these issues should have been fixed in the latest packages. However we are using all of the latest packages (except for the ServiceFabric package, but as far as I know, nothing has changed related to this behavior):
`    <PackageReference Include="Microsoft.Diagnostics.EventFlow" Version="1.1.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Inputs.EventSource" Version="1.1.1" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Inputs.MicrosoftLogging" Version="1.1.1" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsights" Version="1.1.5" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.ServiceFabric" Version="1.1.3" />
`
Is this a known issue?

**Comment by karolz-ms** [comment]
What I suspect is happening is that you are using logical operation scopes (`ILogger.BeginScope()`) exposed by Microsoft.Extensions.Logging _and_ some of your events also have a property named `Scope` on them. When logical operation scopes are used, the Microsoft.Extensions.Logging input will try to add scope information to events, using `Scope` property. This causes property name clash and the warning you are seeing.

Are the events with two "Scope" properties raised from your code, or are these some framework/system events?

**Comment by mfmadsen** [comment]
Thanks for the quick reply! I suspect the same reason for the warnings, but I am seeing this only for events raised by the framework/system as the events we raise, are output using EventSource.

Custom data from an example event with multiple scope values:
EventId
1
Keywords
0x0000000000000000
Level
Informational
Message
Executing action method Application.AuthService.Controllers.Account.AccountController.Login (Application.AuthService) with arguments () - ModelState is Valid
ProviderName
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Scope
Application.AuthService.Controllers.Account.AccountController.Login (Application.AuthService)
Scope_2
RequestId:80000002-0005-fa00-b63f-84710c7967bb RequestPath:/Account/login

From this, it appears to me that ASP.Net Core (I guess) adds the Scope_2 value while the Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker provider adds the Scope value.

**Comment by karolz-ms** [comment]
I am starting to think that maybe we do not need to warn about these property name conflicts. The library handles them so there is no data loss. What do you think?

**Comment by mfmadsen** [comment]
I think that wouldn't be a good idea as that would mean you couldn't reliably filter on only the scope property value as you couldn't be sure that the value would actually be in the scope property (could be in scope_<whatever> property instead).

Reviewing the code for Microsoft.Diagnostics.EventFlow.Inputs.MicrosoftLogging/Logger/EventFlowLogger.cs the issue seems to be that a Scope property is explicitly added for each nested scope. I think a better approach would be to set the Scope property only at the inner most scope and set it to a breadcrumb style value listing the entire "scope path". For the above example event, the following Scope value would then be set:

RequestId:80000002-0005-fa00-b63f-84710c7967bb RequestPath:/Account/login > Application.AuthService.Controllers.Account.AccountController.Login (Application.AuthService)

(and the Scope_2 value would then not be set at all).

Let me know if you would like me to submit a PR on this.

**Comment by karolz-ms** [comment]
Yes, that sounds very good. Please submit a PR--many thanks!

**Comment by mfmadsen** [comment]
I have submitted PR #110. When going through the unit tests, I became unsure whether this change is the way forward. It really depends on how you want this to behave.
If you decide to keep the existing behavior (with multiple Scope properties), then you should probably remove the warning regarding property name conflicts as you suggested earlier. However that change is in the core module and also changes behavior, so I'm not really sure which approach is better.

**Comment by karolz-ms** [comment]
I think this is a step in the right direction, thanks. Will comment more on the PR.

**Comment by karolz-ms** [comment]
Resolved with Microsoft.Logging input package version 1.1.2 or newer. Thanks a bunch for making EventFlow better!
