### ISSUE TITLE
Microsoft.Diagnostics.EventFlow.Inputs.Serilog Nuget package Dependency

### ISSUE THREAD

**Issue by thecodejedi** [Azure/diagnostics-eventflow#120]
Microsoft.Diagnostics.EventFlow.Inputs.Serilog 1.2.2 is dependent on Microsoft.Diagnostics.EventFlow.Core (>= 1.1.6) which currently can not be met as 1.1.6 is not released yet.

Microsoft.Diagnostics.EventFlow.Inputs.Serilog 1.2.1 was dependent on Microsoft.Diagnostics.EventFlow.Core (>= 1.1.0) maybe it is a possibility to step back to this Version dependency?

**Comment by karolz-ms** [comment]
OOPS, sorry. Should be fixed now.
