### ISSUE TITLE
Changes to eventFlowConfig.json at runtime

### ISSUE THREAD

**Issue by alexvy86** [Azure/diagnostics-eventflow#121]
Are there any plans to support changes to the eventFlowConfig.json file at runtime? I'm thinking a bit into the future of a project that we're starting and how we might want to change the Level of events that EventFlow handles, particularly to enable lower-level messages for troubleshooting. Since the idea is for EventFlow to forward everything to a central logging system, I'd rather not have Verbose messages consuming bandwidth all the time. If we could change a filter or even add a new output (say, local to a file) on demand for scenarios like this one, it would be nice.

I took a quick look at the code and it seems from the [DiagnosticPipelineFactory](https://github.com/Azure/diagnostics-eventflow/blob/df8efb6b62653fb5a4d6156eb9cce9b231228cef/src/Microsoft.Diagnostics.EventFlow.Core/Implementations/DiagnosticPipelineFactory.cs#L29) that the configuration file is only loaded once when building the pipeline. Would adding `reloadOnChange: true` work? Is it even something you'd want to enable?

**Comment by karolz-ms** [comment]
Alex, good question.

Technically it should be possible to add this kind of functionality to EventFlow but it is a little tricky around making sure that you do not lose events, and do not get duplicate events, as the new configuration is applied. Ideally, when new configuration is detected, the following should happen (this assumes that input configuration has not changed):

1. Configuration is validated and the new pipeline is built, but not hooked up to inputs
2. Inputs are atomically switched to pump data into the new pipeline
3. The old pipeline is allowed to process events that have been pushed into it, then it is shut down.

If input configuration _is changing_, then it becomes even more tricky. That is the main reason why so far we have been reluctant to attempt to solve this problem, despite the fact that many environments do provide configuration change notifications.

But, there is an alternative: if you are using Service Fabric, or a similar service orchestrator, you can do a  rolling service upgrade just to apply the new configuration. This approach bypasses the whole complexity of doing diagnostic pipeline configuration change on the fly.

Hope this helps!
Karol

**Comment by alexvy86** [comment]
Makes sense, thanks Karol.

**Comment by karolz-ms** [comment]
OK, cool. Closing the issue for now.
