### ISSUE TITLE
Service Fabric support code sample needs more explanation

### ISSUE THREAD

**Issue by mikanyg** [Azure/diagnostics-eventflow#123]
The code sample of program.cs of the Service Fabric support is lacking detailed explanation why it uses ManualResetEvent and Console.CancelKeyPress event handler. 

When comparing with a newly created SF service, alot of code is added and even changed. 

Especially the use of Console.CancelKeyPress seems out of place in my understanding of how you can run service fabric services. Even though the SF services are console apps, they are always run silently, so how to even trigger the CancelKeyPress event?

So a bit more detailed explanation would a least help my understanding of the sample

**Comment by karolz-ms** [comment]
Good point, we should update the docs, but for the sake of explaining things quickly, the main reason for handling CancelKeyPress is to be able to shut down the diagnostic pipeline cleanly and dispose of all pipeline elements.

The issue that triggered this implementation was [this](https://github.com/Azure/diagnostics-eventflow/issues/96).

Service Fabric will send a Ctrl-C to the service process and wait for it to exit (for 30 by default, I believe). This is the chance for the process to do cleanup like mentioned above.

**Comment by mikanyg** [comment]
Thx for the quick update, it makes more sense to me now. A small paragraph explaining the sample implementation compared to what is "default" for all Service Fabric templates would be nice.

**Comment by karolz-ms** [comment]
I have added a few sentences clarifying the intention https://github.com/Azure/diagnostics-eventflow/commit/f241e67daf884c68d4ac80e0aaf368773ae129fd
