### ISSUE TITLE
Unable to attach custom properties using metadata filters

### ISSUE THREAD

**Issue by mikanyg** [Azure/diagnostics-eventflow#125]
I have tried to add additional custom properties to events using the metadata filter, and have not succeeded.

I have tried the following two approaches as global metadata filters
"filters": [    
    {
      "type": "metadata",
      "metadata": "request",
      "include": "requesturi == \"/myapp/myservice\"",
      "requestNameProperty": "requesturi",
      "durationProperty": "ellapsed",
      "isSuccessProperty": "issuccess",
      "responseCodeProperty": "statuscode",
      "applName": "MyApplication",
      "servName": "MyService"
    },
    {
      "type": "metadata",
      "metadata": "custom",
      "include": "ProviderName == SerilogInput",
      "applName": "MyApplication",
      "servName": "MyService"
    }
  ],

In the first filter I have added the two properties applName and servName with static values for all requests. In the other filter all events coming from serilog input provider should have the same properties with static values. I use Application Insights as output, but neither my traces or requests have these properties added.

As I understand the docs, this should be possible. For now I will probably use serilog to add these static properties.

**Comment by karolz-ms** [comment]
I would just use a custom filter for that. Check extensibility section in the docs--it has an example for creating a custom output, but a custom filter implementation looks almost the same, modulo different interface that needs to be implemented (`IFilter` vs `IOutput`)

In the  `IFilter.Evaluate()` method just add required properties using `EventData.AddPayloadProperty()`. You can even read the names and values of the properties from configuration (that would happen in the filter factory code, which receives filter configuration as a parameter to `CreateItem()`). 

Let me know how it goes!

**Comment by karolz-ms** [comment]
Closing this for now, but let us know if you have any follow-up questions
