### ISSUE TITLE
EventFlow failing to capture events within AppDomain (potential race condition?)

### ISSUE THREAD

**Issue by ibebbs** [Azure/diagnostics-eventflow#127]
Hi,

I am trying to use EventFlow to capture data from EventSource based instrumentation within a console app that starts an Orleans Silo (which, for context, initializes it's own app domain) and am experiencing some severe inconsistencies in functionality leading me to believe there may be race-conditions in EventFlow. FYI, I am also using [EventSourceProxy](https://github.com/jonwagner/EventSourceProxy) to take some of the leg work out of creating EventSource implementations but, as will be seen below, I have shown that this is not causing the issue.

For background, I have two event sources as follows:

_"Outer" event source_ - EventSourceProxy generated EventSource
```
[EventSource(Name = "Outer.Instrumentation")]
public abstract class Instrumentation : EventSource
{
    public static readonly Instrumentation Log = EventSourceImplementer.GetEventSourceAs<Instrumentation>();

    [Event(1, Level = EventLevel.Informational)]
    public abstract void Activated(string type, Guid id);

    [Event(2, Level = EventLevel.Informational)]
    public abstract void Deactivated(string type, Guid id);
}
```

_"Inner" event source_ - Manually implemented EventSource
```
[EventSource(Name = "Inner.Instrumentation")]
public class Instrumentation : EventSource
{
    public static readonly Instrumentation Log = new Instrumentation();

    [Event(1, Message = "Checking for data later than {0}", Level = EventLevel.LogAlways)]
    public void CheckingForUpdate(string currentVersion)
    {
        if (IsEnabled())
        {
            WriteEvent(1, currentVersion);
        }
    }

    [Event(2, Message = "Found data dated {0}, starting update", Level = EventLevel.Informational)]
    public void UpdateAvailable(string latestVersion)
    {
        if (IsEnabled())
        {
            WriteEvent(2, latestVersion);
        }
    }

    [Event(3, Message = "Found data dated {0}, no update required")]
    public void NoUpdateAvailable(string latestVersion)
    {
        if (IsEnabled())
        {
            WriteEvent(3, latestVersion);
        }
    }

    [Event(4, Message = "Encountered the following error while checking for updates: {0}")]
    public void ErrorCheckingForUpdate(string error)
    {
        if (IsEnabled())
        {
            WriteEvent(4, error);
        }
    }
}
```

I then initialize the Orleans Silo (i.e. the new app domain) as follows:

```
private static void InitSilo(string[] args)
{
    using (var pipeline = DiagnosticPipelineFactory.CreatePipeline("eventFlowConfigSilo.json"))
    {
        SiloHost = new SiloHost(System.Net.Dns.GetHostName())
        {
            ConfigFileName = "OrleansConfiguration.xml"
        };

        SiloHost.InitializeOrleansSilo();

        if (!SiloHost.StartOrleansSilo())
            throw new SystemException(String.Format("Failed to start Orleans silo '{0}' as a {1} node", SiloHost.Name, SiloHost.Type));
    }
}

public void Start()
{
    _hostDomain = AppDomain.CreateDomain(
        "OrleansHost",
        null,
        new AppDomainSetup() { AppDomainInitializer = InitSilo }
    );
}
```

Which uses the following event flow config file:

```
{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        { "providerName": "Outer.Instrumentation" },
        { "providerName": "Inner.Instrumentation" }
      ]
    }
  ],
  "filters": [],
  "outputs": [
    {
      "type": "StdOutput"
    }
  ],
  "extensions": []
}
```

Now, when I start the silo, I *always* see events from the "Outer" event source but never see events from the "Inner" event source. Even more confusingly, if I add a breakpoint to the "IsEnabled" check on any of "Inner.Instrumentation's" events, the check *sometimes* evaluates to true (proceeding to call WriteEvent) and *sometimes* evaluates to false (skipping the call to WriteEvent) but, in either case, I don't see any output from "Inner.Instrumentation".

Furthermore:
* If I initialize the EventFlow pipline outside of the app-domain then (as could be expected) I do not receive events for either event source.
* If I run PerfView and listen to the "Inner.Instrumentation" event source then "IsEnabled" *always* evaluates to true and I *always* receive events for the EventSource in PerfView but not in "StdOutput" (showing that the event source itself is fine).
* If I change "Inner.Instrumentation" to be generated by EventSourceProxy I still don't see any events (and lose the ability to check "IsEnabled").
* I have an additional EventSource outside of the AppDomain with it's own EventFlow pipeline and it *always* emits the correct events.
* Ensuring the class initializer of the event source is run before the EventFlow pipeline is created has no effect.

This is proving to be quite a frustration and I would very much appreciate suggestions on the potential cause of and (preferably) solution to this issue.

Thanks in advance,
  Ian

**Comment by karolz-ms** [comment]
Sorry for late reply, Ian--was on vacation yesterday.

This is a bit a shot in the dark, but can you try changing the names of your EventSources so they do not contain the dot character in the name? E.g. `Outer-Instrumentation` instead of `Outer.Instrumentation`? Historically this was a source of bugs/issues.

If that does not help, I wonder if you could provide us with a complete sample/gist that reproduces the problem.

**Comment by karolz-ms** [comment]
Also, @ibebbs  we just pushed a newer version of the EventSource input to NuGet (1.1.2). It has a fix for potential deadlock condition during initialization, which might help here as well. Can you check it out?

**Comment by ibebbs** [comment]
Hi @karolz-ms,

Thanks for this. Hopefully I'll get a chance to try the new version later today or over the weekend and will let you know how it goes.

Ian

**Comment by karolz-ms** [comment]
@ibebbs any news about the issue? Are you still seeing it?

**Comment by karolz-ms** [comment]
Closing this one for now (no firm repro), but please reopen if more information becomes available!
