### ISSUE TITLE
Unable to map Serilog.Error to AppInsight exceptions when no Exception exists

### ISSUE THREAD

**Issue by mikanyg** [Azure/diagnostics-eventflow#130]
In Serilogs ILogger interface, it is possible to create LogEvents with level = Error without any Exceptions attached to the LogEvent.

When using EventFlow filters to map LogEvents with level = Error to metadta of type Exception this fails due to the following check in code https://github.com/Azure/diagnostics-eventflow/blob/dced8a46d446a03ffdb4588d08fa608408e046d0/src/Microsoft.Diagnostics.EventFlow.Inputs.Serilog/SerilogInput.cs#L85

It would make sense to make it possible to map to Exception metadata when using ILogger.Error("Some critical business error, that don't result in Exception")

**Comment by karolz-ms** [comment]
Michael, what you describe does not fit how the Exception standard metadata type was designed. With that metadata type you have to have an Exception instance to work with.

From Application Insights API perspective it is possible to create `ExceptionTelemetry` without an instance of an Exception, but I am not sure if that really makes much sense. Can you elaborate what are you trying to achieve?

**Comment by karolz-ms** [comment]
Closing this one for now but feel free to reopen as necessary!

**Comment by mikanyg** [comment]
@karolz-ms No problem, I'm sorry for not getting back on this.

First of all, I think you are right about the design. We needed something in Application Insight to categorize our serilog traces of level Error (even those that did not occur from exceptions), and thought that the AppInsights exception meta data was the way to go.

The workaround was to add a dummy exception like, 
`Log.Error(dummyException, "important error message here");`

But it made us re-think our whole approah,  so we are moving away from this "hack".

**Comment by karolz-ms** [comment]
@mikanyg thanks for clarification. Cheers!
