### ISSUE TITLE
Unable to send the EventFlow Messages/Errors to Application Insight

### ISSUE THREAD

**Issue by mohitchhabra** [Azure/diagnostics-eventflow#131]
Hi,

I am unable to send the eventflow messages to Application Insight.  I followed the following article's scenario 2. 
https://blogs.msdn.microsoft.com/softwaresimian/2017/06/16/azure-service-fabric-application-insights-working-sample/

Thanks,
Mohit Chhabra

**Comment by lmolkova** [comment]
Hello @mohitchhabra,

could you please share your eventFlowConfig.json?

Which input do you have?  If you are using event source as input, make sure you set up the source(s) names correctly.
Note that there is a filter (in the config provided in the article) that drops all messages with Verbose severity. Please check if your input sends any messages with higher severity or remove filter temporary.

Can you make sure something writes to this input i.e. if you run your service locally, you can get some messages from the input without EventFlow.

Did you set up ApplicationInsights instrumentation key? How do you check that messages/errors do not appear in AppInsights?

Thanks,
Liudmila

**Comment by mohitchhabra** [comment]
Hi Luidmila,

Please find my file content below :
`{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        { "providerName": "MyCompany-Service_Fabric_HotTelemetry-BasicService" }
      ]
    }
  ],
  "filters": [
    {
      "type": "drop",
      "include": "Level == Verbose"
    }
  ],
  "outputs": [
    {
      "type": "ApplicationInsights",
      "instrumentationKey": "servicefabric:/MyConfigSection/ApplicationInsightsInstrumentationKey"
    }
  ],
  "schemaVersion": "2016-08-11",
  "extensions": []
}`


> Which input do you have? If you are using event source as input, make sure you set up the source(s) names correctly.
 - I used Event Source as an Input and double checked my name sources. 

> Note that there is a filter (in the config provided in the article) that drops all messages with Verbose severity. Please check if your input sends any messages with higher severity or remove filter temporary. 

- I used Message with Severity Critical and error as well. I also tried with removing the filter.

> Can you make sure something writes to this input i.e. if you run your service locally, you can get some messages from the input without EventFlow.

- I am able to  write it but output is not going to AI.

> Did you set up ApplicationInsights instrumentation key? How do you check that messages/errors do not appear in AppInsights?

Yup, I did. In the config above I used settings.xml to store the key. But I tried putting it directly in the eventflowconfig as well.  I went through the AI account on the portal and check with exceptions and messages. There is no Traces/Exceptions in AI account. I am using AI since it's early preview to I have good enough understanding of reading the metrics. 

Thanks,
Mohit Chhabra

**Comment by lmolkova** [comment]
@mohitchhabra 
 Thanks for the details.

1. Could you please run your service locally in the debug mode and check Debug output in Visual Studio.
Look for the output from ApplicationInsights.

![image](https://user-images.githubusercontent.com/2347409/29936148-005035ea-8e36-11e7-9b2c-79bcd2e0e34c.png)

Make sure ikey is properly set up there.
Please also check for suspicious exceptions in the debug output.

2. Would you be able to provide repo app? EventFlow input and AppInsights output are quite popular, and we are not aware of any issues, so the issue you see is rare and hard to resolve without repro.

Thanks,
Liudmila

**Comment by mohitchhabra** [comment]
Hi Liudmila,

1) I was getting Application Insight Telemetry (unconfigured) which what I understood was the reason of the issue initially  but shouldn't the nugget package of Eventflow.Output.AI configure it? Btw, I did configured the AI to test it out and then I am getting the telemetry data but not the logs which I am logging through Event Flow.

2) you can use the code from this repo. I have used this one as well in my experiments.
https://github.com/ross-p-smith/service-fabric-hot-telemetry

Thanks,
Mohit Chhabra

**Comment by lmolkova** [comment]
Mohit,

1. It means that somehow instrumentation key was not configured properly.
2. I'll look into your repo and let you know why it happens

**Comment by lmolkova** [comment]
1. I'm not able to reproduce your initial issue. If I set proper ikey in Local.1Node.xml, Local.5Node.xml, I see that ikey is configured AND I see messages from your EventSource on the portal (and in Analytics)
![image](https://user-images.githubusercontent.com/2347409/29945581-86477fe4-8e56-11e7-82a4-81858fd4427e.png)

![image](https://user-images.githubusercontent.com/2347409/29945566-72cd0236-8e56-11e7-8bca-983b10119da5.png)

![image](https://user-images.githubusercontent.com/2347409/29945646-d7c420e8-8e56-11e7-963f-77908815be57.png)

Please make sure you set up ikey in the local.1node and local.5node.xml

2. I also see unconfigured in AI traces from ASP.Net Core:
```
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2017-08-31T21:06:36.6132860Z","tags":{"ai.cloud.roleInstance":"xxxxxx","ai.application.ver":"1.0.0.0","ai.internal.sdkVersion":"aspnet5f:2.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Hosting starting","severityLevel":"Verbose","properties":{"CategoryName":"Microsoft.AspNetCore.Hosting.Internal.WebHost","{OriginalFormat}":"Hosting starting","DeveloperMode":"true","AspNetCoreEnvironment":"Production"}}}}
```

So ApplicationInsights SDK additionally monitors your asp.net core application and this one is not configured.
EventFlow configuration does not configure the whole AI SDK, it only configures EventFlow output.

You may configure it in appsettings.json, ApplicationInsights section
```
{
  "ApplicationInsights": {
    "InstrumentationKey": "11111111-2222-3333-4444-555555555555"
  }
}
```
or with APPINSIGHTS_INSTRUMENTATIONKEY env variable

**Comment by lmolkova** [comment]
Mohit,

Were you able to get the event source messages in AppInsights?

**Comment by karolz-ms** [comment]
Please reopen if this is still an issue after following @lmolkova guidelines--hope not!
