### ISSUE TITLE
Why not to have an out-of-the-box Output provider for Serilog (or NLog, log4net, etc.)?

### ISSUE THREAD

**Issue by ycamargo** [Azure/diagnostics-eventflow#132]
If we already have a Serilog Input, why not an Output?

In my current project we have a legacy table logging (SQL Server) that we still need to populate with application generated logs. 
Our old implementation is based on log4net configured to write logs directly to SQL Server.
Our new implementation is based on Microsoft.Extensions.Logging for log writing & Microsoft.Diagnostics.EventFlow for routing events to Application Insights and, in a near future, to OMS or ELK. Since we need to mantain, for a while, the SQL Server logging, we are about to develop our own Custom Output but, if we had an ootb Serilog output provider, we can just configure it to do so. And, a Serilog Output could be a good temporary (or even permanent) alternative to send the logs to a lot of other targets (using Serilog sinks).

I know we can do that using Microsoft.Extensions.Logging providers (for Serilog, NLog, log4net, whatever) but this alternative will be more tied to the code (instead of configuration files) and does not seens to be the best design approach.

What do you think about?

Regards

**Comment by lmolkova** [comment]
Hi @ycamargo,

Thanks for the suggestion!
It would be great if you could opensource your custom output. We would be happy to reference your repo and the nuget package. It should be almost as good as ootb output, except adding extensions section into the config.

Having your own repo also allows you to develop it at your own pace and have full control over bug fixes and releases.

If you need any help with implementation, just let me know. @karolz-ms created a [guide](https://github.com/Azure/diagnostics-eventflow#creating-a-pipeline-with-custom-elements-using-configuration) that you have probably already seen.

Thanks,
Liudmila

**Comment by ycamargo** [comment]
Hi @lmolkova, thanks for the quick response.
I will implement a Custom Output only to directly write log entries to SQL Server table. My original idea was to implement this highly coupled with our legacy table structure but I can work a little bit more on that in order to decouple it and make it more reusable and suitable for different table structures. And I will be glad to share that with you.
I have no near term plans to implement a Custom Output to Serilog but if I have time I will take a look on that too.

Thanks,

Yuri

**Comment by lmolkova** [comment]
thanks, @ycamargo, keep us posted!

I'm closing this issue for now.

**Comment by ycamargo** [comment]
Hi @lmolkova,
I've created a Custom Output to Sql Server tables.

The repo is here: https://github.com/ycamargo/diagnostics-eventflow-sqloutput

And nuget package is here: https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Outputs.SqlTable/1.0.0

Please, feel free to take a look, evaluate it and reference in your documentation.

I will accept PR evolutions to it, also.

Thanks and regards.
