### ISSUE TITLE
eventFlowConfig.json does not show up for Service Fabric ASP.NET Stateless/Stateful services

### ISSUE THREAD

**Issue by dkkapur** [Azure/diagnostics-eventflow#133]
When adding the EventFlow NuGets to a project containing ASP.NET services (both stateful or stateless), templates available in VS 2017 since version 15.02, the eventFlowConfig.json does not seem to be created (it is not under PackageRoot > Config) and cannot be found elsewhere in the directory. 

This still works as expected for non ASP.NET services.

**Comment by lmolkova** [comment]
Hi Deep,

It's in fact related to the project file type.
1. non ASP.NET templates use old csproj (project.json) format 
2. ASP.NET templates use new csproj format (PackageReference)

Unfortunately, Nuget does not support content files for the new csproj (https://github.com/NuGet/Home/issues/4942).

Karol mentions it in readme

```
Note: if your project targets .NET Core the eventFlowConfig.json file will not be automatically added. To fix this you can just copy the example listed above and save it under the name "eventFlowConfig.json" in your project folder. Then, open your project file (this assumes you are using Visual Studio 2017/MSBuild 15 csproj-based project system) and add the following snippet to your project:
```

However it's not really related to the .NET Core, I'll update the readme.

**Comment by lmolkova** [comment]
As there is nothing else we can do and limitation is coming from nuget, I'm closing the issue.

**Comment by dkkapur** [comment]
I see - so basically it should still work as long as the NuGets are added and I do the manual steps suggested?

Thanks for the rapid response, sorry I missed that in the readme!

**Comment by lmolkova** [comment]
Yes, you are right. Just copy (and modify) the config and that's it.
