### ISSUE TITLE
Set metadata metric name from event property

### ISSUE THREAD

**Issue by mikanyg** [Azure/diagnostics-eventflow#136]
The metric meta data does not support specifying metric name from an event property, only by specifying the metric name directly in json filter configuration.

I would like to be able to dynamically specify metric name based on an event property, just like in Request (requestNameProperty) and Dependency (targetProperty) meta data.

The scenario would be that we have Serilog input logger with pre-configured Context properties that is detected by the include filter. 

Usage in code could be 
`Log.Information("This message is converted to a metric {MetricName} with a count of {MetricValue}, "CustomMetricName", 1);`

example config of filter
{
  "type": "metadata",
  "metadata": "metric",
  "include": "ProviderName==Serilog && LogType==Metric",
  "metricNameProperty": "MetricName",
  "metricValueProperty": "MetricValue"
}

Which would make it easy to have a general metric meta data filter that can make logging configuration more maintainable.

**Comment by karolz-ms** [comment]
Makes a ton of sense, thanks for the suggestion, Mikael. Will try to get that added. Feel free to submit a PR if you need it soon

**Comment by mikanyg** [comment]
I don't expect to have time for a PR anytime soon, but looking forward to see it in action :-)
