### ISSUE TITLE
Etw Input provider throws  System.UnauthorizedAccessException: Error Starting ETW: Access Denied (Administrator rights required to start ETW)

### ISSUE THREAD

**Issue by GitHubSachin** [Azure/diagnostics-eventflow#141]
When the application runs under low privileges (standard user like network service), it is unable to start listening to a Etw input provider. I see error like this below

System.UnauthorizedAccessException: Error Starting ETW: Access Denied (Administrator rights required to start ETW) 

Is there specific configuration to be specified to listen to provider if that does not exist?
I am using input like this
"inputs": [
    {
      "type": "ETW",
      "providers": [
        {
          //This is my custom provider guid
          "providerGuid": "QDF70947-988D-5AA7-6059-8D957FAD613Q"
        }
      ]
    }
  ],
  "filters": [
    {
      "type": "drop",
      "include": "Level == Verbose"
    }
  ],

**Comment by karolz-ms** [comment]
@GitHubSachin  sorry for late reply!

ETW capturing requires administrative privileges, as the error says. This is a basic Windows OS requirement and is also mentioned in [the docs for the output](https://github.com/Azure/diagnostics-eventflow#etw-event-tracing-for-windows):

> The data is captured machine-wide and requires that the identity the process uses belongs to Performance Log Users built-in administrative group

To be precise, the Performance Log Users group is the lowest privilege that makes it work. Running as administrator will do the trick too.

Be *very, very careful* about doing this however. This privilege basically lets you "get inside" any process in the system, including OS processes, with quite obvious security implications.

Hope this helps!
