### ISSUE TITLE
GetSystemTimePreciseAsFileTime function in EventDataExtensions not supported on operating systems before windows 8

### ISSUE THREAD

**Issue by arturwa** [Azure/diagnostics-eventflow#142]
GetSystemTimePreciseAsFileTime is not supported on operating systems prior Windows 8
Latest update ( Nuget Package 1.1.3)  throws exceptions on Windows 7 running NET 4.6.1, NETCore 2.0

**Comment by karolz-ms** [comment]
Closed inadvertently--"thank you!" Github :-/

**Comment by karolz-ms** [comment]
@arturwa Thank you for reporting this issue.

Can you try NuGet package 1.1.4 (just uploaded) to see if it fixes the problem?

**Comment by karolz-ms** [comment]
I assume the problem is fixed, but let me know if the new version does not work for you
