### ISSUE TITLE
Error in using with .Net 4.6.1 

### ISSUE THREAD

**Issue by tanwarsatya** [Azure/diagnostics-eventflow#147]
Hi

I was  successfully able to use the event flow and send tracing  info to Application Insight from a Service Fabric application. Recently I tried to upgrade the .net framework from 4.5.2 to 4.6.1 and now  i am seeing errors..

Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricDiagnosticPipelineFactory.CreatePipeline(String healthEntityName, String configurationFileName, String configurationPackageName)
   at SchoolWayz.Cloud.Worker.Services.Router.Program.Main() in C:\work\infowayz\SchoolWayz\source\apps\Cloud.Worker.Services.Router\Program.cs:line 36

Is there any plan to support 4.6.1 and other frameworks.

Regards
Satya

**Comment by karolz-ms** [comment]
This error is most likely not related to EventFlow. A lot of users are using EventFlow in applications targeting 4.6x frameworks without issues.

It is probably a mismatch between what the application is requiring and what is actually installed on your SF cluster. E.g. are you sure the cluster has .NET 4.6.1 installed?

**Comment by tanwarsatya** [comment]
I found the issue it was because of .Net Standard version for my library. I have to use .Net Standard 1.0 , and cannot use .Net Standard 2.0 with eventflow library.

**Comment by karolz-ms** [comment]
EventFlow .NET Core libraries do support .NET Core 1.0 (netstandard 1.6) if possible. In [the documentation](https://github.com/Azure/diagnostics-eventflow#platform-support) ".NET Core" means netstandard 1.6 and should work for applications targeting .NET Core 1.0 and above.
