### ISSUE TITLE
Log to a flat file through Diagnostics.EventFLow

### ISSUE THREAD

**Issue by nicoleta-scrimint** [Azure/diagnostics-eventflow#151]
Hi,

In the past I was using Semantic Application Block from Microsoft Enterprise Library for logging to a flat file or to a rolling flat file. I saw on the GitHub page for Semantic Logging that the project is no longer under development and that Diagnostics.EventFlow could be used instead. I could use the EventSource input as a semantic logging structure for the logging methods. I saw that Diagnostics.EventFlow does not have out of the box an output destination to log files. It can be built an output destination to a log file through the CustomOutput extention type, still there needs to be configured how to save the log data into the file. I would have liked a built-in log file destination output, so that we do not create the logging destination output from scratch. In the Semantic Logging Application Block, the data was saved into the log file in a structured way with specific information gathered from the EventSource event methods.

Is it available a destination output file for the Diagnostics.EventFlow?
Thank you!

https://github.com/MicrosoftArchive/semantic-logging

**Comment by karolz-ms** [comment]
Hi @nicoleta-scrimint 

we currently have no plans to develop an output that would write to structured files, sorry. That said, it should not be very hard to develop one, or adapt the one Semantic Logging Application Block  (SLAB) is using to EventFlow. [The documentation section on extensibility](https://github.com/Azure/diagnostics-eventflow#eventflow-pipeline-element-types) should have everything you need to get started, but if you have questions, please open an issue here on GitHub.

Hope this helps anyway
Karol

**Comment by karolz-ms** [comment]
Closing this one for now
