### ISSUE TITLE
ApplicationInsightsOutput - Send DateTime as Iso 8601

### ISSUE THREAD

**Issue by jfloodnet** [Azure/diagnostics-eventflow#156]
In order for Log Analytics to understand DateTimes, they must be formatted as specified here: https://docs.loganalytics.io/docs/Language-Reference/Data-types/datetime

It looks as though DateTime.ToString() is being called, which will format a culture specific date time similar to "5/12/2017 9:53:22 AM" [ApplicationInsightsOutput.cs#L325](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsights/ApplicationInsightsOutput.cs#L325)

Can a similiar fix be applied as in issue #75 ?

**Comment by karolz-ms** [comment]
Makes sense, thanks for the suggestion! We'll fix this

**Comment by karolz-ms** [comment]
Keep open till new bits are released

**Comment by karolz-ms** [comment]
Fixed in AI.Output version 1.2.1 release
