### ISSUE TITLE
Event data loss in case of network issues

### ISSUE THREAD

**Issue by abhiggit** [Azure/diagnostics-eventflow#157]
Is there a way to retrieve the ETW events fired from a service during a network issue. For my case, all the events received during an ongoing network issue were lost and an exception event was logged in the HealthReporter csv file. Once the issue was resolved, it worked fine for newly generated events. I am trying to push my events output to EventHub.

**Comment by karolz-ms** [comment]
Sorry, preserving and re-sending events in case of network issues is currently only supported by Application Insights output (via their "server" channel).
