### ISSUE TITLE
output support logstash ?

### ISSUE THREAD

**Issue by zxarcg** [Azure/diagnostics-eventflow#161]
I want to output logstash,  can I do this?

**Comment by karolz-ms** [comment]
As of today there is no direct way to push data into logstash. You could use EventHub as an intermediary, but that is probably an overkill.

But thanks to @mblaschke we are very close to have native HTTP output for EventFlow [(see issue 160)](https://github.com/Azure/diagnostics-eventflow/issues/160), so once it is available, you will be able to use that to pump data directly to logstash.

Hope this makes sense?

**Comment by karolz-ms** [comment]
The HTTP output will be published in the next couple of days; I just need to take care of some administrative stuff with NuGet org. Closing this issue for now.
