### ISSUE TITLE
Trace input does not capture the ActivityID

### ISSUE THREAD

**Issue by karolz-ms** [Azure/diagnostics-eventflow#167]
Should examine https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.correlationmanager.activityid?view=netframework-4.7.1 and add the activity ID to the event payload if a valid ID is available.

**Comment by tedvanderveen** [comment]
Is it related to .Net version 4.7.1? (Looking at the URL you provided).
Should we see same results when using EventSource?

**Comment by karolz-ms** [comment]
Not really, it is just that the docs.microsoft.com site defaults to showing APIs for the latest version of the framework, which is 4.7.1 as of now.

However, the docs suggest that this API is available for 4.5+ and .NET Core 2.0, but not Core 1.1. So we'll have to decide whether to start publishing a separate version of the input assembly that targets Core 2.0 for the folks that are on Core and want to take advantage of this functionality (Core 2.0 would be required). Probably yes.

**Comment by karolz-ms** [comment]
Trace input package version 1.4.1 or later
