### ISSUE TITLE
"DiagnosticPipelineFactory: unknown type 'Http' in configuration section 'outputs'"

### ISSUE THREAD

**Issue by SujaySKumar** [Azure/diagnostics-eventflow#168]
Running the latest versions of

Microsoft.Diagnostics.EventFlow (v1.1.0), 
Microsoft.Diagnostics.EventFlow.ServiceFabric (v1.1.4),
Microsoft.Diagnostics.EventFlow.Outputs.HttpOutput (v1.1.1). 

`DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json")` throws the above exception.

Stack Trace:

`" "DiagnosticPipelineFactory: unknown type 'Http' in configuration section 'outputs'"  at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ReportUnknownItemTypeAndThrow(IHealthReporter healthReporter, IConfigurationSection configurationSection, ItemConfiguration itemConfiguration)\r\n   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ProcessSection[PipelineItemType,PipelineItemChildType](IConfigurationSection configurationSection, IHealthReporter healthReporter, IDictionary`2 itemFactories, IDictionary`2 childFactories, String childSectionName)\r\n   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(IConfiguration configuration, IHealthReporter healthReporter)\r\n"`

**Comment by karolz-ms** [comment]
@SujaySKumar thanks for reporting this! Just realized we need to publish a new version of the Core package to have the new Http output recognized by the DiagnosticPipelineFactory. Will do this later today.

**Comment by karolz-ms** [comment]
Should be fixed by the EventFlow.Core Nuget package version 1.1.9 or newer
