### ISSUE TITLE
Sample of simplest possible configuration using ILogger as input

### ISSUE THREAD

**Issue by eloekset** [Azure/diagnostics-eventflow#178]
I'm trying to use EventFlow to log from ASP.NET Core Micro Services in Service Fabric to Application Insights, but I haven't succeeded in configuring that correctly. So I decided to try a simple .NET Core Console application to see if I was able to configure EventFlow to use an ILogger as input and StdOut as output.

I've published the simple console app in this repo: https://github.com/eloekset/EventFlowLogTest1

I expect it to output the three LogDebug, LogInformation and LogError messages to the console, but it doesn't. So I used AddConsole() and AddDebug() from Microsoft.Extensions.Logging, just to verify that I get an output that way - and I do.

My eventFlowConfig.json file looks like this:
```
{
  "inputs": [
    {
      "type": "Microsoft.Extensions.Logging"
    }
  ],
  "filters": [
    {
      "type": "drop",
      "include": "Level == Verbose"
    }
  ],
  "outputs": [
    {
      "type": "StdOutput"
    }
  ],
  "schemaVersion": "2016-08-11"
}
```

Can someone spot the issue?

**Comment by yantang-msft** [comment]
@eloekset I tried your project and it does show the LogInformation and LogError through EventFlow, no LogDebug since it's dropped by the filter plugin.
Can you give it a try again? If it's still not working, try add the HealthReporter and see if there is anything abnormal.

**Comment by eloekset** [comment]
Hah! Indeed, it does work. I was tricked by having a breakpoint at line 27 - the closing bracket for the using block of `logger.BeginScope`. 🙄

Thanks! Then I'll just need to add more and more to this until I reach the same complexity as I've got in the microservice project.

**Comment by eloekset** [comment]
It would be useful if the team could provide a sample project demonstrating exactly how this configuration is done: https://github.com/Azure/diagnostics-eventflow#support-for-service-fabric-settings-and-application-parameters
