### ISSUE TITLE
Disable strong naming for local build to make unit tests easier to run

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/diagnostics-eventflow#180]
We shall update the project that strong naming/signing only runs when it is the build intending for releasing or validation. It should be opt-in rather than opt-out.

**Comment by karolz-ms** [comment]
https://github.com/Azure/diagnostics-eventflow/pull/196 solves this issue

**Comment by xiaomi7732** [comment]
Thank you for taking care of this!
