### ISSUE TITLE
Is there a way to use Event flow diagnostics with Azure function.

### ISSUE THREAD

**Issue by whizlingo** [Azure/diagnostics-eventflow#183]
We are currently using Event flow diagnostics for log aggregation for all our docker enabled ASP.net core web apis hosted in Azure SF. We also have few azure functions where we want to use the same approach. I see that the only instance of ILogger is accessible, but i guess we would need ILoggerFactory. Do you have a sample for leveraging it in the Azure functions ?.

**Comment by SergeyKanzhelev** [comment]
I'm not sure you will be able to hook up requests collected by azure function hosting into eventflow this way. My understanding you only have access to the `TelemetryClient`, not `TelemetryConfiguration`. So you cannot replace telemetry channel there.

It should work for custom telemetry though.

cc: @brettsam and @christopheranderson

**Comment by karolz-ms** [comment]
@SergeyKanzhelev thanks for chiming in. My original point was just to say that objects expensive to create and destroy, like EventFlow pipeline or TelemetryConfiguration, should be shared between Azure function invocations. [The doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#custom-telemetry-in-c-functions) shows how to do this using static class members. I did not mean to suggest that this example shows how to create EventFlow pipeline from within an Azure function.

Not sure I understand your point though--the sample sets `InstrumentationKey` on `TelemetryConfiguration.Active`, so why are you saying it does not have access to `TelemetryConfiguration`?

**Comment by SergeyKanzhelev** [comment]
My understanding there is a separate TelemetryConfiguration object that is used to process and send standard telemetry collected by hosting infra. Example shows how to report custom telemetry in addition to what hosting infra collected.

**Comment by karolz-ms** [comment]
I see. @brettsam or @christopheranderson : is there a plan/desire to open it up a bit, i.e. put AppInsights vs other diagnostic backends on more equal footing with regards to Azure Functions?

**Comment by brettsam** [comment]
Yes, there's a desire to open it up more. We're currently looking into that for Functions V2.

I don't know much about EventFlow, but it looks like to get it hooked up to App Insights, you register a `TelemetryProcessor`? That's the kind of thing we'd like to enable in V2: customization of our host services (like the factory we use to create the `TelemetryClient`). In addition to allowing customization of our `ILoggerFactory`. It looks like either of those would open this up for better integration with EventFlow.

**Comment by karolz-ms** [comment]
@brettsam yes, EventFlow can hook up to AppInsights SDK pipeline as a TelemetryProcessor.

I am glad that you guys are working on making Functions V2 more open for customization. My hope is that the resulting design not only will allow me to add arbitrary logger providers to the final `ILogger` dependency-injected into all parts of the application, but also _will allow me to control the processing of all infrastructure diagnostics generated by Functions runtime/host_. The latter opens up very interesting scenarios like 

- sending verbose logs to some cheap storage (think Azure blobs), while warnings/exceptions/dependency calls go to AppInsights and power their premium experiences
 - augmenting Application Insights with 3rd party analysis/monitoring/alerting solutions
 - using technologies like logstash or fluentD for extra flexibility & scale (esp. if Azure Functions are part of bigger, multi-platform system)

Does this make sense?

**Comment by karolz-ms** [comment]
Closing this for now as this is largely a question of making Azure functions more extensible with regards to diagnostic options. @whizlingo please reopen if you have further questions. Thanks!
