### ISSUE TITLE
ElasticSearch outputter cannot be used in vanilla .net core projects

### ISSUE THREAD

**Issue by knowhoper** [Azure/diagnostics-eventflow#185]
Hi,

OOTB the Asp.net Core template cannot be used with ElasticSearch eventflow due to NEST5 relying on an old version of JSON.net. I have also encountered issues with MassTransit due to NEST requiring an old package too.

NEST 5.0.0 depends on Newtonsoft.Json (>= 9.0.0 && < 10.0.0) but Newtonsoft.Json 9.0.0 was not found. An approximate best match of Newtonsoft.Json 9.0.1 was resolved.
Install-Package : Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
 Test.Service -> Microsoft.AspNetCore.All 2.0.5 -> Microsoft.AspNetCore.Mvc.ViewFeatures 2.0.2 -> Newtonsoft.Json.Bson 1.0.1 -> Newtonsoft.Json (>= 10.0.1) 
 Test.Service -> Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch 2.2.1 -> NEST 5.0.0 -> Newtonsoft.Json (>= 9.0.0 && < 10.0.0).At line:1 char:1
+ install-package Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch ... 

Is there an ETA of an package update?

Thanks in advance!

**Comment by karolz-ms** [comment]
Thanks for the report. We'll try to fix this in a few days. 

Have you found any workarounds yet? Like, upgrading NEST package to, say, 5.6.0?

**Comment by knowhoper** [comment]
Hi, thanks for the fast response. Yes, upgrading NEST solved the package warnings. 

Thanks again!

**Comment by karolz-ms** [comment]
Elasticsearch output v 2.2.2 solves this issue for good
