### ISSUE TITLE
eventFlowConfig.json not added when ServiceFabric extension is added from nuget

### ISSUE THREAD

**Issue by Danwich** [Azure/diagnostics-eventflow#19]
When I add the service fabric the json config file is not added.  Per the current implementation in preview 3, the json file should probably be added and placed in the Config folder so that once packaged the config file will be found in the config package as the Event Flow pipeline for Service Fabric is expecting.

**Comment by karolz-ms** [comment]
Thanks for the suggestion, @Danwich  Makes sense.

**Comment by karolz-ms** [comment]
Support for content files probably requires switching from dotnet pack to nuspec

**Comment by karolz-ms** [comment]
Fixed. Will be part of 1.0 release
