### ISSUE TITLE
EventHub Output: How to output Event Hub Partition Key

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/diagnostics-eventflow#191]
We use EventSource inputs and output events to EventHub using EventFlow. We want to process the events in Event Hub using partitioning to make sure related events are handled by the same Event Hub "consumer" instance.
So my question is, how can we provision an EventSource to output the PartitionKey that is outputted to Event Hub by EventFlow?

**Comment by karolz-ms** [comment]
@tedvanderveen I assume you are asking about a mechanism to send event data to specific EventHub partition--is this correct?

If so, this is currently not supported, but could be relatively easily added

In your case, is it typical that a single service instance (or single EventFlow instance) writes to a single EventHub partition? Or is it the case that a single service instance will be writing to multiple EventHub partitions? I am asking because I am wondering if we can still batch events efficiently when explicit partitioning is used.

**Comment by tedvanderveen** [comment]
@karolz-ms hi! We are writing to a single Event Hub that is configured with 8 partitions. Nu providing an EventHub PartitionKey, we can assure that related events are processed nu the same EventHub consumer instance.

**Comment by karolz-ms** [comment]
@tedvanderveen thanks, I was thinking along same lines. So just to confirm, in your scenario, every EventSource event might potentially go to a different partition and would have to be examined individually?

**Comment by tedvanderveen** [comment]
@karolz-ms every event on EventHub shall be processed individually, but we need to be able to ensure that related events are processed by the same EventHub consumer receiver instance. This is exactly what the EventHub PartionKey is meant for. At the moment the EventFlow output to EventHub functionality does not set this PartionKey system property in the output event message, while EventHub best practices documentation recommed using this EventHub event metadata field.

**Comment by karolz-ms** [comment]
@tedvanderveen  We are not using Microsoft.ServiceBus.Messaging library; we are using Microsoft.Azure.EventHubs https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs?view=azure-dotnet, which I believe is now the recommended library to interact with EH. 

In that library if you want to send events to specific partition, you use SendAsync overload that takes partitionKey parameter: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventhubclient.sendasync?view=azure-dotnet#Microsoft_Azure_EventHubs_EventHubClient_SendAsync_System_Collections_Generic_IEnumerable_Microsoft_Azure_EventHubs_EventData__System_String_

**Comment by tedvanderveen** [comment]
@karolz-ms the point is that I want to use EventSource in combination with EventFlow do we van mix andere match inputs andere various outputs. Without direct dependencies in our code to any EventHub specifics. Keep it agnostic.

**Comment by tedvanderveen** [comment]
Hi @karolz-ms, I notice that at the moment this library does not leverage this overload that you mentioned: 
https://github.com/Azure/diagnostics-eventflow/blob/92158e4ab0ee0d1fc5e45fe3c210cf4cc70b02ba/src/Microsoft.Diagnostics.EventFlow.Outputs.EventHub/EventHubOutput.cs#L114
By not specifying a `partitionKey` via the `SendAsync()` overload, the partitionKey is basically assigned quite randomly by EventHub itself and so we loose control over this powerful partitioning feature, especially true in case the consuming end of the EventHub instance wants to distribute load or make sure that related events are processed by the same EventHub listener/processor.
What would be a good way to optionally take a field value from the input stream and apply that value in the partitionKey overload?

**Comment by karolz-ms** [comment]
I was thinking along pretty much the same lines. Let me try to get to implementing this in the next few days, stay tuned

**Comment by tedvanderveen** [comment]
Please let me know if I can contribute @karolz-ms

**Comment by karolz-ms** [comment]
Hey, if you have something working, by all means please share! We welcome outside contributions very much

**Comment by tedvanderveen** [comment]
@karolz-ms I created a PR #203 that implements this feature.

**Comment by tedvanderveen** [comment]
@karolz-ms I pushed extended tests for the #203 , but run into this #205 when I try to run the tests.

**Comment by tedvanderveen** [comment]
@karolz-ms PR #203 all shiny and ready to close this issue.

**Comment by karolz-ms** [comment]
EventHub output package version 1.3.1 that has the partition key implementation has been submitted to Nuget. Thanks again!!
