### ISSUE TITLE
ElasticSearch error with multiple events

### ISSUE THREAD

**Issue by knowhoper** [Azure/diagnostics-eventflow#192]
I am using the following eventFlowConfig.json and experience errors if we output many log entries in a short space of time to ElasticSearch. EventFlow then stops outputting to ES.

Config:

```
{
    "inputs": [
        {
            "type": "EventSource",
            "sources": [
                { "providerName": "Microsoft-ServiceFabric-Services" },
                { "providerName": "Microsoft-ServiceFabric-Actors" },
                { "providerName": "Application1" }
            ]
        },
        {
            "type": "Trace",
            "traceLevel": "Info"
        },
        {
            "type": "Microsoft.Extensions.Logging"
        }

    ],
    "outputs": [
        {
            "type": "ElasticSearch",
            "indexNamePrefix": "RTHS",
            "serviceUri": "http://localhost:9200",
            "eventDocumentTypeName": "event"
        },
        {
            "type": "StdOutput"
        }
    ],
    "healthReporter": {
        "type": "CsvHealthReporter",
        "logFileFolder": ".",
        "logFilePrefix": "HealthReport",
        "minReportLevel": "Debug",
        "throttlingPeriodMsec": "1000",
        "singleLogFileMaximumSizeInMBytes": "8192",
        "logRetentionInDays": "30",
        "ensureOutputCanBeSaved": "false"
    },
    "schemaVersion": "2016-08-11",
    "extensions": []
}
```

Error:

> Warning
>  Unhealthy deployed service package: ApplicationName='fabric:/Applicatio1', ServiceManifestName='Application1Pkg', ServicePackageActivationId='2f2b2c44-92bf-47de-a928-5e59b0403a7a', NodeName='_Node_1', AggregatedHealthState='Warning'.
>                 Event	
> Warning
>  Unhealthy event: SourceId='Application1', Property='Connectivity', HealthState='Warning', ConsiderWarningAsError=false.
>   ElasticSearchOutput: request resulted in an error: Debug information: Invalid NEST response built from a successful low level call on POST: /_bulk
> # Invalid Bulk items:
>   operation[0]: index returned 403 _index: rths-2018.03.21 _type: event _id: veoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[1]: index returned 403 _index: rths-2018.03.21 _type: event _id: vuoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[2]: index returned 403 _index: rths-2018.03.21 _type: event _id: v-oSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[3]: index returned 403 _index: rths-2018.03.21 _type: event _id: wOoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[4]: index returned 403 _index: rths-2018.03.21 _type: event _id: weoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[5]: index returned 403 _index: rths-2018.03.21 _type: event _id: wuoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[6]: index returned 403 _index: rths-2018.03.21 _type: event _id: w-oSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[7]: index returned 403 _index: rths-2018.03.21 _type: event _id: xOoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[8]: index returned 403 _index: rths-2018.03.21 _type: event _id: xeoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[9]: index returned 403 _index: rths-2018.03.21 _type: event _id: xuoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[10]: index returned 403 _index: rths-2018.03.21 _type: event _id: x-oSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[11]: index returned 403 _index: rths-2018.03.21 _type: event _id: yOoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[12]: index returned 403 _index: rths-2018.03.21 _type: event _id: yeoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[13]: index returned 403 _index: rths-2018.03.21 _type: event _id: yuoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[14]: index returned 403 _index: rths-2018.03.21 _type: event _id: y-oSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[15]: index returned 403 _index: rths-2018.03.21 _type: event _id: zOoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[16]: index returned 403 _index: rths-2018.03.21 _type: event _id: zeoSRmIBlOOpMzK_tQOj _version: 0 error: Type: cluster_block_exception Reason: "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
>   operation[17]: index returned 403 _index: rths-2018.03.21 _type: event _id: zuoSRmIBlOOpMzK_tQOj _version: 0 erro [Truncated]
> 

Am i missing some configuration? Any help would be much appreciated.

Thanks in advance.

**Comment by karolz-ms** [comment]
A quick search uncovered many threads about this error on Elastic forums, and also on stackoverflow, for example:

https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282/3
https://stackoverflow.com/questions/48119189/elasticsearch-6-index-change-to-read-only-after-few-second

Looks like ES is running out of (or _thinks_ it is running out of) disk space. I am not an ES expert by any means but it does not seem like a problem unique to EventFlow.
