### ISSUE TITLE
Telemetry correlation in app insights using event flow. 

### ISSUE THREAD

**Issue by whizlingo** [Azure/diagnostics-eventflow#194]
We want to populate our own request id in the telemetry.Context.Operation.Id when the event flow pushes events to App insights . Is there a way i can do that using Filters e.t.c ?. 

 https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation

**Comment by karolz-ms** [comment]
@whizlingo sorry, this is not possible today because setting the operation ID/operation parent ID is something that the Application Insights output does and it currently does not provide any means of extending its functionality.

Can you tell me a bit more about the context in which you are using Event Flow? Maybe we can come up with some workaround

**Comment by whizlingo** [comment]
Thanks @karolz-ms , We are currently not using event flow diagnostics. The current implementation uses Serilog as logger pushing the events directly to App insights. During the process we have a custom implementation which uses asp.net core middleware to populates serilog LogContext with the request id if applicable. We then do a check if the property exists, if yes then update the telemetry context before synching the Operation id.  This is needed to populate the operation id  in our global app insights instance. It makes it easier for us to correlate  logs in a distributed environment.

We now want to add flexibility of adding filters and use different output based on the client type. We thought of using event flow in this scenario as found it pretty straightforward to use.

**Comment by karolz-ms** [comment]
If you are already using Application Insights and are looking for multi-output capability, Application Insights has native support for that. There is a concept of `TelemetrySink` and you can have multiple of these. A sink is a combination of a telemetry processor chain (~filter in EventFlow) ending up with a channel (~output in EventFlow).

See https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/Test/Microsoft.ApplicationInsights.Test/Shared/Extensibility/TelemetrySinkTests.cs for some usage examples. There is also a few examples on how to enable multiple sinks through configuration here https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/Test/Microsoft.ApplicationInsights.Test/Shared/Extensibility/TelemetryConfigurationFactoryTest.cs

The only problem is that, as of today and unlike EventFlow, Application Insights does not have many ready-to-use channels, so you would have to write the one that you need yourself (or port EventFlow output(s) that you need, repackaging it as Application Insights channel(s)).

Alternative is to wait for EventFlow to support correlation natively, but that might take a while to implement :-)

**Comment by karolz-ms** [comment]
Closing for now, but please feel free to contact us with further questions or suggestions as necessary
