### ISSUE TITLE
Adding a filter to drop events based on a custom property.

### ISSUE THREAD

**Issue by whizlingo** [Azure/diagnostics-eventflow#197]
We are currently using Serilog with event flow and wanted to put a subset of events from Serilog input to SQL output. We want to write a filter on one of our own custom property that we have on the event. Is it possible or are we limited to using the ones defined in event data (for e.g. Log level,event id e.t.c ) ?. If possible can you provide a quick snippet of such a filter which uses a custom field from payload in the logical expression ?.

**Comment by karolz-ms** [comment]
The standard drop filter should work with any custom property in the payload. All expressions described in https://github.com/Azure/diagnostics-eventflow#logical-expressions should work with custom properties too.

Let me know how it works for you!

**Comment by whizlingo** [comment]
Thanks @karolz-ms , i figured out the issue in my code. Thanks again.
