### ISSUE TITLE
AI Dependency Metadata and EventSource 

### ISSUE THREAD

**Issue by jsturtevant** [Azure/diagnostics-eventflow#207]
The Service Fabric templates create an EventSource logging by default.  I am trying to use Eventflow to push the EventSource events to Application Insights.  This works well for events with filters on the AI output, for example:

```csharp
# eventflow config (just showing output configuration)
"outputs": [
    {
      "type": "ApplicationInsights",
      "instrumentationKey": "servicefabric:/DiagnosticPipelineParameters/ApplicationInsightsKey",
      "filters": [
        {
          "type": "metadata",
          "metadata": "ai_event",
          "include": "ProviderName==MyCompany-DeviceSimulation-DeviceSimulator && EventId==100",
          "eventName": "DeviceConnected"
        }
]
# event
ServiceEventSource.Current.DeviceConnected(Context, simulationItem, device);
```

When it comes to tracking Application Dependencies, there is a Dependency metadata filter that can convert an event to AI dependency requires `isSuccessProperty` and `durationProperty` values.  

In EventSource the typical pattern is to use  `EventStart` and `EventStop`,  the Service Fabric example has the following in the sample code that is generated, which states that `start` and `stop` enable profiling tools to calculate these values such as duration

```csharp
// A pair of events sharing the same name prefix with a "Start"/"Stop" suffix implicitly marks boundaries of an event tracing activity.
// These activities can be automatically picked up by debugging and profiling tools, which can compute their execution time, child activities,
// and other statistics.
private const int ServiceRequestStartEventId = 5;
[Event(ServiceRequestStartEventId, Level = EventLevel.Informational, Message = "Service request '{0}' started", Keywords = Keywords.Requests)]
public void ServiceRequestStart(string requestTypeName)
{
     WriteEvent(ServiceRequestStartEventId, requestTypeName);
 }

private const int ServiceRequestStopEventId = 6;
[Event(ServiceRequestStopEventId, Level = EventLevel.Informational, Message = "Service request '{0}' finished", Keywords = Keywords.Requests)]
public void ServiceRequestStop(string requestTypeName, string exception = "")
{
      WriteEvent(ServiceRequestStopEventId, requestTypeName, exception);
}
```

The challenge is that to create a AI Dependency with EventSource and AI, and I would need to fire another event with the `isSuccessProperty` and `durationProperties` included and calculate the durations my self.  Could event flow make this easier by using the using the semantics of Start and End and generate those values for us?  A simple configuration would be:

```json
{
          "type": "metadata",
          "metadata": "dependency",
          "include": "ProviderName==MyCompany-DeviceSimulation-DeviceSimulator",
           "startEvent": "DeviceSendStart",
           "stopEvent": "DeviceSendStop",
            "targetProperty": "dependencyname"
}
```

And then usage would be:

```csharp
ServiceEventSource.Current.DeviceSendStart(this.Context, this.simulationItem, device);
await device.SendEventAsync(newDeviceStateJson, simulationItem.MessageType);
ServiceEventSource.Current.DeviceSendStop(this.Context, this.simulationItem, device);
```

With the `Success` and `duration` calcuation done automatically when pumped to the output.  Does this make sense and is it possible?

**Comment by karolz-ms** [comment]
The typical pattern is that the "Stop" event carries information about duration and outcome. So you do not need a separated event, but yes, you'd have to calculate the duration yourself. You can simplify this by some sort of wrapper method, or, if the framework you use supports that, push the event generation into some sort of an action decorator like `IActionFilter` in ASP.NET Core.

Pushing duration calculation to the output is not a good idea for various reasons. In introduces additional state into the output, making it more complicated and error-prone. It is also not necessarily the case that (stop event timestamp) - (start event timestamp) == dependency call duration.

**Comment by karolz-ms** [comment]
Let me know if you have further questions
