### ISSUE TITLE
HttpOutput sets health state of Service Fabric application to Warning

### ISSUE THREAD

**Issue by bonussoft** [Azure/diagnostics-eventflow#208]
We are using output type 'Http' to send logs to logstash. Every now and then the endpoint is not reachable. In such cases the HttpOutput sets the health state of our Service Fabric application to 'Warning'. Unfortunately the state remains 'Warning'even if all subsequent calls are successful. We expect that the state is changed to 'Ok' if the Http requests recover.

**Comment by karolz-ms** [comment]
This should be now fixed with the 1.4 version of the Http output Nuget package
