### ISSUE TITLE
filter documentation or filter may need to be modified 

### ISSUE THREAD

**Issue by Danwich** [Azure/diagnostics-eventflow#21]
for the json filtering section it seems like it is looking for EventId instead of id as the documentation indicates.  The include statement I used was "include": "ProviderName == MyProvider && EventId == 7", instead of "include": "ProviderName == MyProvider && id == 7",

**Comment by yantang-msft** [comment]
Hi Danwich, thank you for pointing this out. I've submitted a PR to eliminate the confusion.
However, one thing to point out is that the you can specify any property name for the filter. You probably used the EventSource input, where the property name is "EventId". But for other inputs, it might be different. You can also use the StdOutput to check what properties does an event have.

**Comment by karolz-ms** [comment]
thanks for pointing this out @Danwich Docs have been updated
