### ISSUE TITLE
RotateLogFileImp throws WinIOError exception failing my app in the runtime

### ISSUE THREAD

**Issue by ninjaboy** [Azure/diagnostics-eventflow#216]
Hi all

Having no `healthReporter` settings in the config leads to default settings instantiated which leads to the following failure that prevents my app to execute in runtime.

```
System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
System.IO.__Error.WinIOError()
System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
System.IO.File.Move(String sourceFileName, String destFileName)
Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFileImp(String logFileFolder, Func`2 fileExist, Action`1 fileDelete, Action`2 fileMove)
Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFile(String logFileFolder)
Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.SetNewStreamWriter()
Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.Activate()
Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(IConfiguration configuration, IHealthReporter healthReporter)
Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(String jsonConfigFilePath)
Poplar.Application.Host.AppDomain.ServiceInProcessHost.Start()
```

I would expect logging/diagnostics library to either fail reporting to internal logs or to find a workaround for the issue (reporting to the internal logs).

Is there anything I can do to:
1. Completely disable healthReporter
2. Fix log rotation somehow (preferrably in an automated manner)

Thanks in advance

**Comment by karolz-ms** [comment]
@ninjaboy first, can you describe the context in which you are using EventFlow: what is your application etc. Also what specifically is the WinIOError that you are encountering?

I would first try to ensure that the working folder for the standard health reporter (`CsvHealthReporter`) is writable. Refer to the docs https://github.com/Azure/diagnostics-eventflow#csvhealthreporter , `logFileFolder` configuration property specifically.

If your application has absolutely no good place to write the health reporter file to, you can  disable the standard health reporter by setting its configuration property `ensureOutputCanBeSaved` property to false.

Finally you can substitute the standard health reporter with your own implementation that does something more appropriate for your application. See [an example here](https://github.com/Azure/diagnostics-eventflow/blob/master/test/Microsoft.Diagnostics.EventFlow.Core.Tests/DiagnosticsPipelineFactoryTests.cs#L69)

Let us know how it goes!

**Comment by ninjaboy** [comment]
@karolz-ms , hi Karol, sorry for the late reply.
The behaviour we found is that this error appears whenever the app is run without Admin permissions, which basically corresponds to your suggestion to check access rights.
I think the case can be closed, considering the other options you have provided.

Thanks!

**Comment by iblazhko** [comment]
Hi @karolz-ms ,

I am trying to use EventFlow and having exactly the same problem as described above:

```
---- System.IO.IOException : The process cannot access the file because it is being used by another process.
Stack Trace:
----- Inner Stack Trace #1 (System.IO.IOException)
-----
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFileImp(String logFileFolder, Func`2 fileExist, Action`1 fileDelete, Action`2 fileMove)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFile(String logFileFolder)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.SetNewStreamWriter()
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.Activate()
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(IConfiguration configuration, IHealthReporter healthReporter)
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(String jsonConfigFilePath)
```

Setting configuration property `ensureOutputCanBeSaved` property to `false` did not help, still have the same error.

I have also attempted to implement custom health reporter, but that did not work either - my project where I need to use it, refrerences EntityFrameworkCore and this leads to conflict of versions:

```
Error NU1107
Version conflict detected for Microsoft.Extensions.Configuration.Binder. Reference the package directly from the project to resolve this issue. 

... -> Microsoft.EntityFrameworkCore 2.1.0 -> Microsoft.Extensions.Logging 2.1.0 -> Microsoft.Extensions.Configuration.Binder (>= 2.1.0) 
... -> EventFlow.Extensions -> Microsoft.Diagnostics.EventFlow.Core 1.4.1 -> Microsoft.Extensions.Configuration.Binder (>= 1.1.1 && < 2.0.0)
```

The project has binding redirect directives:
```
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```

but that does not make any difference as far as Error NU1107 is concerned.

Please advise how I can disable health reporting completely, that is not something that is required in our case and we would be happy to not have health reporting rather that being blocked by this error.

As a side note, we see health report files being created in unexpected places when `logFileFolder` is not set or set to `"."`:

- %USERPROFILE%\.nuget\packages\microsoft.diagnostics.eventflow.core\1.4.0\lib\netstandard2.0\
- %USERPROFILE%\AppData\Local\Temp\259aea5c-5d92-4773-b9d1-49a51ae4cc24\259aea5c-5d92-4773-b9d1-49a51ae4cc24\assembly\dl3\02622f49\00597b7e_f79ed301\HealthReport_20180405.csv

**Comment by karolz-ms** [comment]
@iblazhko looks like multiple processes are trying to write to the same health reporter file. What kind of application is this? Can you share the whole project file?

Regarding Ms.Ex.Configuration.Bindier error, the EntityFrameworkCore 2.x can only be used with apps that target .NET Core 2.x, NOT 1.x. From the version of EventFlow.Core lib that gets picked, looks like you are targeting .NET Core 1.x?

**Comment by iblazhko** [comment]
@karolz-ms I will try to create a small project that would demonstrates the problem.

**Comment by TrevorVonSeggern** [comment]
I was came into the same issue today. I was able to get around this exception by setting the LogFilePrefix in the healthReporter section to a random guid. Ex:

```
{
  "inputs": [
    {
      "type": "Log4net",
      "logLevel": "Debug"
    }
  ],
  "outputs": [
    {
      "type": "StdOutput"
    }
  ],
  "healthReporter": {
    "LogFilePrefix": "random guid injected here"
  }
}
```
