### ISSUE TITLE
Only the first message on application startup gets to the Elastic Search server

### ISSUE THREAD

**Issue by BuddhaBuddy1** [Azure/diagnostics-eventflow#226]
Microsoft.ServiceFabric 6.2.274
Microsoft.AspNetCore.All 2.0.8
Microsoft.Diagnostics.EventFlow.Inputs.EventSource 1.4.0
Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch 2.5.1
Elasticsearch.NET and Nest 6.1.0 (to get around error handling problem, so I can see the following problem)

ElasticSearch server is running 6.2.2, installed from XPath's template.

We are using Service Fabric, writing a ASP Net Core 2 application. The Service Fabric Visual Studio template generates a ServiceEventSource class that extends EventSource. Only the very first message, a call to ServiceEventSource.ServiceTypeRegistered(), ever appears in Elastic Search. There do not appear to be any errors in the Service Fabric cluster (there are no health warnings, anyway). I see many other messages in Visual Studio's Diagnostic Events tab, but not in the Elastic Search server.

One thing I'm noticing is that the structure of the message in Diagnostic Events is different than what is shown in Kibana.

Diagnostic Events:
```
{
  "Timestamp": "2018-05-24T13:07:55.6793053-07:00",
  "ProviderName": "MyCo-MyApp-MyService",
  "Id": 3,
  "Message": "Service host process 25168 registered service type MyService",
  "ProcessId": 25168,
  "Level": "Informational",
  "Keywords": "0x0000F00000000002",
  "EventName": "ServiceTypeRegistered",
  "ActivityID": null,
  "RelatedActivityID": null,
  "Payload": {
    "hostProcessId": 25168,
    "serviceType": "MyService"
  }
}
```

Kibana:
```
t _id 		[id]
t _index 		myapp-2018.05.24
# _score 		 - 
t _type 		diagData
# keywords 		263,882,790,666,241.969
# level 		4
# payload.EventId 		3
t payload.EventName 		ServiceTypeRegistered
t payload.Message 		Service host process 25168 registered service type MyService
# payload.hostProcessId 		25,168
t payload.serviceType 		MyService
t providerName 		MyCo-MyApp-MyService
timestamp 		May 24th 2018, 13:07:55.677
```

The payload in the Diagnostic Events is different than what is called payload in Kibana. I am not sure if it matters in Elastic Search, but the payload for other messages from service fabric is different than that first message. For example, a later message, generated by a call to , has a payload like this:
```
  "Payload": {
    "serviceName": "fabric:/MyApp/MyService",
    "serviceTypeName": "MyServiceType",
    "replicaOrInstanceId": [ID],
    "partitionId": "[GUID]",
    "applicationName": "fabric:/MyApp",
    "applicationTypeName": "MyAppType",
    "nodeName": "vm1",
    "message": "Starting Kestrel on http://+:8770"
  }
```

I don't know what that would look like in Kibana, but I assume the extra fields would be "payload.<fieldName>". Does that cause a problem in Elastic Search?

**Comment by karolz-ms** [comment]
How is EventFlow configured? What providers/EventSources are you listening to?

**Comment by BuddhaBuddy1** [comment]
```
{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        { "providerName": "Microsoft-ServiceFabric-Services" },
        { "providerName": "Microsoft-ServiceFabric-Actors" },
        // (replace the following value with your service's ServiceEventSource name)
        { "providerName": "MyCo-MyApp-MyService" }
      ]
    }
  ],
  "filters": [
    {
      "type": "drop",
      "include": "Level == Verbose"
    }
  ],
  "outputs": [
    {
      "type": "ElasticSearch",
      "indexNamePrefix": "MyApp",
      "serviceUri": "http://somewhere.in.azure.com:9200",
      "eventDocumentTypeName": "diagData",
      "numberOfShards": 1,
      "numberOfReplicas": 1,
      "refreshInterval": "15s",
      "useSniffingConnectionPooling":  false
    }  ]
}
```

**Comment by BuddhaBuddy1** [comment]
If normal logging messages in ServiceEventSource are considered Verbose, and they are just getting filtered out, I'm going to cry.

**Comment by BuddhaBuddy1** [comment]
OK, whew. I removed the filters section and had the same results. :-D

**Comment by karolz-ms** [comment]
Confirm you are using [ServiceFabricDiagnosticPipelineFactory](https://github.com/Azure/diagnostics-eventflow#service-fabric-support) and you do not see any health errors/warnings in SF cluster explorer?

**Comment by BuddhaBuddy1** [comment]
Yes, nothing in cluster since fixing the sniffing connection pool issue. We now get the one message, and that's it.
Here is my Program.cs:
```
namespace MyService
{
    internal static class Program
    {
        /// <summary>
        /// This is the entry point of the service host process.
        /// </summary>
        private static void Main()
        {
            try
            {
                // The ServiceManifest.XML file defines one or more service type names.
                // Registering a service maps a service type name to a .NET type.
                // When Service Fabric creates an instance of this service type,
                // an instance of the class is created in this host process.
                using (ManualResetEvent terminationEvent = new ManualResetEvent(initialState: false))
                using (var diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("MyCo-MyApp-MyService"))
                {
                    Console.CancelKeyPress += (sender, eventArgs) => Shutdown(diagnosticsPipeline, terminationEvent);

                    ServiceRuntime.RegisterServiceAsync("MyServiceType",
                    context => new MyService(context)).GetAwaiter().GetResult();

                    ServiceEventSource.Current.ServiceTypeRegistered(Process.GetCurrentProcess().Id, typeof(MyService).Name);
                }
                // Prevents this host process from terminating so services keeps running. 
                Thread.Sleep(Timeout.Infinite);
            }
            catch (Exception e)
            {
                ServiceEventSource.Current.ServiceHostInitializationFailed(e.ToString());
                throw;
            }
        }
        private static void Shutdown(IDisposable disposable, ManualResetEvent terminationEvent)
        {
            try
            {
                disposable.Dispose();
            }
            finally
            {
                terminationEvent.Set();
            }
        }
    }
}
```

**Comment by karolz-ms** [comment]
OK, thanks. Can you do a bit more poking around to narrow down the problem please:

1. From your service code, can you raise some events from the `ServiceEventSource` (e.g. there should be a Message event). Confirm you see them in VS Diagnostic Window when running the service locally, but not in Elasticsearch when running in Azure
1. Confirm that you do see events from Microsoft-ServiceFabric-Services and/or Microsoft-ServiceFabric-Actors when running locally, but they do not get to your Elasticsearch. Please make sure that you really see events from these two EventSources and not from Microsoft-ServiceFabric (no suffix)
1. (Bonus question) If possible, try a different output provider (e.g. Application Insights, EventHub, HTTP)--is it also not working? In other words, does it look like the EventSource events are not being captured, or is this a problem unique to Elasticsearch output

If none of the above provides enough clues, I will a sample app that demonstrates the problem, please

**Comment by BuddhaBuddy1** [comment]
We raise lots of events, and I do see them in Diagnostic Events. The first codeblock in my original post is copied from the Diagnostic Events window from the event that does get through to Elastic Search, and the last codblock is copied from there as well, but from one of the messages that does NOT get through to Elastic Search.

We used to log to OMS, but it seemed flaky. It would sometimes get all my messages, and sometimes get none of them, and sometimes they would show up hours later. We don't have that instance any more. We were going to try to go through Event Hub, then from there to Elastic Search, to see if we could get around the problem of not being able to connect to Elastic Search directly. I have not got to the point where I can view the messages in Event Hub, but the NUMBER of messages it received looked correct.

**Comment by BuddhaBuddy1** [comment]
Here are the steps to repro from scratch.

Launch Visual Studio in Admin mode
New Service Fabric Application
Name: ElasticTest
Next
.Net Core 2.0, Statless ASP.NET Core
Service Name: ElasticService
OK
API (No Authentication)
OK
Right-click ElasticService -> Manage NuGet Packages
Microsoft.Diagnostics.EventFlow.ServiceFabric (1.4.0)
Microsoft.Diagnostics.EventFlow.Inputs.EventSource (1.4.0)
Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch (2.5.1)

Add eventFlowConfig.json
```
{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        { "providerName": "Microsoft-ServiceFabric-Services" },
        { "providerName": "Microsoft-ServiceFabric-Actors" },
        // (replace the following value with your service's ServiceEventSource name)
        { "providerName": "MyCompany-ElasticTest-ElasticService" }
      ]
    }
  ],
  "outputs": [
    {
      "type": "ElasticSearch",
      "indexNamePrefix": "elastictest",
      "serviceUri": "http://somewhere.in.azure.com:9200",
      "eventDocumentTypeName": "diagData",
      "numberOfShards": 1,
      "numberOfReplicas": 1,
      "refreshInterval": "15s",
      "useSniffingConnectionPooling": false
    }
  ]
}
```
**serviceUri might have to be in a different network to repro.**

Right-click on Solution -> Properties
	Select "Single startup project", set to ElasticService
Select Configuration Properties, make sure all available Build/Deploy checkboxes are checked.
OK
Right-click ElasticTest project -> Properties
Change Application Debug Mode to Remove Application (Refresh doesn't seem to work well)

Replace Program.cs:Main() with
```
        private static void Main()
        {
            try
            {
                // The ServiceManifest.XML file defines one or more service type names.
                // Registering a service maps a service type name to a .NET type.
                // When Service Fabric creates an instance of this service type,
                // an instance of the class is created in this host process.
                using (ManualResetEvent terminationEvent = new ManualResetEvent(initialState: false))
                using (var diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("MyCompany-ElasticTest-ElasticService"))
                {
                    Console.CancelKeyPress += (sender, eventArgs) => Shutdown(diagnosticsPipeline, terminationEvent);

                    ServiceRuntime.RegisterServiceAsync("ElasticServiceType",
                    context => new ElasticService(context)).GetAwaiter().GetResult();

                    ServiceEventSource.Current.ServiceTypeRegistered(Process.GetCurrentProcess().Id, typeof(ElasticService).Name);
                }
                // Prevents this host process from terminating so services keeps running. 
                Thread.Sleep(Timeout.Infinite);
            }
            catch (Exception e)
            {
                ServiceEventSource.Current.ServiceHostInitializationFailed(e.ToString());
                throw;
            }
        }
        private static void Shutdown(IDisposable disposable, ManualResetEvent terminationEvent)
        {
            try
            {
                disposable.Dispose();
            }
            finally
            {
                terminationEvent.Set();
            }
        }
```

Add using clause:
`using Microsoft.Diagnostics.EventFlow.ServiceFabric;`

Go to ValuesController.cs:Get() and before the return add:
`            ServiceEventSource.Current.Message("In Get()");`

F5

After this installs and the API is hit, I have 8 items in Diagnostic Events. The first two are from providers not in eventFlowConfig, the FM and CM events. All the others should be, but only the first, ServiceTypeRegistered, is in Elastic Search.

This is in reverse order from what Diagnostic Events shows, as that has the newest on top. This is the order they occurred.
```
ServiceTypeRegistered: providerName=MyCompany-ElasticTest-ElasticService
ServiceMessage: providerName=MyCompany-ElasticTest-ElasticService
StatelessRunAsyncInvocation: providerName=Microsoft-ServiceFabric-Services
StatelessRunAsyncCompletion: providerName=Microsoft-ServiceFabric-Services
Message:  providerName=MyCompany-ElasticTest-ElasticService
Message:  providerName=MyCompany-ElasticTest-ElasticService
```

Go to Kibana Management, Index Patterns -> Create Index Pattern
elastictest*
Next
Selected timestamp, clicked Create Index Pattern
Go to Discover
Select "elastictest*" from index dropdown

Only see one message.

**Comment by karolz-ms** [comment]
@BuddhaBuddy1  ehm, turns out to be a trivial mistake, but hard to spot. First, in Program.cs:Main() method, the call to `Thread.Sleep(Timeout.Infinite)` should be replaced with `terminationEvent.WaitOne()` (was it incomplete copy of the example in the docs?). As-is the Ctrl-C handler (`Shutdown()` method) has no effect.

Also, and more importantly, that call should be *inside the using block*. As it is right now, the pipeline is disposed immediately after the service type is registered--no wonder you are getting just that one event! :-)

Please confirm things work as expected after making these changes

**Comment by BuddhaBuddy1** [comment]
Ouch, thanks!
I copied them from another example, but obviously incorrectly! :-(

**Comment by BuddhaBuddy1** [comment]
Well, my network guy took down my test ELK stack for some reason. I'll reply with confirmation once I have access again.

**Comment by karolz-ms** [comment]
Roger

**Comment by BuddhaBuddy1** [comment]
Yes, works like a charm, thanks for the fixes!

**Comment by karolz-ms** [comment]
Cool, glad this turned out to be a false alarm
