### ISSUE TITLE
Duplicated properties

### ISSUE THREAD

**Issue by lmolkova** [Azure/diagnostics-eventflow#23]
Some of the inputs allow additional properties to be passed with message and such properties are added to `EventData.Payload`.
Such inputs are 
- EventSource
- Serilog

However, they may have the same key as predefined payload properties such as `Message` or `EventId`.
We should make sure inputs handle this case in the same way. See Karol's comment on #18

> Agreed that all inputs should behave the same way. Feel free to open an issue about this and we can deal with it as a separate change.
> 
> I think whatever the original event carries should take priority over what the input adds. So if there is a "Message" property on the event, we should not overwrite it. We could either skip input additions completely or make the added property name unique, e.g. by appending random number at the end of the name. These are, essentially, variations of the (1) option you have. I have slight preference for the latter. 
> 
> I do not think using a separate dictionary is a good idea. It will make the output code and, ultimately, consumption of the data much more complicated, for a marginal benefit.
> 
> Oh, and I would just report a warning, not an error, if a name collision happens, esp. if you decide to make the added property name unique and include the data, mitigating the conflict.

**Comment by karolz-ms** [comment]
Fixed by 11fb2a2e52193524423e4bb4f667a2037c4f558e
