### ISSUE TITLE
Filtering on Payload not possible

### ISSUE THREAD

**Issue by kwaclaw** [Azure/diagnostics-eventflow#230]
I added this filter
```
  "filters": [
    { // we drop events from all other WCF services except ours
      "type": "drop",
      "include": "Payload.AppDomain != MobilityServicesHost.exe"
    }
  ],
```
This does not filter at all. The HealthReport CSV files is empty, indicating no exceptions were thrown.
I also tried  ` "include": "Payload.[\"AppDomain\"] != MobilityServicesHost.exe"`

Is this a bug or is it simply not supported?

**Comment by kwaclaw** [comment]
Yes, that worked, Thank you!
Did I overlook something in the docs?

**Comment by karolz-ms** [comment]
Not really, this was not very well explained, sorry about that! I have just added the following paragraph to the [Logical Expressions section](https://github.com/Azure/diagnostics-eventflow#logical-expressions); hopefully this makes it more clear.

Standard and custom (payload) properties are treated equally; there is no need to prefix custom properties in any way. For example, expression `TenantId != Unknown && ProviderName == MyEventProvider` will evaluate to true for events that 
  - were created by `MyEventProvider` provider (ProviderName is a standard property available for all events), and
  - have a TenantId custom property, with value that is different from "Unknown" string.
