### ISSUE TITLE
keywords not recognized in hex notation

### ISSUE THREAD

**Issue by kwaclaw** [Azure/diagnostics-eventflow#231]
I am using the ETW inout and try to enable based on a keyword mask.
The docs suggest that hex notation is OK to use, but it seems it does not work at least for large keywords. That is, I get no events collected.
However, the same bitmask supplied in decimal notation works.

This is the example:
```
  "inputs": [
    {
      "type": "ETW",
      "providers": [
        { // this covers all WCF services on the machine
          "providerName": "Microsoft-Windows-Application Server-Applications",
          //"providerGuid": "{C651F5F6-1C0D-492E-8AE1-B4EFD7C9D503}",
          "level": "Informational",
          "keywords": "2305843009213694000" //  works
          // "keywords": "0x2000000000000030" // does not work
        }
      ]
    }
  ],
```

**Note**:
The high bits come from enabling a WCF specific keyword called ChannelKeywords.Analytic.
Taken from WcfEventSource.cs (https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs)

```
  public class ChannelKeywords
  {
      public const EventKeywords Admin = unchecked((EventKeywords)0x8000000000000000);
      public const EventKeywords Operational = unchecked((EventKeywords)0x4000000000000000);
      public const EventKeywords Analytic = unchecked((EventKeywords)0x2000000000000000);
      public const EventKeywords Debug = unchecked((EventKeywords)0x1000000000000000);
  }

```

**Comment by karolz-ms** [comment]
Can you try the number without the quotes, ie `"keywords": 0x200F`? I think the parser might be interpreting the number as string if it is quoted

**Comment by kwaclaw** [comment]
That would not be valid JSON.

**Comment by karolz-ms** [comment]
You are right, 0x is valid in JavaScript but not in JSON, bummer. Will have to take a closer look to see what is going on here. Thanks for reporting the issue!

**Comment by karolz-ms** [comment]
So the technical reason for the error is the fact that Keywords property is defined as an enumeration, plus the following (which is used by `Microsoft.Extensions.Configuration` to parse the Keywords property value):

```
> Enum.Parse(typeof(System.ComponentModel.BindingDirection), "0x1")
Requested value '0x1' was not found.
  + System.Enum.TryParseEnum(System.Type, string, bool, ref System.Enum.EnumResult)
  + System.Enum.Parse(System.Type, string, bool)
  + <Initialize>.MoveNext()
> Enum.Parse(typeof(System.ComponentModel.BindingDirection), "1")
TwoWay
```

This is quite unfortunate as hex notation is very useful for keywords. I am thinking about adding a pre-processing step where values for keywords property would be converted to decimal notation before being passed to `ConfigurationBinder.Bind()`. Let me know if you have a better idea!

**Comment by karolz-ms** [comment]
ETW input version 1.4.0 solves this issue. Thanks for reporting!
