### ISSUE TITLE
ETW input - cleanup of trace sessions

### ISSUE THREAD

**Issue by kwaclaw** [Azure/diagnostics-eventflow#232]
I run into this problem really often: while stopping WCF services (self-hosted) from the debugger, or by closing the console Window, the ETW TraceSeccion created by EtwInput is  not cleaned up (as finalizers are not run). I also tried the ProcessExit and DomainUnload events for cleanup, without success.

So after a handful of debug sessions I get the dreaded "Insufficient system resources" error because Windows only supports a very small number of active trace sessions. Solutions could be:

1. Supply a session name or a session name pattern in the configuration. EtwInput will either attach to an existing trace session with that name, or create a new one if necessary.

2. If EtwInput supported a way of getting at the session name, I could save the session name to the file system and on next application start, clean it up before starting the new pipeline.

3. If EtwInput also support attaching to an existing session, I could have it attach to the saved session name instead of creating a new one.

Or does anyone know a better way for cleaning up ETW trace sessions?

**Comment by karolz-ms** [comment]
Disposing of the pipeline (i.e. leveraging the fact that it implements `IDisposable`) should dispose of all pipeline elements and, in particular, cause ETW input to release the session. Is that not happening? Is it difficult to dispose of the pipeline in your debugging scenarios?

**Comment by kwaclaw** [comment]
I am using it the correct way, I am disposing it - see the actual code:
```
    class Program {
        [STAThread]
        static void Main(string[] args) {
            using (var pipeline = DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json")) {
                ServiceStartup.StartServices();
                MyServiceHostManager.StopServicesInteractively(5);
                Console.ReadLine();
            }
        }
    }
```

But there are many scenarios where the Dispose is not called. One is when you stop debugging, another is when you simply close the console Window instead of pressing a key. Unfortunately these scenario are frequent, at least when developing.

**Comment by karolz-ms** [comment]
I could see the ETW input take an optional "session name prefix" configuration parameter and search for existing session(s) upon startup. If any exist, kill them and then create a new session, using the configured prefix. This way you get a clean session, with just the providers you wanted to track (configuration may have changed between invocations of the program/service that uses the ETW input).

This would of course only work if the ETW input with particular name prefix is a singleton instance on the system.

Would you be willing to take a stab at implementing this and submit a PR?

**Comment by kwaclaw** [comment]
I'll have a look, might have to wait a little - full time job, always busy.

**Comment by kwaclaw** [comment]
OK, found a little time, pull request created.

**Comment by karolz-ms** [comment]
Cool. Let's continue with the PR
