### ISSUE TITLE
Implement log4net input plugin

### ISSUE THREAD

**Issue by jeremysmith1** [Azure/diagnostics-eventflow#235]
I have a code base that uses log4net throughout. I would like to use eventflow to send out the logs.

Would a input plugin for log4net be desired? It does not look like it has been attempted before.

I was thinking I could do it similar to how Serilog is done.

**Comment by karolz-ms** [comment]
@jeremysmith1 yes, absolutely, if you are willing to send us a PR, it will be very welcome

**Comment by karolz-ms** [comment]
No problem. I have been slacking a bit too, now that the summer is in full swing ☺️

**Comment by karolz-ms** [comment]
The input has now been published on Nuget, but let's keep this issue open as a reminder that the README needs to be updated too

**Comment by karolz-ms** [comment]
Looks like Nuget package failed validation--there is some glitch with package signing. Investigating...

**Comment by karolz-ms** [comment]
The package has been published

**Comment by karolz-ms** [comment]
Thanks for updating the docs, Jeremy. The input is now complete!
