### ISSUE TITLE
Microsoft.Extensions.Configuration.Abstractions dependency version constraint of Microsoft.Diagnostics.EventFlow.Core package

### ISSUE THREAD

**Issue by vladislav-karamfilov** [Azure/diagnostics-eventflow#236]
Is there any reason for the new version of `Microsoft.Diagnostics.EventFlow.Core` (1.4.1) to introduce the upper version limit of the `Microsoft.Extensions.Configuration.Abstractions` dependency (constraints `>= 1.1.1 && < 2.0.0`)? I can see that this was introduced in v1.4.1 but I cannot see why is this constraint introduced and why is this for `.NETFramework 4.5.1` and `.NETStandard 1.6` only.

**Comment by karolz-ms** [comment]
Yes. There have been breaking changes between version 1.x and 2.x of the `Microsoft.Extensions.Configuration` library. See [issue 171](https://github.com/Azure/diagnostics-eventflow/issues/171) for more details.
