### ISSUE TITLE
PerformanceCounter configuration

### ISSUE THREAD

**Issue by mhjelmseth** [Azure/diagnostics-eventflow#238]
Hi

When using the PerformanceCounter input, it doesn't seem like changing the collectionIntervalMsec have any effect. It still samples every 30 seconds, which is the default value.

**Comment by karolz-ms** [comment]
@mhjelmseth sorry, this is a bug. The configuration parameter was meant to be named `collectionIntervalMsec` but the current implementation uses `samplingIntervalMsec` (note that for individual counters it starts with "sampling", not "sample", as it is at the top level). 

We need to clean this mess ASAP so I am going to keep this issue open for tracking, but for now the information above hopefully unblocks you.

**Comment by mhjelmseth** [comment]
Thanks, @karolz-ms, I will rename my configuration setting to 'samplingIntervalMsec' until this issue is fixed.

**Comment by karolz-ms** [comment]
PerformanceCounter input package 1.3.1 has the fix. Thanks again for reporting!
