### ISSUE TITLE
ETW input: ProcessID/ProcessName are likely to conflict with ETW event properties

### ISSUE THREAD

**Issue by karolz-ms** [Azure/diagnostics-eventflow#246]
Change https://github.com/Azure/diagnostics-eventflow/pull/239 added Process ID/Name to event data created by ETW input. Unfortunately these are common payload properties for ETW events (e.g. from Windows Process provider), resulting in property name conflicts when payload properties are added to `EventData` structure.

We could significantly reduce the likelihood of these conflicts by using a prefix, e.g. `EtwEventSourceProcessId` and `EtwEventSourceProcessName` respectively

@frblondin FYI and please let me know if you have any suggestions
@commonsensesoftware FYI

**Comment by frblondin** [comment]
No problem for me - as long as the information is somehow available!

**Comment by commonsensesoftware** [comment]
Agreed. Perhaps `TraceEventXXX` (ex: `TraceEventProcessId`) would work to make it clear the property is coming directly from the underlying `TraceEvent`.

In addition, when names do collide, it seems that there should be some _reasonable_ way to rationalize the duplicate property name. Currently, the appended number is completely random! (as seen [here](../blob/11fb2a2e52193524423e4bb4f667a2037c4f558e/src/Microsoft.Diagnostics.EventFlow.Core/Implementations/PayloadDictionaryUtilities.cs#L31)). Although subtle, there is also a flaw in the loop of this logic. Should there ever be more than 10 duplicates, however unlikely, this code will be stuck in an endless loop. Starting 1 and incrementing by 1 until there are no duplicates will both provide _some_ level of consistency and has no feasible chance of looping infinitely. Most cases will likely be a single duplicate key and iteration. In rare scenarios, there might be two iterations.

<end musings>

**Comment by karolz-ms** [comment]
@commonsensesoftware  hold on, looks like ETW input tests are completely disabled right now. Working to re-enable them...

**Comment by karolz-ms** [comment]
ETW input 1.4.1 uses `TraceEventProcessID` and `TraceEventProcessName` properties
Core package 1.4.2 employs sequential suffix until a unique property name is found
