### ISSUE TITLE
Read Only file system on Linux containers

### ISSUE THREAD

**Issue by mikehole** [Azure/diagnostics-eventflow#255]
Hi,

I have been trying to use eventflow within Linux containers but have hit the problem where creating the pipeline (`DiagnosticPipelineFactory.CreatePipeline`)  it throws up an System.IO.IOException: 'Read-only file system' exception. 

Not sure if there is there a work around for this or I am going about things in the right way so this may not be an issue. 

Cheers,

Mike

**Comment by karolz-ms** [comment]
@mikehole interesting, thanks for reporting. Can you share the configuration for your pipeline? What inputs/outputs are you using? Any nonstandard health reporters? What kind of application is this? What version of EventFlow Core package are you using? 

Maybe you can share a simple repro, that would be ideal.

**Comment by mikehole** [comment]
Hi Here is a simple repo that throws the read only file system error:

https://github.com/mikehole/eventflow-issue

**Comment by karolz-ms** [comment]
Looking...

**Comment by karolz-ms** [comment]
OK I think I understand the problem. Seems like a bug in the default health reporter. Hopefully with have a PR with a fix later today

**Comment by karolz-ms** [comment]
@mikehole EventFlow Core package 1.4.4, just published on Nuget, should fix this problem. Please test and let me know what you find!

**Comment by karolz-ms** [comment]
Assuming this is fixed... but let us know ASAP if there is still a problem!
