### ISSUE TITLE
Inputs.Log4net does not send data to Outputs

### ISSUE THREAD

**Issue by jeremysmith1** [Azure/diagnostics-eventflow#257]
tl;dr Add the following code **AFTER** you create the pipeline: `BasicConfigurator.Configure(LogManager.GetAllRepositories().FirstOrDefault(p => p.Name == "EventFlow"));`

Inputs.Log4net is using the log4net appender to send events. [https://logging.apache.org/log4net/release/faq.html#custom-appender](url)

The appender is being added as expected, but a call to BasicConfigurator.Configure(repoName) is needed for the appender to be used. Everything works after that.

I will do my best to get a PR for this over the coming weekend.

**Comment by karolz-ms** [comment]
I merged the PR but let's keep this issue open till we publish the updated package to Nuget

**Comment by karolz-ms** [comment]
The package (v. 1.0.1) has been published
