### ISSUE TITLE
.net framework 4.7.2 uses .net framework 4.5.1 nuget package

### ISSUE THREAD

**Issue by ghelyar** [Azure/diagnostics-eventflow#261]
I have a .net framework 4.7.2 project that references both [Microsoft.Extensions.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration/) 2.1.1 (a requirement of other packages) and other .net framework projects.

I want to use [Microsoft.Diagnostics.EventFlow.Core](https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Core/).

The .net framework 4.5.1 version of this package has a dependency restriction Microsoft.Extensions.Configuration.Abstractions (>= 1.1.1 && < 2.0.0)

The .net standard 2.0 version of this package has a dependency restriction Microsoft.Extensions.Configuration.Abstractions (>= 2.0.1)

.net framework 4.7.2 can use .net standard 2.0 packages, which would work in this case, but it picks the .net framework 4.5.1 package, so I can't use it.

As a simple reproduction, an asp.net core 2.1 project, targeting `net472`, just can't reference EventFlow at all.

Is it possible to force the project to reference the .net standard 2.0 version of the package? I would really not like to have to reference a dll directly.

If not, could a .net 4.7+ target be added to the package (and any related packages, like inputs and outputs, if they have the same problem) at some point that mirrors the .net standard 2.0 target's dependencies?

**Comment by karolz-ms** [comment]
Would it be possible for you to just switch to .NET Core 2.1 framework? If not, why?

We could add a 4.7 target to EventFlow packages like you said... and settle on Ms.Ex.Configuration 2.x for that target. Would you consider submitting a PR?

**Comment by ghelyar** [comment]
As there are references to other .net framework projects, some of which will likely never be net standard/core compatible, it can't just target .net core.

I will submit a PR as soon as I can.

**Comment by karolz-ms** [comment]
The packages (Core 1.5.0, EtwUtilities 1.6.0 and ServiceFabric 1.5.0) should be available from nuget.org.

Thank you for helping with this change, much appreciated.
