### ISSUE TITLE
Microsoft.Diagnostics.EventFlow.Inputs.Log4net nupkg not including .NET 451

### ISSUE THREAD

**Issue by xied75** [Azure/diagnostics-eventflow#264]
The dependency here https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Inputs.Log4net/1.0.1 shows it only support .NETFramework 4.6, which is higher than the core and other packages.

**Comment by karolz-ms** [comment]
Log4net itself supports only NET Standard 1.3 so .NET FX 4.5.x cannot be targeted. That has been the case at least since Log4net version 2.0.6 (December 2016).

Do you have a need to use log4net with 451?

**Comment by xied75** [comment]
@karolz-ms You almost get me. :) Well, looks like it's only 2.0.6 has such limited target surface. Check out 2.0.7 or the current 2.0.8. They probably misunderstood the netstandard capabilities in 2.0.6.

Regarding the requirement of 45x, certainly it's for __enterprise__ customers. :)

**Comment by karolz-ms** [comment]
@xied75 ah, sorry, my mistake. Given that I do not see a reason why log4net input would not support .NET 4.5.1.

If you need this quick, feel free to submit a PR. Otherwise we'll try to fix this in the next couple of weeks.

**Comment by karolz-ms** [comment]
Sorry it took so long! Log4Net input 1.0.2 should fix this.
