### ISSUE TITLE
Any plans to implement a FluentD output?

### ISSUE THREAD

**Issue by ycamargo** [Azure/diagnostics-eventflow#267]
Recently I was advisoring a team that uses containerized applications running on Openshift and, consequnetly, it's logging aggregation feature based on EFK. They were trying to follow the 12-factor recommendation and send all logs to stdout and let FluentD capture those logs on the underlying infrastructure. But they were struggling with some log messages missing when log volume increases.
So, I recommended them to use EventFlow to send logs directly to ElasticSearch. But we discussed a lot about bypassing FluentD. Seens clear to me that sending to logs to FluentD is a lot more decoupled approach.
So, my question is: do you have any plans to implement a FluentD output for EventFlow?

**Comment by karolz-ms** [comment]
We do not have any plans at this point to provide a native FluentD output.

We do have an HTTP output that sends data in JSON format to arbitrary endpoint. That should be easily consumable by FluentD.

What kind of data volume are we talking about here (eg. events per service process/VM/Elastic instance?)

**Comment by ycamargo** [comment]
Yes, we discussed about the HTTP output. 
It's an eCommerce application that is being rearchitected in microservices. This site has a very high traffic, specially on Black Fridays and other seasonal dates, so it generates a huge amount of logs.
For this kind of volume, the recommendation is to use the FluentD "in_forward" TCP input plugin like NLog does (https://github.com/fluent/NLog.Targets.Fluentd).
Now, they are thinking about use NLog or Serilog to support this, but I do prefer a more "independent" and lightweight approach.
I'm willing to create this FluentD output for them. :-)

**Comment by karolz-ms** [comment]
Sounds great! Let us know if we can help in any way.
