### ISSUE TITLE
Determine whether events are lost

### ISSUE THREAD

**Issue by pisees** [Azure/diagnostics-eventflow#270]
Hi,

Is there a way to determine whether events are being lost? I have Service Fabric -> EventFlow -> Application Insights, and seeing issue that is hard to explain unless we are losing.

Kurt

**Comment by karolz-ms** [comment]
Well, there is a couple of possibilities

1. You are producing so many events that the EventFlow pipeline is not able to keep up. That should trigger a warning via the health reporter. Check your service health in Service Fabric and see if it is in warning state, and if so, why. This applies to native SF apps though, not guest containers etc. If using guest container, the health reporter produces a CSV file instead, the warnings go there.
2. Application Insights may be throttling you. Throttling (“sampling”) is on by default https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling 

Let us know what you find!

**Comment by karolz-ms** [comment]
Closing this one for now, but please reopen if you have further questions!
