### ISSUE TITLE
ElasticSearch 6.x and above enables just one document type per index

### ISSUE THREAD

**Issue by alesspan** [Azure/diagnostics-eventflow#271]
You may experiment that indexes on ElasticSearch 6.x and above can have **just one document type** as you can see here [https://github.com/elastic/elasticsearch/issues/15613#issuecomment-239435920](url)

For this reason, EventFlow should not use anymore the eventDocumentTypeName property on json configuration for creating the mapping on _type property on ES.
However, we could use same eventDocumentTypeName property to build, instead, a custom field to be used when querying the ES index (with Kibana or whatever else) in exact same way we could with the default _type field.

cheers,
Alessandro

**Comment by karolz-ms** [comment]
@alesspan thanks for bringing this issue to our attention

Do you know what is the implication of the document type deprecation on the NEST API? In particular, should we just stop setting `BulkIndexOperation<T>.Type` property?

Regarding reusing the eventDocumentTypeName to be a source of custom field, I'd rather just deprecate the configuration property. There is already a way to add custom field(s) to documents: `EventData.Payload`, so IMO, there is no point having a special one just for the `ElasticSearchOutput`. Thoughts?

**Comment by jeremysmith1** [comment]
It would be good to remove it eventually. Elasticsearch 7 will display a warning, and version 8 could fail. Based on the current plan here: https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types 

I would like to check if removing the type prevents earlier versions of Elasticsearch from Indexing. If it prevents older versions from indexing, we could put the issue off to allow for more use cases. Version 8 is a while off.

**Comment by karolz-ms** [comment]
@jeremysmith1 roger and thanks! I guess will have to do some testing...

**Comment by jeremysmith1** [comment]
@karolz-ms Oh don't worry about the testing. I planned on trying it out over the three day weekend.

If it is safe to remove, would it be okay to submit a PR. I am not sure if @alesspan would like to implement it.

**Comment by alesspan** [comment]
Hi @karolz-ms,
I already cloned this repo and started working on it :)
However, projects should be updated to .NET 4.6.1 at least for leveraging latest NEST and Elasticsearch.Net libraries and this is very sensitive action and should be taken carefully in order not to break something.
Do we have a strategy already in place about .NET framework version update for EventFlow library?

About the Type property, I started verifying it but documentation of ES .NET library doesn't get so deeply about the fact that this property is required or not.
However, based on [https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html](url) I see the _type property is defined on HTTP POST payload so I suspect it's still needed.

Just a specific test can clarify it.

Cheers,
Alessandro

**Comment by karolz-ms** [comment]
@alesspan excellent, your help is much appreciated!

Can you explain why it is necessary to move to NEST/Elasticsearch.Net to newest (6.3.x) series in order to fix this issue?

If consuming new NEST version IS necessary, the simplest way forward is to switch the target framework for the Elastisearch output from 4.5 to 4.6.1 and increment its major package version. Programs targeting 4.5 can still use older version of the package.

We could also consider using different versions of the NEST package for different target framework and do conditional compilation of code if NEST APIs have breaking changes, but this gets more complicated and I'd rather go down this route only if we have to.

**Comment by alesspan** [comment]
@karolz-ms I was thinking on Framework update for verifying, in case, if some methods were deprecated on newer versions of ES SDK and, for instance, for making real tests with bulk insert without Type property set.

When we increase the .NET Framework version, we must get rid of all Nuget packages, after having identified all top level nuget packages, because those could have different dependencies and, sometimes those are not automatically removed by Visual Studio and can cause issues at runtime thus it's better to install from scratch top level packages on every projects.

About incrementing the NetFx of the ElasticSearch output only, you have to tell if this don't cause issues for sure on EventFlow core libraries.

cheers

**Comment by karolz-ms** [comment]
@alesspan I think I understand, thanks for explanation. I would still start with trying if it is enough to stay with .NET 4.5, that is, maintain the current NEST 6.1 series dependency, or change it to 6.2 series, which still supports NET 45. If these do not work, but 6.3 series **does** (I mean bulk insert without Type property set), then I agree it is a good reason to go ahead with NET 45 --> NET 4.6.1 transition for Elasticsearch output.

Having Elasticsearch output depend on NET 4.6.1 should be fine. We had this kind of situation (core package targeting NET 4.5, some outputs targeting NET 4.6) from day 1.

**Comment by karolz-ms** [comment]
eventDocumentTypeName has been removed in the latest output release, see [issue 329](https://github.com/Azure/diagnostics-eventflow/issues/329)
