### ISSUE TITLE
An example code on using eventflow in actor services (.net core)

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/diagnostics-eventflow#274]
Would you please include an example on how to configure an ```EventFlow``` pipeline with ```ActorEventSource``` ?

**Comment by karolz-ms** [comment]
I would just try adding `ActorEventSource` to [the list of sources for the `EventSource` input](https://github.com/Azure/diagnostics-eventflow#eventsource). Is that not working for you?

**Comment by Arash-Sabet** [comment]
Well, we wired it up using Autofac in an actor. I was looking for another solution to be able to connect ILogger to EventSource by a pipeline.

**Comment by karolz-ms** [comment]
Sorry, still don't understand what you are trying to do. ILogger and EventSource are both logging APIs so I am not sure what it means to "connect" them.

**Comment by Arash-Sabet** [comment]
The following example illustrates how to leverage a pipeline in a stateless or stateful aspnet core service: https://github.com/Azure/diagnostics-eventflow#microsoftextensionslogging 

I was looking for an explicit example of how to utilize such a pipeline in an Actor.

**Comment by karolz-ms** [comment]
Ah, got it. Good question.

I do not have a specific example for the actor service, but examples you mentioned above still apply to a large degree. That is:

1. Create the EventFlow pipeline in the actor service startup code [here is relevant doc snippet from Service Fabric documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-using)
1. If you are using `ActorEventSource` as your logging API, you are pretty much done--as long as EventFlow EventSource input is properly configured in step 1 (i.e. to capture events from your `ActorEventSource`), your actor code can just use the `ActorEventSource` and not bother with anything else.
1. If you are using ILogger as your logging API, you need to make sure that the ILogger implementation is created using `LoggerFactory` that was subject to `AddEventFlow(pipeline)` call (pipeline being the pipeline singleton created in step 1). The actual code might look slightly differently depending on how you instantiate loggers for your actors.

Does this help?

**Comment by Arash-Sabet** [comment]
I think it makes sense. My point is that it will be great if you could add a section to the markdown document to explicitly describe this context in Actors scope for first-time readers. That will help a lot.

**Comment by karolz-ms** [comment]
Good suggestion, thanks. Will do

**Comment by Arash-Sabet** [comment]
@karolz-ms Thanks. That will be great.

**Comment by karolz-ms** [comment]
Readme has been updated with better instructions
