### ISSUE TITLE
Adding a header using http Output

### ISSUE THREAD

**Issue by Zakouille** [Azure/diagnostics-eventflow#275]
Hello, 

I need to push data using HTTP.
However, when pushing the access is secured so I need to **add a header** to my HTTP request.

Here is my current eventFlowConfig : 

"outputs": [
    {
      "type": "Http",
      "serviceUri": "https://example-hello.com/event",
      "format": "Json",
      "httpContentType": "application/json",
    }
]

And I need to add a header like this : 

"X-KEY": "d5bd0f0f6cff42249t5f0117ac36d670",

Is it possible ? I couldn't find an example in the documentation.

Thanks in advance.

**Comment by karolz-ms** [comment]
Yes, sorry, this is possible. The documentation was incomplete; I have just updated it. Basically you can do the following:

```json
"outputs": [
  {
    "type": "Http",
    "serviceUri": "https://example-hello.com/event",
    "format": "Json",
    "httpContentType": "application/json",
    "headers": {
      "X-Key": "123456"
    }
  }
]
```

Let us know how whether it worked for you!

**Comment by Zakouille** [comment]
Thank you for your response !
Testing it atm. 

Also, might be a dumb question, but do I need to precise somewhere that it has to be a http POST request ? Or can I just leave "Http" as it is ?

**Comment by karolz-ms** [comment]
The HTTP output always uses POST request, that is hard-coded and cannot be changed in the current implementation.

**Comment by Zakouille** [comment]
Alright just wanted to make sure, thank you for your help !
