### ISSUE TITLE
EventSource Issue Looking for Kernel32.dll on .NET Core

### ISSUE THREAD

**Issue by michaellandi** [Azure/diagnostics-eventflow#279]
Hey All,

I'm having an in issue on .NET Core 2.1 using newer `Microsoft.Diagnostics.EventFlow.Inputs.EventSource` inputs.

Here is my eventFlowConfig.json:

```
{
    "inputs": [
    {
        "type": "EventSource",
        "sources": [
            {
                "providerName": "ExampleEventSource"
            }
        ]
    }
  ],
  "outputs": [
    {
        "type": "StdOutput"
    }
  ],
  "schemaVersion": "2016-08-11"
}
```

Running version EventSource (1.4.2) produces this issue:  

> Unhandled Exception: System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener. ---> System.DllNotFoundException: Unable to load shared library 'Kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libKernel32.dll, 1): image not found
>    at Microsoft.Diagnostics.EventFlow.Inputs.EventDataExtensions.GetSystemTimePreciseAsFileTime(Int64& filetime)
>    at Microsoft.Diagnostics.EventFlow.Inputs.EventDataExtensions.ToEventData(EventWrittenEventArgs eventSourceEvent, IHealthReporter healthReporter, String context)
>    at Microsoft.Diagnostics.EventFlow.Inputs.EventSourceInput.BroadcastEvent(EventWrittenEventArgs eventArgs)
>    at Microsoft.Diagnostics.EventFlow.Inputs.EventSourceInput.BroadcastEventIfSourceNotDisabled(EventWrittenEventArgs eventArgs)
>    at Microsoft.Diagnostics.EventFlow.Inputs.EventSourceInput.OnEventWritten(EventWrittenEventArgs eventArgs)
>    at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
>    --- End of inner exception stack trace ---

Rolling back to a previous version like (1.2.0) does not exhibit this behavior.

Thanks.

**Comment by karolz-ms** [comment]
@michaellandi  what is the OS that you are running on?

**Comment by michaellandi** [comment]
This occurred on Mac OSX.

**Comment by karolz-ms** [comment]
😬 we definitively should not try to load `kernel32.dll` on the Mac. Will try to fix this in the next couple of days. Thanks for the report!

**Comment by karolz-ms** [comment]
@michaellandi can you try EventSource input package version 1.4.3 and let us know if it fixes the issue? Thanks!

**Comment by michaellandi** [comment]
@karolz

> @michaellandi can you try EventSource input package version 1.4.3 and let us know if it fixes the issue? Thanks!

Thanks for the quick turn-around.  It's working perfectly now :)

**Comment by karolz-ms** [comment]
Super. Issue resolved!

**Comment by michaellandi** [comment]
@karolz-ms One last comment.  It seems upgrading to 1.4.3 is defaulting to creating health reports.  This behavior wasn't seen with the older versions (i'm guessing it is pulling in some newer version of event flow).

**Health Reports Created**
    ```
<PackageReference Include="Microsoft.Diagnostics.EventFlow.Inputs.EventSource" Version="1.2.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Outputs.StdOutput" Version="*" />
```

**Health Reports Not Created**
    ```
<PackageReference Include="Microsoft.Diagnostics.EventFlow.Inputs.EventSource" Version="1.4.3" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Outputs.StdOutput" Version="*" />
```

Same eventflow config as above.

**Comment by karolz-ms** [comment]
Roger--investigating. Is your program just creating an EventFlow pipeline with the configuration above and emitting events from the `ExampleEventSource`, or is there more to it?

**Comment by michaellandi** [comment]
Yes, nothing else crazy going on....

> using (var pipeline = DiagnosticPipelineFactory.CreatePipeline(Environment.CurrentDirectory + "/eventFlowConfig.json")) ....

**Comment by karolz-ms** [comment]
@michaellandi please try EventFlow Core 1.5.4 package (just published); it should not create the reporter file until there are some reports. That is, unless you set `EnsureOutputCanBeSaved` flag to true

**Comment by michaellandi** [comment]
@karolz-ms looks good! Thanks.
