### ISSUE TITLE
System.Diagnostics.DiagnosticSource input

### ISSUE THREAD

**Issue by ghelyar** [Azure/diagnostics-eventflow#283]
I was just wondering whether there was any existing [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/) input, and whether it would be worth adding one? If so, I don't mind doing it when I have time.

`DiagnosticSource` seems to be quite similar to `EventSource`, but as it's in-process, it seems like a bit of a nicer fit for EventFlow.

**Comment by karolz-ms** [comment]
@ghelyar your help would be much appreciated, as all members of the EventFlow team here at Microsoft are currently working primarily on other projects till at least mid-to-late January, myself included. 

It is true that `DiagnosticSource` is similar to `EventSource`, the main difference being that `EventSource` deals only with easily serializable types in the payload, vs. `DiagnosticSource` that can handle any data. Fortunately EventFlow is more like `DiagnosticSource` than `EventSource` in this respect, so stuffing `DiagnosticSource` event data into EventFlow `EventData` instance should be quite straightforward.

> BTW, both `EventSource` and `DiagnosticSource` are in-process, really, it is just that the default `EventListener` for `EventSource` is one that produces ETW traces on Windows, so many people think 
that producing ETW is the primary purpose of `EventSource`. It is not. `EventSource` is foremost a *logging API*, just like `DiagnosticSource`.

**Comment by karolz-ms** [comment]
@ghelyar will you also be able to send a PR that updates the README with DiagnosticSource input information?

**Comment by ghelyar** [comment]
Can you also please confirm that as the source has no level property, leaving the log level of these events as 0 is sufficient? This is described as [NotUsed](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Core/Implementations/LogLevel.cs)

**Comment by karolz-ms** [comment]
Well, there is no "error level" concept for DiagnosticSource events, so it makes sense to use `NotUsed`. It also makes sense that this is the highest level a.k.a. LogAlways in ETW, resulting in these events going through the filters.

**Comment by karolz-ms** [comment]
I think the doc PR that you sent wraps it up. Again many thanks for this contribution @ghelyar !
