### ISSUE TITLE
ApplicationInsights input does not set metadata correctly for processing by outputs

### ISSUE THREAD

**Issue by voltcode** [Azure/diagnostics-eventflow#291]
I am trying to develop a simple outputter that parses exception information.
I tested it with NLog input and calling logger.Error(exception);     works fine - exception is recognized as Exception in my output class.

however, when I use the application insights input it does not work correctly.

in the client code I call:  telemetryClient.TrackException(exception);   

in my output this condition is not fulfilled:
if (eventData.TryGetMetadata(ExceptionData.ExceptionMetadataKind, out metadataSet))
{
}

When inspecting the eventData in profiler, I can see that the private property - metadata is null when the input is from Application Insights, whereas from NLog it is not null.
In both NLog and AI cases, the payload is not null.

It seems like the data is flowing through but is generated correctly on the ai side.

I am using:
<package id="Microsoft.ApplicationInsights" version="2.8.1" targetFramework="net462" />
  <package id="Microsoft.Diagnostics.EventFlow.Core" version="1.4.1" targetFramework="net462" />
  <package id="Microsoft.Diagnostics.EventFlow.Inputs.ApplicationInsights" version="1.4.1" targetFramework="net462" />

**Comment by karolz-ms** [comment]
Well, it is just a bug (not-implemented issue) in Application Insights input. 😐  It should be setting Dependency/Request/Metric/Exception metadata on events depending on input telemetry type, but it does none of these things today.

How important is this feature for you, @voltcode ?

**Comment by voltcode** [comment]
Without being able to rely on AI input, I probably have to give up using Ai altogether, which is a shame because it means I may need to reimplement what it does by stiching other inputs together + replicating some of the Ai data generation myself.  I'd say that's pretty serious reason whether or not to use AI :) 

It may also be that because of the need for custom development, I may ditch using eventflow too, which would be a shame because otherwise it does a good job.

**Comment by karolz-ms** [comment]
Adding metadata to events produced by Application Insights input is not a complicated fix. Would it be sufficient for your purposes to have it ready by the end of this week?

Also, if you could describe a bit what your system architecture is and where the logs are going, we might give you some tips on how to get most benefits from App Insights

**Comment by voltcode** [comment]
That would be great, thanks!

Regarding architecture - requirements aren't finalized yet, but I need to be ready for some on-premise deployments without internet access for at least some of the services and be able to merge this data with existing logging infrastructure NLog, etc. as eventflow permits. 
With regard to types of information - the more of the scope that ai can provide, the better, but we may need to enrich it with custom data.  Some of the information may go to ai, however some of it has to be accessible inside network as well. Any hints appreciated :)

**Comment by karolz-ms** [comment]
ApplicationInsights input 1.4.2 was published on NuGet. Let us know know how it works for you!

Regarding the architecture: I think what you are doing makes a lot of sense. Event if the data does not go to Application Insights, you probably still want to use Application Insights SDK for .NET-based clients, as the SDK has a lot of instrumentation for Microsoft frameworks.

**Comment by voltcode** [comment]
Thanks a lot, do you know what's  the best way to switch off sending the Ai data to Azure, for such on-premises nodes without internet access? I know you can set the target hostname to localhost, but that's just seems like a wasteful hack (data is probably still sent) ? On such offline node I need the data to flow through eventflow.
