### ISSUE TITLE
logging entries missing via OMS output

### ISSUE THREAD

**Issue by lnhzd** [Azure/diagnostics-eventflow#294]
We configured our pipeline to have dual outputs: OMS output and Std output.
We are expecting entries in these two outputs match up, however they do not correlate with each other: For a given period of time (a few hours) we are seeing 9 entries of error level logging in Stdoutput, while there is only one appearing in OMS. We noticed missing entries because we were after certain errors in OMS but they were not there, potentially the same issue may happen on other logging level, e.g. info, debug, as well.
the traffic was pretty low, we were not running any load tests whatever, a few smoke tests only.

{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        {
          "providerName": "MyProviderName",
          "level": "Verbose"
        }
      ]
    }
  ],
  "outputs": [
    {
      "type": "StdOutput"
    },
    {
      "type": "OmsOutput",
      "workspaceId": "servicefabric:/ef/workspaceId",
      "workspaceKey": "servicefabric:/ef/workspaceKey",
      "logTypeName": "myTableName"
    }
  ],
  "schemaVersion": "2016-08-11"
}

**Comment by lnhzd** [comment]
no it's only an intermittent error (may be more frequent than intermittent but definitely not happening on every single entry), this effectively means the warning of health report will be flushed by the next successful call to OMS presumably? we  didn't set up any alert, nor did anyone sitting there staring at sf explorer for a 24 hours so cannot really tell, unless there's a way to check historical data of health report?

it has been happening for a while, for at least two of our services so may not relate to the shortage you mentioned.thanks.

**Comment by lnhzd** [comment]
Thanks Karolz, following your suggestion I passed in a custom health reporter that outputs to std output, and found that for a given period (20 min), out of the 100 ish requests go out to oms, 6 failed because "OmsOutput: OMS REST API returned an error. Code: Forbidden Description: Forbidden {"Error":"InvalidAuthorization","Message":"An invalid signature was specified in the Authorization header"}."

These failing requests are almost data-specific that contains a payload of json string with an already serialized object that contains exception stack trace, ex.ToString. 
Looked at the signatureInput, message.Length does look suspicious I wonder if it's something to do with how you validate message length when a message is received on your side?

I've got a raw request (goes to OMS) that can be used to demo the problem, but I'm not comfortable to paste the payload here, is there an email I can send the payload across for you to investigate the problem please? thanks.

**Comment by lnhzd** [comment]
I started wondering if this issue should be closed here but to be opened against log analysis, as I cannot see anything wrong on the client side according to https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api#authorization

**Comment by lnhzd** [comment]
all right, think I've now figured out what the problem is, the issue is still in OMSOutput package:
https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Outputs.Oms/OmsOutput.cs#L160
when building the signature, it needs to be:
Encoding.UTF8.GetBytes(message).Length
as opposed to 
message.Length

**Comment by karolz-ms** [comment]
@davidfowl FYI I think you have been working on similar code; just bringing it to your attention to make sure similar mistake is not repeated elsewhere ☺️

**Comment by davidfowl** [comment]
Ah good to know!
