### ISSUE TITLE
Diagnostic HealthReport creation taking more time

### ISSUE THREAD

**Issue by vbkattamudi** [Azure/diagnostics-eventflow#298]
Hi @karolz-ms ,
At the time of instantiation health report creating is taking 9 seconds, Even though we are not providing Health report settings in eventflow config file.

Please provide your inputs.
Attached the Dot trace profiler details
Thanks,
Badri and @saitejkuralla
![diagnostic_healthreport](https://user-images.githubusercontent.com/31533345/50397878-4cb79080-0799-11e9-8e4f-43476608a15c.png)

**Comment by vbkattamudi** [comment]
Hi @karolz-ms, 

Can you please help us on the issue as it is a blocker for us, do we have any settings to not instantiate the health report.

Thanks,
Veerabhadra Kattamudi

**Comment by karolz-ms** [comment]
@vbkattamudi @saitejkuralla I am not sure I see anything out of ordinary here. The thread in the trace is not initializing the health reporter, nor is it creating a health report. It is a health report writer thread, waiting for health reports to be written to a file. By default only warnings and errors are recorded by the CsvHealthReporter, so if everything is working well and there are no warnings or errors, the thread will just keep waiting doing nothing, potentially for a very long time.

This implementation could be improved by using asynchronous I/O or some other mechanism that does not involve a dedicated writer thread, but for most services it should not matter much.

Does this answer your question?

**Comment by saitejkuralla** [comment]
@karolz-ms what you said was correct but to be more precise this behavior is seen only for the first time.

**Comment by karolz-ms** [comment]
@saitejkuralla sorry, I am not exactly sure what you mean when you say "the behavior is seen only for the first time"

It would be very helpful if you could share a project that demonstrates the problem, and clarify what you  **would expect** to happen versus what is **actually happening**, in terms of timing or whatever else is the concern.

**Comment by karolz-ms** [comment]
Closing for now but please reopen if you need more help on this issue
