### ISSUE TITLE
Why does Log4net input require changes to logging code? 

### ISSUE THREAD

**Issue by ArturDorochowicz** [Azure/diagnostics-eventflow#299]
As far as I see (all?) input libraries are written in such a way that they can read from their respective inputs without requiring any changes to the existing log writing code. Only log4net input is different. Here we are required to request a logger from a specific logger repository called `EventFlowRepo`. Existing log4net logging code won't work, because it typically creates loggers from the default repository.

Why is log4net input implemented in this way? Can it be changed? Can it be used differently so that it behaves like other inputs (i.e. no changes to existing logging code are required).

**Comment by karolz-ms** [comment]
It should be fairly easy to fix this. One possibility is to make the logging repository name a configuration parameter and use the value of the parameter as [part of initialization](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.Log4net/Log4netInput.cs#L66) Default value could be empty, which would be a hint to use the default repository.

@jeremysmith1 was there a particular reason why you used a named repository as the default for log4net input?

**Comment by jeremysmith1** [comment]
It is a little fuzzy, but I remember having issues if I did not create a named repository. I don't think this is necessary, but I am unsure. It was just inexperience on my part I believe.

I will take a deeper look into it over the weekend, if you do not beat me to it.

**Comment by karolz-ms** [comment]
Thanks Jeremy! 

@ArturDorochowicz if you want to take a stab at this fix, that would be very appreciated, we do take PRs

**Comment by karolz-ms** [comment]
@ArturDorochowicz sorry looks like Jeremy and I could not get to making this change sooner. Let me know if this is still something you would like to be improved.

**Comment by ArturDorochowicz** [comment]
Well, I think this is an area that could be improved, but I myself don't have plans anymore to use Event Flow library.

**Comment by karolz-ms** [comment]
OK, thanks for quick update. I am going to close this for now; will reconsider if other users complain.
