### ISSUE TITLE
Make OmsOutput extensible

### ISSUE THREAD

**Issue by AssafTzurEl** [Azure/diagnostics-eventflow#300]
The project I'm currently working on was using OmsOutput to send logs and metrics to Azure Log Analytics, but the results were unsatisfactory:
1. All the properties of EventData were logged (even if we didn't need them)
2. Custom properties were named Payload_<PropertyName>, since they were all contained in the Payload dictionary
3. Everything was sent to a single table, since you can only set a single log type in the configuration file.

We ended up writing our own CustomOmsOutput, which converts the EventData to JSON, manipulates the fields, and can send each object to a different table. The problem is, now we need to scan the changes to the original OmsOutput.cs and update our code whenever there's a bug fix (or a new feature).

My request: Please make OmsOutput extensible:
1. Allow manipulation of the output before sending it (e.g. using a strategy pattern)
2. Let the user direct each object to a different table (e.g based on a specific field or a criteria delegate that can be run on an object)

TIA,
Assaf.

**Comment by AssafTzurEl** [comment]
@karolz-ms I can think of several ways to do this. Let's switch to email for the discussions and get back here for a PR once we have a clear direction.

**Comment by karolz-ms** [comment]
So @AssafTzurEl , how is it going with a PR for this? I think you were very close to having it completed?

**Comment by AssafTzurEl** [comment]
Yes, you're right, @karolz-ms - but I have to many fires to put out right now... got a promise from management to have some time for that PR, hopefully next week.

**Comment by karolz-ms** [comment]
@AssafTzurEl thanks, it is no rush, whenever you have time. I just do not want the results of your thought and work to get lost, that is all.

**Comment by AssafTzurEl** [comment]
@karolz-ms PR submitted. I can send you our usage (derived class with overridden method) if you want, as an example.

Plus: Got another (minor) enhancement - let's discuss it after we're done with the big one.

**Comment by karolz-ms** [comment]
@AssafTzurEl sorry for late reply, I was a bit under the weather last week. Looking now.

**Comment by karolz-ms** [comment]
The package with the change (version 1.5.0) was published on NuGet. Please give it a try and let us know if there are any issues.

Thanks a bunch for making EventFlow better!
