### ISSUE TITLE
Collect ETW Container Logs with ETW input

### ISSUE THREAD

**Issue by groccodm** [Azure/diagnostics-eventflow#304]
Hello,

  I'm already using EventFlow to capture events from ServiceFabric services without problems. We are now deploying some services hosted inside docker containers running inside Service Fabric, and we would like to collect the logs generated by the logging driver specified here: https://docs.docker.com/v17.09/engine/admin/logging/etwlogs/

  I guessed that the ETW input would be able to capture the logs generated only configuring the provider ID specified on the link above, but even if I can see the container logs on the SF management page, eventflow doesn't seem to be able to capture them.
 
  I made a little test app that uses the Tracing libraries directly, and with this code

            using (TraceEventSession userSession = new TraceEventSession(sessionName, TraceEventSessionOptions.Create))
            {

                Task.Run(() =>
                {
                    userSession.EnableProvider(
                        "a3693192-9ed6-46d2-a981-f8226c8363bd",
                        TraceEventLevel.Verbose
                    );

                    userSession.Source.AllEvents += delegate (TraceEvent data)
                    {

                        Console.WriteLine($"<{data.ProviderName}:{data.ID}>__[{data.OpcodeName}] {data.EventName} <| {data.FormattedMessage}");
                    };

                    // this is a blocking call until the session is disposed
                    userSession.Source.Process();
                    Console.WriteLine("End of session");
                });

                // wait for the user to dismiss the session
                Console.WriteLine("Presse ENTER to exit...");
                Console.ReadLine();
            }

it captures the logs from the containers. 
Looking inside the code of the ETW input, you attach to the Source.Dynamic.All event, that i guess it's only useful for providers that have a manifest published. This is not the case for the container logs.

I would like to know if maybe i'm doing something wrong with the configuration of the ETW input in my eventflow app, or if maybe you are planning on supporting this scenario if it's not supported right now.

I also can make a version of the ETW input that captures this particular kind of logs, but i can't seem to find documentation on how to make an extension/custom input for eventflow, if you can point me to an example i will try that as a solution.

My last option would be to not use EventFlow and make a custom event collector, but we are already using eventflow for all our logging needs and don't want to support a hybrid scenario or have to develop a new Event collector from scratch. 

Thanks for your support.

**Comment by karolz-ms** [comment]
@groccodm It would be very helpful if you elaborated a bit on your current diagnostic setup and expectations. For example:

- Are you attempting to use ETW input just for the sake of capturing logs from containers? Or are you using ETW already in your non-Docker deployments? 
- What EventFlow inputs are you using today? Will they change when you move to Docker? 
- Where do these logs/events go (Application Insights? Elasticsearch? something else?) 
- Do you capture just application events, or also Service Fabric events? 
- Is it going to be Windows-only app for foreseeable future, or do you expect to have some Linux-based/.NET Core-based services?

For various reasons ETW is often problematic in a container-based environments

Creating custom EventFlow input is very easy. Start with [Extensibility paragraph](https://github.com/Azure/diagnostics-eventflow#extensibility) to learn how EventFlow works under the covers. The mechanics of hooking up custom pipeline elements [is described here](https://github.com/Azure/diagnostics-eventflow#creating-a-pipeline-with-custom-elements-using-configuration). This is only needed if you are using a configuration file; if you are creating EventFlow pipeline via code, just create an instance of your input and add it to the `DiagnosticPipeline` constructor via `inputs` parameter.

**Comment by groccodm** [comment]
@karolz-ms thanks for the fast reply.

- We are alreading using EventFlow to capture all the logs from our existing applications that run as native Service Fabric services.
- We use the ETW input to capture the application events, but we are not planning to run the eventflow process from inside the container, only to set it to capture the logs that the container generates.
- The output it's a sql database, since this is a "on-prem" scenario. We capture mainly application events, no service fabric events.
- The new applications that will be run inside containers are .NET Core based, but we don't plan to deploy them on Linux enviroments, always inside windows container/clusters.

I hope this is helpful, in summary we are running applications inside docker containers with windows images, and deploying the containers in a Service Fabric Cluster. The eventflow event collector is running inside Service Fabric as a Native Application, not inside a container, and right now it captures all the events of the native service fabric services we are already running. 

Thanks for the links for the custom inputs!

**Comment by karolz-ms** [comment]
OK, thanks for the update.

I can see what is going on--the way Docker log driver is using ETW is simplistic (basically, exclusively relying on [EventWriteString API](https://docs.microsoft.com/en-us/windows/desktop/api/evntprov/nf-evntprov-eventwritestring) [ETW event log driver sources here](https://github.com/moby/moby/blob/master/daemon/logger/etwlogs/etwlogs_windows.go). As a result, none of the "standard" TraceEvent event parsers can deal with it, but the `AllEvents` hook does.

I would be fine with adding an option to ETW input to use `AllEvents` **instead of** `Source.Dynamic.All`.  By default it should be off, as `AllEvents` does not have the smarts that other parsers do, so for manifest-based ETW providers or from `EventSources` it is a poor choice. Would you be willing to submit a PR for this change?

Longer term I would consider some alternatives to ETW Docker log driver approach. The main thing that I do not like about it is that you are losing event structure (everything is smashed into a string). Yes, you can do pattern matching in your database, but that is harder and more error prone than just having explicit properties that are stored in your database with perfect fidelity. Also, application standard output tends to be polluted by noise from your dependencies, noise that often cannot be controlled. So in my experience, having a dedicated channel for structured logs is a desirable thing.

**Comment by groccodm** [comment]
Thanks for the offer to make a configuration to capture the AllEvents, but if i may i would like to suggest an approach that maybe is more flexible. 
I see in the code that the real processing of the ETW events is done inside the StandardTraceEventSession class, that implements the ITraceEventSession interface and it's created from a method inside the EtwInput class. I guess the idea was to support different tipes of EventParsers, and that would be great for me, because as you said the event it's a string and logging that inside the DB will be difficult to query.
But if i could plug inside the ETWInput a new ITraceEventSession object i could change the Process method to capture AllEvents and parse the Message that the docker container generates to create the correct payload to save inside the DB. 
I know this is  more complicated, but maybe in the long run it will provide more alternatives to developers. Right now what i'm doing is creating a new input using the guide you showed me and making a copy of the EtwInput classes to include the processing of the message. If it's easier to make the configuration i could use it to test the capture, but i will make the new EtwInput class to insert the parsing logic.
Thanks for your help and support.

**Comment by karolz-ms** [comment]
If you want to replace the `StandardTraceEventSession`, you can do this with the current implementation. All you need to do is [provide your own session factory](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.Etw/EtwInput.cs#L68). This needs to be set on EtwInput instance before [it is activated](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.Etw/EtwInput.cs#L70).

Let us know if this approach works for you.

**Comment by groccodm** [comment]
Hi, i'm testing the approach you suggested and it's working fine. Since it's exactly what i need, you can close this issue.
Thanks for you support.

**Comment by karolz-ms** [comment]
Excellent. Thanks for letting us know!
