### ISSUE TITLE
ApplicationInsightsOutput: diagnostics data upload has failed

### ISSUE THREAD

**Issue by JamieTemple** [Azure/diagnostics-eventflow#305]
Hello,

So everything on my cluster was working fine ... until I decided to deploy 2 "versions" of my service side-by-side.

In effect, I now have 2 applications - SIT & UAT running on the same cluster.

My services are running, fine - however there is a warning displayed in SFX:

```'

fabric:/MyApp-SIT-DiagnosticsPipeline' reported Warning for property 'Connectivity'.
ApplicationInsightsOutput: diagnostics data upload has failed.

System.NullReferenceException: Object reference not set to an instance of an object.

at Microsoft.ApplicationInsights.Extensibility.Implementation.TransmissionProcessor.
Process(ITelemetryitem)

at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)    

at Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.SendEventsAsync
(IReadOnlyCollection`1 events, Int64 transmissionSequenceNumber, CancellationToken
cancellationToken)

```

(The other application sets up the services diagnostics pipeline as "fabric:/MyApp-UAT-DiagnosticsPipeline")

Any ideas??

Thanks - Jamie.

**Comment by karolz-ms** [comment]
@JamieTemple what you describe is quite unexpected.

First, the way EventFlow and ApplicationInsights SDK work, being in-process components, two versions of the same service, even running side-by-side on the same cluster node(s) should not interfere with each other.

And the Application Insights `TransmissionProcessor` [is really minimal](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/Extensibility/Implementation/TransmissionProcessor.cs#L33), there is hardly anything that can go wrong there resulting in `NullReferenceException`. Could you please double-check what you quote above is the complete call stack for the exception?

Can you show us what is the configuration for EventFlow and what version of Application Insights SDK are you using?

**Comment by JamieTemple** [comment]
> @JamieTemple what you describe is quite unexpected.
> 

I can only show you what I have of the stack trace, as nothing else is appearing in AI!

![image](https://user-images.githubusercontent.com/3730517/52977614-cc429400-33c5-11e9-97af-45d7b841372a.png)

It's worth noting that I do get "RunAsync has been invoked" and "RunAsync has completed" messages appearing in AI.

> Can you show us what is the configuration for EventFlow and what version of Application Insights SDK are you using?

I'm using Microsoft.ApplicationInsights.ServiceFabric.Native version 2.2.1 (which is using Microsoft.ApplicationInsights 2.4.0)

config is pretty vanilla:

```
{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        { "providerName": "Microsoft-ServiceFabric-Services" },
        { "providerName": "DT.Imago.Direct.AutomationUXService" }
      ]
    }
  ],
  "filters": [
    {
      "type": "drop",
      "include": "Level == Verbose"
    }
  ],
  "outputs": [
    {
      "type": "ApplicationInsights",
      "instrumentationKey": "servicefabric:/ApplicationInsights/InstrumentationKey"
    }
  ],
  "schemaVersion": "2016-08-11"
}
```

... my cluster is currently upgrading apps - once it's done, I'll remove the "side-by-side" apps so there is just a single version once again ... which I really should have done before posting ;)

Jamie.

**Comment by karolz-ms** [comment]
OK one thing to try is to use latest Microsoft.ApplicationInsights (2.9.1 at this time). Just add an explicit reference to this package from your application project. Let us know if the problem persists after that.

Which version of EventFlow ApplicationInsights output are you using?

**Comment by JamieTemple** [comment]
> OK one thing to try is to use latest Microsoft.ApplicationInsights (2.9.1 at this time). Just add an explicit reference to this package from your application project. Let us know if the problem persists after that.
> 
> Which version of EventFlow ApplicationInsights output are you using?

![image](https://user-images.githubusercontent.com/3730517/52978077-a28a6c80-33c7-11e9-93f0-cfc0523414dc.png)

will try an explicit reference later tonight - I have a funny feeling there was a reason I stuck with 2.4.0 ... can't remember right now.

Thanks - Jamie.

**Comment by JamieTemple** [comment]
Ok ... so my bad ... Updating to 2.9.1 looks to have resolved this.

**Comment by karolz-ms** [comment]
@JamieTemple thanks for the update. I am glad it is working now.

The AppInsights SDK has been receiving bug fixes over several releases, including in the area that the exception call stack pointed to. However, to be honest, the suggestion to use the latest version was a bit of a shot in the dark, so please re-open this issue if the problem re-occurs, hopefully not.
