### ISSUE TITLE
Expiration of Service Fabric Health Reports

### ISSUE THREAD

**Issue by berndku** [Azure/diagnostics-eventflow#308]
In case of throttling the ServiceFabricHealthReporter writes the following warning to the Service Fabric Health system: 

```text
 'Service1' reported Warning for property 'Connectivity'. An event was dropped from the diagnostic pipeline because there was not enough capacity
```
 
Given that the TTL of this health report is infinite, how is this message supposed to disappear when the throttling is over?
Or to rephrase, on what condition is the property 'Connectivity' set again to a healthy state ?

**Comment by karolz-ms** [comment]
The warning state should be cleared when a batch of events is successfully sent to its destination by any of the EventFlow outputs. Is this not what you are observing? Are you using a custom output by any chance?

**Comment by berndku** [comment]
Yes, this is what we observing. The next successful event was just a few hours away, leaving the application in an unhealthy state for a long time. We probably would prefer a TTL on the message or tweak the behaviour of the ServiceFabric HealthRepoter in general. Is there any way to provide a custom ServiceFabricHealthReporter ?

**Comment by karolz-ms** [comment]
Thanks for clarification!

There is no good way to replace the ServiceFabricHealthReporter, it is hard-coded into [ServiceFabricDiagnosticPipelineFactory](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.ServiceFabric/ServiceFabricDiagnosticPipelineFactory.cs#L27). You could clone & modify this code, of course, but that is not a very appealing option.

I am thinking adding TTL on the EventFlow health reports makes most sense. How does 10 minutes sound like?

**Comment by karolz-ms** [comment]
Note to self: also set `RemoveWhenExpired` to true, otherwise expired reports will be treated as errors :grin:

**Comment by berndku** [comment]
A TTL of 10 minutes would work for us.

**Comment by karolz-ms** [comment]
Reopen till new Nuget packages are published

**Comment by karolz-ms** [comment]
Service Fabric package 1.5.1 should have this change
