### ISSUE TITLE
Pass ElasticSearch a json object in a column

### ISSUE THREAD

**Issue by gperrego** [Azure/diagnostics-eventflow#310]
@karolz-ms , 

I'm not sure how to pass a json object correctly to ELK.  The intent is that we are able to pass JSON via the WriteEvent from out application.  Then when Elastic receives that event it would flatten the json.  

For example I'm hoping to see something like:

payload.mystring1
payload.mystring2
payload.myobject.name
payload.myobject.lastname
payload.myobject.address

Does the write event support this?  Is there any doco on how we can do this?

https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html

Thanks, 
Greg

**Comment by karolz-ms** [comment]
Greg are you using EventSource input and `EventSource.WriteEvent` method? Can you include a snippet of the code showing how you raise events?

**Comment by gperrego** [comment]
@karolz-ms yes, we are using EventSource input and EventSource.WriteEvent.  We have modeled our event writing based on the default service fabric event writing.  We are doing some basic stuff, here is an example without an object: 

        private const int FirstLoadVerboseEventId = 9;
        [Event(FirstLoadVerboseEventId, Level = EventLevel.Verbose, Message = "{0}")]
        private void FirstLoadVerbose(
            string message,
            string userName,
            string cacheKey
            )
        {
            WriteEvent(
                FirstLoadVerboseEventId,
                message,
                userName,
                cacheKey
                );
        }

Our real goal here is to have multiple applications send events to one shared index in elastic.  This because if each application has its own index each day there are too many shards created and our ELK instance slows down.  So we are trying to use a standardized format for all applications to logs events.  For the example below lets say we plan on having 4 standard columns + 1 Json object:

ApplicaitonName, Username, Server, EventName would be standard across all apps, then in the last "column" we can pass a json object with as many application standard properties that the application wants to pass.  Some apps will pass a json object with  property x, y and z and another application will pass a, b and c.  

Based on this article we understand that when elastic gets this object each property will flattened into its own column.  One advantage of this approach is it will help us in standardizing the methods in the application to take one standard signature.  we will always expect these 5 columns in the [Non event] method.  Then we stringify the Json column and pass it to EventSource.WriteEvent.

Does that make sense?

Thanks, 
Greg

**Comment by karolz-ms** [comment]
Greg, makes sense. Thank you for taking time to provide more context. I can think of two ways of achieving what you describe

1. You can have just one "CustomData" column that is of string type. Your application(s) will serialize whatever data you need into JSON text and populate CustomData column with it. From Elasticsearch perspective it will be just a string--it won't really understand that this is a JSON. However, since the schema of the data is fixed between different applications, indexing this data is straightforward.

OR

2. You can try to store actual "objects" in ES. If you are using EventSource, as your logging API, you would use rich payload feature https://blogs.msdn.microsoft.com/vancem/2015/09/20/rich-payload-data-in-eventsource-v4-6/ to pass application-specific data into EventFlow. I will admit I never tried the EventSource rich payload+Elasticsearch output combination, but it should work, and if there are bugs, we will try to fix them. Using this method you will get what the ES documentation describes, that is, ES will understand it is dealing with "objects" and will flatten the object hierarchy according to docs you quoted above. The little worry I have about this approach is that if you are storing records with many different kinds of "custom data" within the same index, ES will effectively need to index it as a union of all different "custom data" types. So it is about having a lot of (optional) properties within this index. I am not ES expert, so maybe that is not a concern, and it certainly depends on how many different "custom data" types you will actually store per index.

I hope this is clear. Please let me know how the rich payload approach is working for you if you decide to pursue it.

**Comment by gperrego** [comment]
Yeah, I'm going to work on option 2, I'm setting up and example app now.  I think we can do it, i'll keep you updated.

to your concern i'm not concerned, ELK is identifying custom datatypes for each column now and flattening them.  It looks like the payload itself is being treated as an object.  The only difference here would be another level down in the json.  So that does bring up a question, is NEST sending over a json object?  I don't even know if that is a dumb question, I don't' know anything a out NEST.

Thanks,
Greg

**Comment by gperrego** [comment]
@karolz-ms I've tried and i'm not seeing where it is failing.  So I downloaded the eventflow source code and i'm tyring to compile the warsaw sln locally.  This fails due to a missing file in the Core project.  FilterParser.peg.cs.  If I remove it from the project that doesn't fix it (didn't think it would).  So is the GitHub project missing files?

**Comment by karolz-ms** [comment]
Greg, FileParser.peg.cs is code-generated from a grammar file. You need to run tools\restore.cmd to have it generated. See [Contribution Guide](https://github.com/Azure/diagnostics-eventflow/blob/master/contributing.md)

**Comment by gperrego** [comment]
I'm not sure where to run those commands?  You could probably reproduce this really quickly as long as you have an elk instance to send to.  I started out using my own custom objects but then I reverted back to a simple call, exactly emulating what Vance used as sample code in his word doc:
  https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/64/26/84/EventSourceRichPayloads.docx

Starting with an empty ServiceFabric project I added eventflow support and wired up the pipeline.  I ran this and I saw the initialization events from program.cs in Elastic.  Then I added an event to an empty ServiceFabric ServiceEventSource file:

        private const int myEventID = 7;
        [Event(myEventID, Level = EventLevel.Informational)]
        public void LogSimpleData(string message, SimpleData data) { WriteEvent(myEventID, message, data); }

Then I called it from Program.cs

ServiceEventSource.Current.LogSimpleData("testMessage", new SimpleData() { Name = "aName", Address = 234 });

I see it fire but it doesn't come into ELK.  I would have to add all of Warsaw to the solution I think to debug, i'm wondering if its getting lost in NEST?

Do you have some time to look at this?  I'm watching my kids this week and going camping on Wednesday so I will only be able to check in here and there.  Let me know if you want me to try to debug this or if you can take a look.

Thanks,
Greg

**Comment by karolz-ms** [comment]
Greg, unfortunately I think I will only be able to look at this more closely around Wednesday or later. Sorry!

You can get the FilterParser file generated by opening a Developer Command Prompt for Visual Studio. Then go to <EventFlow local repository root> and run tools\restore.cmd from there. That should get you  to the state where you can build all of the Warsaw solution.

**Comment by gperrego** [comment]
Karol,

I'll take a look, I did look there but didn't see it.  I'm wondering if it's a limitation of vs community edition.  Thanks again, I'll keep you posted.

Thanks,
Greg

________________________________

**Comment by karolz-ms** [comment]
Tools folder is just under EventFlow repository root. It is not part of Warsaw solution.

**Comment by gperrego** [comment]
ok, I looked and failed.  I think your knowledge will be key here.  Thank you for the direction on the location of the restore.cmd; I got past that.  I traced it and failed soon after the implementation of EventSourceInput : EventListener.  It has already blown up when it gets to OnEventWritten, i'm seeing "Unsupported type SimpleData in event source".  I've tried this with and without the EventDate annotation above SimpleData.  

I've attached a screenshot of my watch.

So as I've learned more about I would like to refocus on the pain point.  I don't think the gain is really on the elastic search side.  On that side if we have a json object with levels below it that is flattens into columns that's fine or if we just have columns and no object that's fine also.  

The real problem I'm trying to solve is from the perspective of the applications that are logging.  Currently it is rather static on how each individual app logs data.  If I want 50 apps to log I want to reuse some sort of nuget package so they can all pass data and not have to redefine individual methods in each app or in other words I don't want to have to define something like an application specific ServiceEventSource per app.

I understand its great to be able to defined custom application events but there is great value in a shared interface across apps.  Let me know if you have ideas :)

![Unsupported type SimpleData](https://user-images.githubusercontent.com/23040103/54580956-723ee980-49d8-11e9-890b-6d752d10e9e5.PNG)

**Comment by karolz-ms** [comment]
I wonder if `Microsoft.Extensions.Logging`/`ILogger` would not be a better fit for you as a logging API. It is natively supported by EventFlow

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2 

The docs are part of ASP.NET Core, but Extensions.Logging is not dependent on the web stack and can be used from within all sorts of apps, including ServiceFabrice stateful/stateles services, actors etc. It allows you to do things like this:

```csharp
logger.LogInformation("Hello from {friend} for {family}!", "LoggerInput", "EventFlow");
```

The example above does not require any sort of strongly-typed event source class. The resulting event has standard properties such as timestamp, but also two custom properties: "friend" and "family". Let me know what you think about this.

And thanks for the BBQ/beer offer, much appreciated! 😛 :relaxed:

**Comment by gperrego** [comment]
Very interesting.  I think that is our answer.  So I change source to Microsoft.Extensions.Logging.  I will need to use this in existing .net 4.7 apps but as you said it supports it... I'm going to have to get a sample up and running and show the team, if this works I think we have a winner.  I'm not sure if you want to continue to look into the Rich Payload Data or not.  Let me know, I'd be happy to test for you if you would like.

**Comment by karolz-ms** [comment]
No, please investigate Microsoft.Extensions.Logging first. If that works for you, no need to deal with rich payload data/EventSource

**Comment by karolz-ms** [comment]
I assume this can be closed for now, but please re-open if you have further questions!

**Comment by gperrego** [comment]
Yes I just got back from vacation and we'll look into logging extensions this week.  Thank you for all of your help.
