### ISSUE TITLE
Elastic - One App writing to multiple indexes or maybe Logstash?

### ISSUE THREAD

**Issue by gperrego** [Azure/diagnostics-eventflow#312]
I'll throw another one out there, might be a quick answer.  Can one application use Eventflow and somehow write to multiple Elastic indexes?  Maybe it could use type or keyword to determine which index to write to?  

Here is the business need:

We've got a requirement to keep telemetric data longer then application log data.  Currently ELK seems to only backup and del (snapshots) per index.  So I can not easily separate these the different data within one index.  As far as I can tell I don't see a way for Eventflow to send to two locations, I could use two providers but not two indexes?  I have to keep the app data with telemetric data in the same index which means I'm keeping a lot of app data longer than I need to.

It looks like Logstash could handle this, any plans to allow a logstash endpoint to Eventflow?  I see issue #161 so maybe that's the best way?  My concern there is that Logstash is a CPU hog which can be expensive in Azure.  When writing the event I already know which type of data it is, it would be great to classify it there vs going through that decision making process again later on via logstash.

Which would you recommend?  If using the http output is what you would recommend is there a good example for logstash that you are aware of?  

http://www.elastic.co/blog/using-logstash-to-split-data-and-send-it-to-multiple-outputs

Thanks again, 
Greg

**Comment by karolz-ms** [comment]
If you have just two indexes to handle, you can use two Elasticsearch outputs in your EventFlow configuration. And you can use per-output filters to determine which data is going to which index (or both).

What is currently not part of the design is routing telemetry to arbitrary indexes based on some properties, but it does not sound like you need that.

**Comment by karolz-ms** [comment]
I assume this is resolved, but please re-open if you have any questions!
