### ISSUE TITLE
Microsoft Logging: Add AddEventFlow extension for ILoggerBuilder

### ISSUE THREAD

**Issue by lnhzd** [Azure/diagnostics-eventflow#330]
the built-in loggers (Console, Debug, etc) have already been updated from ILoggerFactory to ILoggerBuilder, can we do/add the same for eventflow please?

i.e.: 
    public static ILoggingBuilder AddEventFlow(
            this ILoggingBuilder loggingBuilder,
            DiagnosticPipeline pipeline)
        {
            var loggerInput = pipeline?.Inputs?.Where(i => i is LoggerInput).FirstOrDefault();
            if (loggerInput != null)
            {
                loggingBuilder.AddProvider(new EventFlowLoggerProvider((LoggerInput)loggerInput, pipeline.HealthReporter));
            }

            return loggingBuilder;
        }

Thanks.

**Comment by lnhzd** [comment]
this way we don't need to pass DiagnosticPipeline into Startup, logger can be configured in  WebHostBuilder by calling:
                .ConfigureLogging(builder => builder.AddEventFlow(this.pipeline))

**Comment by karolz-ms** [comment]
@lnhzd Microsoft.Extensions.Logging input version 1.4.1 has been published on NuGet.org. Please give it a try and let us know how it works for you!

**Comment by lnhzd** [comment]
Thanks, installed the new version worked as expected!
