### ISSUE TITLE
ILogger implementation restricts the TState to IReadOnlyList for custom properties

### ISSUE THREAD

**Issue by eugenpodaru** [Azure/diagnostics-eventflow#341]
We are using EventFlow and it's working great. Out main usage is with Microsoft.Logging as input and Application Insights as Output.

Recently we wanted to add some custom properties to traces in application insights. By default, you would use one of the ILogger extensions and have named arguments in the templated message, but if you have a lot of properties you just pollute the trace message.

One solution would be to use the ILogger interface Log method and provide a TState as a IReadOnlyList of KeyValuePair. While this works, I think that this restriction is unnecessary since for example a Dictionary does not implement the IReadOnlyList.

Ultimately the code in the EventFlowLogger that does this check only needs the IReadOnlyList to iterate over the collection, and the same could be achieved with an IEnumerable of KeyValuePair. There might be a performance hit when iterating over an IEnumerable versus iterating over an IReadOnlyList, but taking into account the typical size of a TState the difference should not be noticeable.

**Comment by karolz-ms** [comment]
Thank you for the suggestion! I like the idea. Let me do some testing, stay tuned!

**Comment by karolz-ms** [comment]
@eugenpodaru let me know if [this commit](https://github.com/karolz-ms/diagnostics-eventflow/commit/a94db9675a403906f647962c3f9ca7d80d6d8d43) is what you had in mind

**Comment by karolz-ms** [comment]
MicrosoftLogging input that contains this change was published on nuget.org (ver. 1.4.4)
