### ISSUE TITLE
Missing Logs or Memory Leak in AspNetCore 3.1

### ISSUE THREAD

**Issue by timothy-carter** [Azure/diagnostics-eventflow#354]
Using eventflow with the Microsoft ILogger extensions library in aspnetcore 3.1 causes a memory leak when using a Newtonsoft.Json version of 11.0.1 or higher. If Newtonsoft.Json version 10.0.3 is used (as is referenced in the StdOutput library) logs are lost and a PlatformNotSupportedException is thrown.

This has only been observed when using a default log level of Information, but there could be other places where this will happen. When using the Information log level, the [log from aspnetcore](https://github.com/dotnet/aspnetcore/blob/47cc418dec845031f26cc93170ab26c9ad890a07/src/Mvc/Mvc.Core/src/MvcCoreLoggerExtensions.cs#L746-L752) passes a MethodInfo object as one of the values in the state object.

From here, the [EventFlowLogger ](https://github.com/Azure/diagnostics-eventflow/blob/855a93ed9e393a5ee43b7c26465858100c1ba6a5/src/Microsoft.Diagnostics.EventFlow.Inputs.MicrosoftLogging/Logger/EventFlowLogger.cs#L43) is adding that object to the payload.

If using an output such as StdOutput or EventHubOutput, this object gets serialised using JsonConvert.SerializeObject, which attempts to serialise the whole assembly, and memory use goes through the roof.

For a working example of the bug see https://github.com/timothy-carter/aspnetcore/tree/master/EventFlow/MemoryLeak

A related example at https://github.com/timothy-carter/aspnetcore/tree/master/EventFlow/PlatformNotSupportedException uses Newtonsoft.Json version 10.0.3, but this results in logs being lost and a number of PlatformNotSupportedExceptions being thrown.

**Comment by karolz-ms** [comment]
@timothy-carter thank you for reporting this issue and for providing repro examples. It helps a lot and is much appreciated! 

We will try to fix this ASAP, but I need some time to investigate the options. My current idea is to leverage Newtonsoft `JsonSerializerSettings` to special-case types deriving from [MemberInfo](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo?view=netcore-3.1) and just output the fully-qualified name of the member. I would also like to give EventFlow users the ability to customize the `JsonSerializerSettings` so they can change this default behavior if desired.

In the meantime, as a workaround, you can use an EventFlow filter to do the same, i.e. remove the event property of type `MethodInfo` and replace it with a corresponding fully-qualified member name, or drop the property altogether if it is not important for your diagnostic needs.

Thanks again!

**Comment by karolz-ms** [comment]
Keeping open till new binaries are published on Nuget

**Comment by karolz-ms** [comment]
All the relevant, updated packages should be now on Nuget.

@timothy-carter thanks for bringing this issue to our attention. Please let us know if the updates fix the issue for you!

**Comment by timothy-carter** [comment]
Thanks for the speedy fix @karolz-ms, this has fixed our issue.
