### ISSUE TITLE
Build - Missing FilterParser.peg.cs

### ISSUE THREAD

**Issue by Tridy** [Azure/diagnostics-eventflow#356]
Hi.
I am trying to build the project but I am getting an error message about FilterParser.peg.cs missing:
```
CSC : error CS2001: Source file '\diagnostics-eventflow\src\Microsoft.Diagnostics.EventFlow.Core\..\Microsoft.Dia
gnostics.EventFlow.FilterParserGenerator\FilterParser.peg.cs' could not be found. [\diagnostics-eventflow\src\Mic
rosoft.Diagnostics.EventFlow.Core\Microsoft.Diagnostics.EventFlow.Core.csproj]
```

**Comment by karolz-ms** [comment]
@tridy please take a look at [Contribution Guide](https://github.com/Azure/diagnostics-eventflow/blob/master/contributing.md). You have to run `restore` script to have `FileParser.peg.cs` file generated.

**Comment by Tridy** [comment]
ah, shame on me. Thanks!

**Comment by karolz-ms** [comment]
No, no, no worries. Sorry for being terse--and thanks for looking into EventFlow ☺️
