### ISSUE TITLE
Library dependency missing from list of libs needed

### ISSUE THREAD

**Issue by staypufdresideo** [Azure/diagnostics-eventflow#357]
Hello,

I needed to add this lib in addition to the ones you list.

- Microsoft.Diagnostics.EventFlow.Inputs.EventSource

Otherwise I get a error on run like so:

System.Exception: DiagnosticPipelineFactory: item of type ‘EventSource’ could not be created
System.IO.FileNotFoundException: Could not load file or assembly ‘Microsoft.Diagnostics.EventFlow.Inputs.EventSource, Culture=neutral, PublicKeyToken=null’. The system cannot find the file specified.

**Comment by karolz-ms** [comment]
@staypufdresideo which part of the README are you referring to?

**Comment by staypufdresideo** [comment]
Hello Karol,

This section:

> **Getting Started**
> To quickly get started, you can create a simple console application in VisualStudio and install the following Nuget packages:
> 
> Microsoft.Diagnostics.EventFlow.Inputs.Trace
> Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsights
> Microsoft.Diagnostics.EventFlow.Outputs.StdOutput

When I added:
> Microsoft.Diagnostics.EventFlow.Inputs.EventSource

then that error in my project went away.

Hope that helps.

Sam

**Comment by karolz-ms** [comment]
Sam, thanks for quick reply! I am little surprised because if you do not use `EventSource` input in your code nor EventFlow configuration file, you should not need to reference `Microsoft.Diagnostics.EventFlow.Inputs.EventSource`. 

Can you perhaps share the contents of your eventFlowConfig.json file?

**Comment by karolz-ms** [comment]
Closing this one for now, but feel free to re-open if this problem still persists.
