### ISSUE TITLE
Expected property 'targetProperty' is missing from event metadata

### ISSUE THREAD

**Issue by ysmoradi** [Azure/diagnostics-eventflow#358]
I have got a sample/simple repo at https://github.com/ysmoradi/AppInsightsSdkWithoutAzureAccount/tree/elastic

HealthCheck:

```
2020-05-11 20:12:36Z,Microsoft.Diagnostics.EventFlow.Output,Error,ElasticSearchOutput: Expected property 'targetProperty' is missing from event metadata
```

StdOutput is working fine, but the elastic output is not working properly.

**Comment by karolz-ms** [comment]
Thank you for reporting this issue, much appreciated.

I can see how this can happen [if the target of the dependency call is not available](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.ApplicationInsights/EventFlowTelemetryProcessor.cs#L363). 

We have two choices to fix this issue:
1. Not treat the data as dependency call information if the target is not known
2. Emit dependency metadata but set the target to empty (indicating target of the call is not known). This is akin to saying "the service has made a call, but we don't know what it was calling".

@xiaomi7732 @ysmoradi any thoughts or preferences?

**Comment by xiaomi7732** [comment]
@karolz-ms I am slightly leaning towards setting empty unless there's any defects that I don't see.

* By keep it as a dependency, are we keep more metadata?
* What is the data if it is NOT a dependency?

What's  your preference @ysmoradi & @karolz-ms ?

**Comment by ysmoradi** [comment]
As a matter of fact, I'm not the right person to even talk about these options' pros and cons.
As a user who is new to this fantastic library, I can describe what I'm able to see only.
Std-Console output is fine to me, and I'd like to see the same logged values in elastic too.
It's acceptable to see outputs have different behavior because they come from different backgrounds, so if Std output is able to achieve something that elastic output can't achieve, let the user know about it, then she can decide what to do.

I'm open to providing any more additional information if you like.
Hope this helps.

**Comment by karolz-ms** [comment]
Thank you for your input, @xiaomi7732 and @ysmoradi!

To give you more context, the metadata feature is about sending "semantically rich" information to log destination. In the case of "dependency call" the generated log record is supposed to describe what dependency the monitored service called, how long it took, what was the result, and so on.

Looks like in some cases the data coming from Application Insights does not have the target information, i.e. it is not known what dependency the service called. I was a bit on the fence how to handle that because, without the target bit, the dependency call record is not very useful. OTOH the presence of such records gives the service author opportunity to notice that something might be wrong with service logs and improve on that. So I agree with @xiaomi7732 suggestion and plan to fix the bug by emitting the dependency call record with empty target. Please holler if you disagree.

**Comment by ysmoradi** [comment]
> Thank you for your input, @xiaomi7732 and @ysmoradi!
> 
> To give you more context, the metadata feature is about sending "semantically rich" information to log destination. In the case of "dependency call" the generated log record is supposed to describe what dependency the monitored service called, how long it took, what was the result, and so on.
> 
> Looks like in some cases the data coming from Application Insights does not have the target information, i.e. it is not known what dependency the service called. I was a bit on the fence how to handle that because, without the target bit, the dependency call record is not very useful. OTOH the presence of such records gives the service author opportunity to notice that something might be wrong with service logs and improve on that. So I agree with @xiaomi7732 suggestion and plan to fix the bug by emitting the dependency call record with empty target. Please holler if you disagree.

This sounds good to me.

**Comment by karolz-ms** [comment]
@ysmoradi just a couple of remarks while I am working on the fix

You can work around the issue by setting the target on the dependency telemetry. i.e. after [this line](https://github.com/ysmoradi/AppInsightsSdkWithoutAzureAccount/blob/elastic/AppInsightsSdkWithoutAzureAccount/Startup.cs#L49) add something like

```csharp
exportExcelOperation.Telemetry.Target = "Excel";
```

Also, just FYI, you can also filter events before they get to any output, for example (`eventFlowConfig.json` file):

```json
{
  "inputs": [
    {
      "type": "ApplicationInsights"
    }
  ],
  "filters": [
    {
      "type": "drop",
      "Include":  "Target == localhost:9200"
    }
  ],
  "outputs": [
    {
      "type": "StdOutput"
    },
    {
      "type": "ElasticSearch",
      "serviceUri": "http://localhost:9200"
    }
  ],
  "schemaVersion": "2016-08-11"
}
```

**Comment by karolz-ms** [comment]
ApplicationInsights input version 1.5.1 has been published to nuget.org. Thanks @ysmoradi for bringing this to our attention and for a great repro.
