### ISSUE TITLE
Enabling Output to a file in the local disk

### ISSUE THREAD

**Issue by gurupasupathy** [Azure/diagnostics-eventflow#360]
It is a great idea and you guys have done a great job!

We currently don't seem to have a direct way to write the logs to a text file on the disk. We can use the StdOut and divert it output to a file, but that is more like a hack. Do you think it would be nice to have an Output out of the box for writing to a file? Please excuse, if this can be achieved already and I have missed it.

**Comment by karolz-ms** [comment]
@gurupasupathy we do not have an output that produces files, sorry. 

If you do need one, I would suggest looking at [Serilog](https://github.com/serilog/serilog) and its [file sink](https://github.com/serilog/serilog-sinks-file). You want an output that will do log file rolling and enforce limits on the amount of data stored, and Serilog does good job on that. Not to say that other libraries/systems don't, just what I am familiar with.

Hope this helps! Let us know if you have any other questions.

**Comment by gurupasupathy** [comment]
That helps @karolz-ms , thank you!
