### ISSUE TITLE
Exception thrown when trying to use Elasticsearch output

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/diagnostics-eventflow#363]
I'm seeing the following exception thrown when trying to use the Elasticsearch output package. I'm using the following EventFlow packages:

> Microsoft.Diagnostics.EventFlow.Inputs.EventSource 1.4.6
> Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch 2.7.2
> Microsoft.Diagnostics.EventFlow.ServiceFabric 1.6.0

Here's my eventFlowConfig.json:
```
{
	"inputs": [
		{
			"type": "EventSource",
			"sources": [
				{ "providerName": "Microsoft-ServiceFabric" },
				{ "providerName": "Microsoft-ServiceFabric-Services" },
				{ "providerName": "Microsoft-ServiceFabric-Actors" },
				{ "providerName": "MyApp-MyService" }
			]
		}
	],
	"outputs": [
		{
			"type": "ElasticSearch",
			"indexNamePrefix": "myApp",
			"serviceUri": "https://<deploymentId>.eastus2.azure.elastic-cloud.com:<port>",
			"basicAuthenticationUserName": "<user>",
			"basicAuthenticationUserPassword": "<password>",
			"refreshInterval": "15s",
			"mappings": {
				"properties": {
					"timestamp": {
						"type": "date_nanos"
					}
				}
			}
		}
	],
	"schemaVersion":  "2016-08-11" 
}
```

At my program's entry point, I set it up with:

```
private static void Main() 
{
  try
  {
    using diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("myPipeline");
```

And that should be about all of it. When I start the program, I receive the following exception in the catch block:

```
System.Exception: 'DiagnosticPipelineFactory: item of type 'ElasticSearch' could not be created
System.TypeLoadException: Could not load type 'Elasticsearch.Net.IInternalSerializerWithFormatter' from assembly 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
   at Nest.ConnectionSettingsBase`1..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializerFactory, IPropertyMappingProvider propertyMappingProvider)
   at Nest.ConnectionSettings..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializer, IPropertyMappingProvider propertyMappingProvider)
   at Nest.ConnectionSettings..ctor(IConnectionPool connectionPool, IConnection connection, SourceSerializerFactory sourceSerializer)
   at Nest.ConnectionSettings..ctor(IConnectionPool connectionPool)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput.Initialize(ElasticSearchOutputConfiguration esOutputConfiguration)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutput..ctor(IConfiguration configuration, IHealthReporter healthReporter)
   at Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearchOutputFactory.CreateItem(IConfiguration configuration, IHealthReporter healthReporter)
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.ProcessSection[PipelineItemType,PipelineItemChildType](IConfigurationSection configurationSection, IHealthReporter healthReporter, IDictionary`2 itemFactories, IDictionary`2 childFactories, String childSectionName)'
```
I tried installing Elasticsearch.Net 7.8.1 in hopes that the most recent version would fix things, but the issue persists.

Any ideas of what I'm doing wrong in hooking this up?

Thanks!

**Comment by karolz-ms** [comment]
Looks like an older version of Elastisearch.Net assembly is being loaded (7.0)--EventFlow requires 7.1 or newer. Are you getting any version downgrade warnings during build of you app?

**Comment by WhitWaldo** [comment]
Nope, I tried installing Elasticsearch.Net 7.8.1 in hopes that was the issue, but it hasn't remedied anything. Nothing unusual in the build output.

> 1>------ Build started: Project: <app>, Configuration: Debug Any CPU ------
> 1>C:\...\<app>.cs(273,42,273,58): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
> 1><app> -> C:\...\bin\Debug\netcoreapp3.1\win7-x64\<app>.dll
> 1>Done building project "<app>.csproj".
> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
>

**Comment by karolz-ms** [comment]
Can you share your project file, or maybe even a standalone repro project?

**Comment by WhitWaldo** [comment]
Sure - give me a few to put something together.

**Comment by WhitWaldo** [comment]
Well that took longer to assemble than expected since I put a barebones project together and couldn't repro. I concluded it had to be one of the other packages I'm importing and indeed it was. After an awful lot of trial and effort, I've found that the build works fine if Elasticsearch.Net v7.8.1 is not included anywhere in the build and it throws with the above exception if it is.

Unfortunately, I discovered a dependency on it elsewhere, so I can't do without it, which is why I found the exception throwing regardless of explicitly adding the project or not.

The important files are /Stateless1/Stateless1.csproj (to add and remove the nuget packages) and /Stateless1/Program.cs where you'll find the breakpoint that'll be hit if line 21 in Stateless1.csproj is not commented out.

[EventflowSmaple.zip](https://github.com/Azure/diagnostics-eventflow/files/4941000/EventflowSmaple.zip)

**Comment by karolz-ms** [comment]
I was able to reproduce the problem, investigating.

**Comment by karolz-ms** [comment]
So the problem is if you explicitly reference `Elasticsearch.Net` version 7.8.1, you also need to reference the corresponding `Nest` package (high-level Elasticearch client library). After adding the following line to `Stateless1.csproj` the service loads successfully

```xml
<PackageReference Include="Nest" Version="7.8.1" />
```

Let us know please if this solves the problem and if you run into issues with sending data to Elasticsearch (I do not expect any, but we haven't tested Eventflow with ES client 7.8.1).

I understand this was just a quick sample to reproduce the problem (very helpful, thanks a bunch!), but if you haven't done so already, please make sure you are familiar with [recommendations for service startup code](https://github.com/azure/diagnostics-eventflow#service-fabric-support). In particular, handling `Ctrl-C` signal will result in much shorter service restart/upgrade times.

**Comment by WhitWaldo** [comment]
That fixes it on my side. Thank you for your assistance here!
