### ISSUE TITLE
Request ability to use ConnectionString in ApplicationInsightsOutputConfiguration

### ISSUE THREAD

**Issue by acamann** [Azure/diagnostics-eventflow#369]
Due to app insights resource requiring a connection string with endpoint suffix, we are unable to set the instrumentation key within the event flow config file.  We can set a ConfigurationFilePath but lose the ability for this to be distinct across environments.  

ConnectionStrings have been the preferred configuration method since Microsoft.ApplicationInsights version 2.12.0.  It would be helpful to set this as an output configuration parameter here: diagnostics-eventflow/src/Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsights/Configuration/ApplicationInsightsOutputConfiguration.cs

**Comment by karolz-ms** [comment]
Thank you for the suggestion, @acamann!

References:
- Issue describing goals and referencing the set of PRs that implemented it: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1221
- `ConnectionString` syntax: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Endpoints/EndpointProvider.cs#L31 (this is the best "documentation" I could find 😞 )

**Comment by karolz-ms** [comment]
Application Insights output 1.6.0 that supports connection strings is now published on nuget.org.
