### ISSUE TITLE
Microsoft.Diagnostics.EventFlow.Outputs.EventHub support for .NET Core

### ISSUE THREAD

**Issue by frankfajardo** [Azure/diagnostics-eventflow#37]
This is more a question than an issue: When is `Microsoft.Diagnostics.EventFlow.Outputs.EventHub` going to be available on .NET Core?

**Comment by frankfajardo** [comment]
I understand the dependency is the [ServiceBus library for .NET Core.](https://blogs.msdn.microsoft.com/servicebus/2016/12/20/service-bus-net-standard-and-open-source/)

**Comment by karolz-ms** [comment]
Correct, once the ServiceBus library for .NET Core comes out of preview, we can add a Core version of the output. 

If you need it sooner, feel free to experiment with the preview version of the library. And if you get something working, please share if you can!
