### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Expecho** [Azure/diagnostics-eventflow#38]
Hi there,

can you share what the roadmap is for this library? I've noticed not all input and outputs are supported on .Net Core. Will that change in the (near) future or is there a limitation that causes it to never reach the .Net Core platform?

**Comment by karolz-ms** [comment]
We do not have an official roadmap yet, but with respect to .NET Core we want to support as many of the inputs and outputs as possible. Generally there are two kinds of limitations that prevent us from releasing a .NET Core version of an input or output:

1. A dependency does not have a .NET Core client library (yet). For example that is the case with EventHub today. EventHub folks have a .NET Core client library in preview, so I expect us to release a Core version of the input in the near future.

2. There is more fundamental technical problem and it is unlikely that it will be addressed by .NET Core. Such is the case with performance counter input--performance counters are Windows-only, .NET Core is cross-platform, so it is unlikely that we will ever have a Core version of this input.

Does this make sense?

**Comment by Expecho** [comment]
Thanks for answering. I do get the point of the Windows-only inputs. I am mostly interested in the EventHub and Application Insights sinks so I am glad to here that is just a matter of waiting for the .Net Core support of these particular libraries.
