### ISSUE TITLE
Duplicate dependencies in elastic search output

### ISSUE THREAD

**Issue by arwyl** [Azure/diagnostics-eventflow#385]
https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch/ElasticSearchOutput.cs

As I can see code blocks from lines 154-165 and 167-178 are identical

so dependencies are yielded twice

**Comment by karolz-ms** [comment]
😊  Sorry about that @arwyl Good catch! We'll try to fix it ASAP

**Comment by karolz-ms** [comment]
Re-opening till new NuGets are published

**Comment by karolz-ms** [comment]
Elasticsearch output package 2.7.3 has been published to nuget.org
