### ISSUE TITLE
Shall we remove unused `Microsoft.Diagnostics.EventFlow.TableStorage`?

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/diagnostics-eventflow#396]
Hi everyone,

After touch base with @karolz-ms, we reached an agreement to remove `Microsoft.Diagnostics.EventFlow.TableStorage` due to lack of usability, and in the sake of having a reduced attacking surface for vulnerability.

But we want to hear everyone's opinion, specially, ones that vote against the decision, just in case there's some hidden scenarios that we should've realized. Please comment below if you think there's a scenario for you and the project is worth keeping.

**Details**
The package was developed at the beginning of the project but never since released a NuGet package for it. And there's no inquiries about it either.

**Comment by karolz-ms** [comment]
Resolved via https://github.com/Azure/diagnostics-eventflow/pull/398 -- we did remove it
