### ISSUE TITLE
Does EventFlow supports for app in Azure Kubernetes Service?

### ISSUE THREAD

**Issue by vitaly-pavluk** [Azure/diagnostics-eventflow#409]
Documentation states
__The EventFlow suite supports .NET applications and .NET Core applications. It allows diagnostic data to be collected and transferred for applications running in these Azure environments:_

- _Azure Web Apps_
- _Service Fabric_
- _Azure Cloud Service_
- _Azure Virtual Machines_

Does it imply that .NET6 app running in Docker inside the AKS cannot use "Diagnostics.EventFlow"?

**Comment by karolz-ms** [comment]
Not at all, EventFlow is completely OK to be used inside AKS. I will edit this piece of README for clarity; thanks for bringing this up!
