### ISSUE TITLE
Creating Custom Output Extensions

### ISSUE THREAD

**Issue by Expecho** [Azure/diagnostics-eventflow#41]
How does one create a custom output. I've take the code form the standard output sink but when hooking things up it does not work (as in, no breakpoint are hit, no error messages appear.

I think I need more info about what to put into the extensions configuration of the config file.

**Comment by karolz-ms** [comment]
Good point, we should probably update the docs.

In the meantime please take a look at [diagnostic pipeline factory tests](https://github.com/Azure/diagnostics-eventflow/blob/master/test/Microsoft.Diagnostics.EventFlow.Core.Tests/DiagnosticsPipelineFactoryTests.cs), in particular the test called `CanOverrideDefaultPipelineItems`. Basically, you need to create a factory for your output, then point EventFlow to that factory via an element in the extensions section of the configuration. In case of a custom output the "category" must be set to "outputFactory", "type" to whatever you want the output to be referred as (e.g. "myAwesomeOutput") and the "qualifiedTypeName" needs to be set to a string that allows EventFlow to instantiate the factory via `Type.GetType(typeName)`

This of course assumes you want to use the configuration. Nothing prevents you from bypassing `DiagnosticPipelineFactory` altogether and instantiating a `DiagnosticPipeline` directly. See [diagnostic pipeline tests](https://github.com/Azure/diagnostics-eventflow/blob/master/test/Microsoft.Diagnostics.EventFlow.Core.Tests/DiagnosticPipelineTests.cs) for examples. For testing the output that is probably preferable.

**Comment by Expecho** [comment]
Thanks, I got it working now! Do you guys have plans for additional Input/output items that will be provided out of the box? For example, I see there is a TableStorage output that is not yet included in the latest NuGet package.

**Comment by karolz-ms** [comment]
We are planning to add an input for manifest-based ETW providers very soon. Other than that we have a long backlog but priorities are continuously shifting :-)

What input or outputs would you like to see?

**Comment by Expecho** [comment]
Well, I was thinking about azure blob storage or azure data lake so we can analyze them using for example Azure DataLake analytics

**Comment by karolz-ms** [comment]
Makes sense. Can't make any promises at the moment, but we have heard from several people about rolling log files, BLOB storage and DataLake, so these are definitively on the radar.
