### ISSUE TITLE
Add ability to configure index format string

### ISSUE THREAD

**Issue by BuddhaBuddy1** [Azure/diagnostics-eventflow#416]
Daily indexes are too big for our situation. We would like to have monthly ones, but there is no way to configure the format string. It is hard coded to 'yyyy.MM.dd'.

I would like to be able to configure the index format string.

**Comment by BuddhaBuddy1** [comment]
I have submitted [PR 417](https://github.com/Azure/diagnostics-eventflow/pull/417) to implement this feature.

**Comment by karolz-ms** [comment]
This is done
