### ISSUE TITLE
Microsoft.Diagnostics.EventFlow.Outputs.StdOutput 1.7.1 depends on Microsoft.Diagnostics.EventFlow.Json which does not exist

### ISSUE THREAD

**Issue by ghelyar** [Azure/diagnostics-eventflow#429]
[Microsoft.Diagnostics.EventFlow.Outputs.StdOutput 1.7.1](https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Outputs.StdOutput/1.7.1#dependencies-body-tab) fails to restore because [Microsoft.Diagnostics.EventFlow.Json](https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Json/) does not exist

**Comment by kzadora** [comment]
Oops. I know what the problem is, I forgot that we need to publish the new JSON lib.

**Comment by antymon4o** [comment]
Would it be better if this dep Microsoft.Diagnostics.EventFlow.Json is internal assembly dependency rather than creating a new nuget package with the required versioning?

**Comment by antymon4o** [comment]
This seems similar:
https://stackoverflow.com/questions/59611527/how-to-pack-a-referenced-project-into-a-nuget-package

**Comment by karolz-ms** [comment]
Hmm, not sure... at this point I am inclined to try the simplest thing that will fix this and a separate NuGet package is just that.

**Comment by ghelyar** [comment]
It tends to be a bad idea to pack dlls for dependencies directly into packages anyway because if multiple packages contain the same dll it can lead to problems.

**Comment by karolz-ms** [comment]
Keep open till NuGet is updated

**Comment by karolz-ms** [comment]
@ghelyar The Json package should be accessible from NuGet now. LMK please if this solves the problem, or if there are any issues still.

**Comment by ghelyar** [comment]
This seems to work now, thank you.

**Comment by karolz-ms** [comment]
Fantastic, thanks for confirmation
