### ISSUE TITLE
Application Insights, how can I prevent Exceptions from being recorded as Traces

### ISSUE THREAD

**Issue by GeneralXception** [Azure/diagnostics-eventflow#46]
Hi,

I'm using Event Flow with Service Fabric, SeriLog and Application Insights.

When an Exception is logged by my application, Serilog's Log.Error is called and I can see the Error in Application Insights Traces, however, I was hoping to see the Error recorded as an Exception within Application Insights.

The Custom Data section of the Trace shows that the Level was Error, so I think I've got everything wired up correctly. As is stands, the exceptions will be hard to spot along with all other legitimate Traces.

Is there a way to force the Application Insights output library to do this or is this a responsibility of the Serilog input library?

Thanks

**Comment by karolz-ms** [comment]
Hi Steve, this is simply not implemented at the moment.

In general we want to support all standard Application Insights telemetry types. What is missing today are Dependency, Event, Exception and PageView. These are generally useful concepts so we think it makes sense to define them as standard metadata types. Then we would Application Insights EventFlow output be aware of them and submit proper AI telemetry when events are decorated with these metadata.

We want to do this work pretty soon, but it will probably take us a couple of month to get there.

**Comment by nblumhardt** [comment]
@karolz-ms would it be worth opening a ticket to discuss the possible range of standard metadata items? I know `Message`, `EventId` (or `EventType`) and perhaps `MessageTemplate` would be useful for the log data use case.

**Comment by karolz-ms** [comment]
@nblumhardt Good suggestion, thanks. I have opened  [What additional standard metadata items should be included in EventFlow](https://github.com/Azure/diagnostics-eventflow/issues/48).

**Comment by karolz-ms** [comment]
We will use https://github.com/Azure/diagnostics-eventflow/issues/48 to track the work item of adding support for exceptions and other telemetry items

**Comment by erickbp** [comment]
Hi, is this supported now? I cannot figure out how to make work.
My project is:
- Service Fabric
- .net core 2.2

I cannot figure out how to produce the event in my `ActorEventSource : EventSource` class that ends up in Application Insights as an Exception event type.

Thanks

```
{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
        {
          "providerName": "MyCompany-TestingEventFlow-Actor1",
          "level": "Informational",
          "keywords": "0x7F"
        },
        {
          "providerName": "Microsoft-ServiceFabric-Actors",
          "level": "Warning",
          "keywords": "0x7F"
        }
      ]
    }
  ],
  "outputs": [
    {
      "type": "ApplicationInsights",
      "instrumentationKey": "servicefabric:/ApplicationInsights/InstrumentationKey",
      "filters": [
        {
          "type": "metadata",
          "metadata": "exception",
          "include": "ProviderName == MyCompany-TestingEventFlow-Actor1",
          "exceptionProperty": "exception"
        }
      ]
    }
  ],
  "schemaVersion": "2016-08-11"
}
```

![image](https://user-images.githubusercontent.com/10678433/50393969-cb73e580-0727-11e9-9780-5c955539e812.png)

**Comment by karolz-ms** [comment]
@erickbp the short answer is, you cannot produce an event that has an `Exception` instance attached using EventSource because, as you mentioned [in the comment to issue 92](https://github.com/Azure/diagnostics-eventflow/issues/92#issuecomment-449762529) EventSource restricts the types of data it can use as event properties, You will need to use a different logging API. Any of these will do:
  - Microsoft.Extensions.Logging (ASP.NET ILogger)
  - Serilog
  - DiagnosticSource
  - Application Insights SDK
You can use one of these alternative APIs just in case when you need to produce "exception" events, or you could try to switch wholesale from EventSource to a different API.

**Comment by wesco-krishnanunni** [comment]
Do we have any resolution for this issue? For me also some  of the exceptions are tagged as trace in application insights.

**Comment by karolz-ms** [comment]
@wesco-krishnanunni the resolution is to use one of the APIs mentioned in the previous comment to log exceptions.

In your application, where do these Exceptions come from and what is the API that is used for logging them, do you know?
