### ISSUE TITLE
Configuration of eventFlowConfig.json in Service Fabric at Application level

### ISSUE THREAD

**Issue by JonJam** [Azure/diagnostics-eventflow#47]
I would like to be able to override settings in eventFlowConfig.json when using Service Fabric at the Application level.

This is order that I can have specify a different Application Insights Key in an Application Parameter file i.e. Dev, Pre-Prod and Prod and then have the Service use that key, rather than hard-coding it at the service level.

**Comment by karolz-ms** [comment]
@JonJam thanks for the suggestion, it is a very good one. We should be able to add this capability in near future.

**Comment by karolz-ms** [comment]
Will publish the new NuGet packages shortly
