### ISSUE TITLE
Is there any plan to support Seq outputs?

### ISSUE THREAD

**Issue by zhichaoh** [Azure/diagnostics-eventflow#52]
This is very helpful to debug Service Fabric locally.

**Comment by karolz-ms** [comment]
We have a backlog item to make it easier to view traces from EventFlow during local debugging session, not necessarily using Seq, but the goal is similar. At this point I am not sure when we will put this item on the schedule.

In the meantime there are a few options available:

1. For Service Fabric specifically, if you are using EventSource as your logging API, we have a "Diagnostic Viewer" in VS that is able to capture traces from the application's EventSource as well as Fabric runtime EventSources.

2. Otherwise it should be pretty easy to write a custom EventFlow output that, say, writes logs to a file/set of files. In fact, we are planning to implement something along these lines, but a simple version that is "good enough" for debugging purposes should be a "one afternoon" project. If you want to pursue something like this, [StdOutput](https://github.com/Azure/diagnostics-eventflow/tree/master/src/Microsoft.Diagnostics.EventFlow.Outputs.StdOutput) would be a good starting point. Let me know if you need help!

**Comment by nblumhardt** [comment]
I'm keen to take a shot at a Seq output; I've had it on my to-do list for a while :-) I'll try to make some time this week and see how much work is involved.

@zhichaoh just out of interest, besides typical application log data from things like Serilog, are there particular event types coming through EventFlow that you'd find particularly useful in Seq?

**Comment by zhichaoh** [comment]
@nblumhardt I am using eventflow in a Service Fabric local cluster (consists of a few physical machines).  My current set up is SeriLog Input -> DiagnosticPipeline -> StdOutput Output.  I also redirect the console output to local file in the exe ServiceManifest.xml file.  I can see the log events sent to the file if I knew which node/VM the executable is running on.  This is however difficult to track because the executable can run on any node at any time.  I can send the output to AppInsights.  However, it is very helpful to send the output to a local log server such as Seq when Internet is not reachable.

I also tried to follow @karolz-ms's suggestion to write some output plugin following the StdOuput implementation.  I tried to do a quick test by modifying the StdOuput.cs file locally so that it send the EventData as Json object via Serilog to Seq to just test the concept.  However, I can not test it using service fabric because of the strong named assembly validation.  Since there is no instruction on how to create a plugin dll in the "extensions" config file, I am kind of stuck.

I don't have specific needs for Seq output as long as it respects the common rules of writing Output.    As for event type, I am interested in all application events and service fabric events for the troubleshooting.

Thanks!

**Comment by zhichaoh** [comment]
It looks like DiagnosticPipelineFactory.cs CreateItemFactories method is check if custom OutputFactory can be created by the given user provided the "extensions" section.  I will try to create a plugin and put a reference there to see if it works.

**Comment by zhichaoh** [comment]
Still can not plugin my SeqOutput dll.  I have followed the hint in the source code by creating a SeqOutput.cs and SeqOutputFactory.cs with the given extension section
```
"extensions": [
    {
      "Category": "outputFactory",
      "Type": "Seq",
      "QualifiedTypeName": "SeqOutput.SeqOutputFactory, SeqOutput.SeqOutput, Culture=neutral"
    }
  ]
```

My SeqOutput.cs is: 
```
namespace SeqOutput
{
    public class SeqOutput : IOutput
    {
        public static readonly string TraceTag = nameof(SeqOutput);

        private readonly IHealthReporter healthReporter;

        public SeqOutput(IHealthReporter healthReporter)
        {
            Requires.NotNull(healthReporter, nameof(healthReporter));
            this.healthReporter = healthReporter;
            Log.Logger = new LoggerConfiguration()
                             .WriteTo.Seq("http://localhost:5341")
                             .CreateLogger();
        }

        public Task SendEventsAsync(IReadOnlyCollection<EventData> events, long transmissionSequenceNumber, CancellationToken cancellationToken)
        {
            try
            {
                foreach (EventData evt in events)
                {
                    string eventString = JsonConvert.SerializeObject(evt);
                    string output = $"[{transmissionSequenceNumber}] {eventString}";

                    //Console.WriteLine(output);
                    Log.Information(output);
                }
                return Task.FromResult(true);
            }
            catch (Exception ex)
            {
                this.healthReporter.ReportProblem($"Fail to send events in batch. Error details: {ex.ToString()}");
                throw;
            }
        }
    }
}
```
And my SeqOutputFactory.cs is defined as
```
class SeqOutputFactory : IPipelineItemFactory<SeqOutput>
    {
        public SeqOutput CreateItem(IConfiguration configuration, IHealthReporter healthReporter)
        {
            Requires.NotNull(healthReporter, nameof(healthReporter));

            return new SeqOutput(healthReporter);
        }
    }
```

Because the EventFlow.Core nupkg does not have source published (needs confirmation), I can not debug into the DiagnosticPipelineFactory to figure out what kind of mismatch that I may have. 

Any insights?

**Comment by zhichaoh** [comment]
Now, sort of getting it working.  The extensions should be written as (following some hints from issue #41)
```
"extensions": [
    {
      "category": "outputFactory",
      "type": "StdOutput",
      "qualifiedTypeName": "SeqOutput.SeqOutputFactory, SeqOutput"
    }
  ]
```
However, note that, I can only override the StdOutput by using the same type.  If I change the "type" to be something else, the plugin dll will be loaded.

**Comment by karolz-ms** [comment]
I tried to explain how to use configuration to instantiate custom outputs in my reply to the issue https://github.com/Azure/diagnostics-eventflow/issues/53

@zhichaoh @nblumhardt so I am thinking at this point we could use this issue to track the work item to add the Seq output, or we could just close this issue and track the work item in some other way. Let me know what you prefer.

**Comment by karolz-ms** [comment]
@zhichaoh, I hear you, but given that the Seq output had no definitive delivery date I think it is better to close this issue for now.
