### ISSUE TITLE
Cannot add custom output via extensions section

### ISSUE THREAD

**Issue by zhichaoh** [Azure/diagnostics-eventflow#53]
The DiagnosticPipelineFactory ignore extensions for custom outputs specified in the extensions section (following instruction given is #41).  

Way to reproduce, Change "StdOutput" to any other name (such as "MyOutput" not of the provided standard outputs in the CanOverrideDefaultPipelineItems unit test.  The test will fail. 

Debugging through the code, ProcessSection in DiagnosticsPipelineFactory only process predefined outputs keys.  Since "MyOutput" is not processed, so it is ignored even though outputFactories already have the entry defined.

**Comment by karolz-ms** [comment]
@zhichaoh I think you are a bit confused about how the extension mechanism works.

Each extension record has 3 properties:
- "category" identifies extension type. Currently types recognized by DiagnosticPipelineFactory are inptuFactory, filterFactory, outputFactory or healthReporter. (BTW, the last type should really be healthReporterFactory, I have opened issue https://github.com/Azure/diagnostics-eventflow/issues/54 to track that)
- "type" is the tag that identifies the extension in other parts of the configuration document(s). It is totally up to the user of an extension what she uses here.
- "qualifiedTypeName" is the string that allows DiagnosticPipelineFactory to instantiate the extension factory

Here is a very simple example that illustrates how to create a custom output. 

```csharp
namespace EventFlowCustomOutput
{
    class Program
    {
        static void Main(string[] args)
        {
            using (DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json"))
            {
                Trace.TraceError("Hello, world!");
                Thread.Sleep(1000);
            }
        }
    }

    class CustomOutput : IOutput
    {
        public Task SendEventsAsync(IReadOnlyCollection<EventData> events, long transmissionSequenceNumber, CancellationToken cancellationToken)
        {
            foreach(var e in events)
            {
                Console.WriteLine($"CustomOutput: event says '{e.Payload["Message"]?.ToString() ?? "nothing"}'");
            }
            return Task.CompletedTask;
        }
    }

    class CustomOutputFactory : IPipelineItemFactory<CustomOutput>
    {
        public CustomOutput CreateItem(IConfiguration configuration, IHealthReporter healthReporter)
        {
            return new CustomOutput();
        }
    }
}
```

(content of eventFlowConfig.json)
```json
{
  "inputs": [
    {
      "type": "Trace"
    }
  ],
  "filters": [
  ],
  "outputs": [
    {
      "type":  "CustomOutput"
    }
  ],
  "schemaVersion": "2016-08-11",

  "extensions": [
    {
      "category": "outputFactory",
      "type": "CustomOutput",
      "qualifiedTypeName": "EventFlowCustomOutput.CustomOutputFactory, EventFlowCustomOutput"
    }
  ]
}
```

I am going to take an action item to add this to the documentation, so there is no more confusion.

Let me know if this helps!

**Comment by karolz-ms** [comment]
Also, it is worth noting that you can create the whole pipeline imperatively, i.e. through code, without relying on configuration and DiagnosticPipelineFactory. When you are prototyping something, that might be a simpler way to start.

**Comment by zhichaoh** [comment]
@karolz-ms, I see, I missed the part that an output for the custom output must be provided in the config,
```
"outputs": [
    {
      "type":  "CustomOutput"
    }
  ],
```

Great, everything is working as intended.

Thanks!

**Comment by karolz-ms** [comment]
Documentation was updated to cover extensibility, so the issue can be closed
