### ISSUE TITLE
ServiceFabric + ApplicationInsights - System.NullReferenceException

### ISSUE THREAD

**Issue by MECLab-Keags** [Azure/diagnostics-eventflow#56]
Hi Team,

I'm currently experiencing an issue where a Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.AddProperties is throwing a NullReferenceException in a ServiceFabric cluster. I cannot replicate the issue running the applications in my local cluster.

Here is the error I'm seeing in the Service Fabric Explorer:
>Error event: SourceId='My-DiagnosticPipeline', Property='Connectivity'.
>Diagnostics data upload has failed.
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.AddProperties(ISupportProperties item, EventData e)
>   at Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.SendEventsAsync(IReadOnlyCollection`1 events, Int64 transmissionSequenceNumber, CancellationToken cancellationToken)

Any help would be much appreciated.
Cheers
Keagan

**Comment by karolz-ms** [comment]
Hmm. Is it possible that some of the values in your event payload are null? I think we have a bug in https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsights/ApplicationInsightsOutput.cs line 198 where we call payloadItem.Value.ToString() without checking for null...

**Comment by karolz-ms** [comment]
@MECLab-Keags I pushed a new release of the ApplicationInsights plugin that fixes this issue in the code (version 1.0.1 of the Nuget package). Please give it a try, and if you still see problems, feel free to reactivate the issue.

**Comment by MECLab-Keags** [comment]
@karolz-ms looks good! Thanks for the help. I'm seeing another error, however I think it's a totally separate problem, so I'll open a new issue.

Cheers
