### ISSUE TITLE
There is a health event with same SourceId and Property with equal or higher sequence number. ServiceFabric + ApplicationInsights

### ISSUE THREAD

**Issue by MECLab-Keags** [Azure/diagnostics-eventflow#57]
Hi @karolz-ms, 

I'm now seeing this error while upgrading a ServiceFabric application via VSTS release management.
This causes the release to fail, occasionally the release succeeds without any errors, or if the release is rolled back due to the error after 15 - 30 minutes the error disappears and you no longer see it in the ServiceFabric explorer.

>	Error event: SourceId='My-DiagnosticPipeline', Property='Connectivity'.
>Diagnostics data upload has failed.
>System.Fabric.FabricException: There is a health event with same SourceId and Property with equal or higher sequence number. Health report versus existing sequence numbers: 131341925004487551, 131341925006674981. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C11
>   at System.Fabric.Interop.NativeClient.IFabricHealthClient3.ReportHealth(IntPtr healthReport)
>   at System.Fabric.FabricClient.HealthClient.ReportHealthHelper(HealthReport healthReport)
>   at System.Fabric.Interop.Utility.<>c__DisplayClass13.b__12()
>   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String >functionArgs)
>   --- End of inner exception stack trace ---
>   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String >functionArgs)
>   at System.Fabric.Interop.Utility.RunInMTA(Action action)
>   at System.Fabric.FabricClient.HealthClient.ReportHealth(HealthReport healthReport)
>   at >Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.SendEventsAsync(IReadOnlyCollection`1 events, Int64 transmissionSequenceNumber, CancellationToken cancellationToken)

Any help again would be much appreciated.
Cheers
Keagan

**Comment by karolz-ms** [comment]
Roger. Interesting, I haven't seen this one yet. I am following up with Service Fabric folks on what to do about it...

**Comment by karolz-ms** [comment]
Sorry for late reply. I have a fix, just needed to take care of migrating to VS 2017/MSBuild 15 first. ETA noon tomorrow (Pacific time).

**Comment by karolz-ms** [comment]
OK, the fix has been submitted. You need Microsoft.Diagnostics.EventFlow.ServiceFabric package version 1.1.1. Please reactivate the issue if you still see problems!

**Comment by MECLab-Keags** [comment]
@karolz-ms sorry about the delay getting back to you.
I've upgraded all our services and it looks good!

Cheers for that
Keagan

**Comment by karolz-ms** [comment]
Hey, glad to hear that, cheers!
