### ISSUE TITLE
We are trying to log events from azure service fabric to app insight. It is observed that events with different event level (warning, critical) are logged as trace only. Is there any way to distingush between the events

### ISSUE THREAD

**Issue by akhilaj** [Azure/diagnostics-eventflow#59]

**Comment by karolz-ms** [comment]
Currently Application Insights output in EF can produce traces, metrics and requests. We are planning to add support for “dependency”, “exception” and possibly “event” (see issue https://github.com/Azure/diagnostics-eventflow/issues/48),  but it is not there at the moment.

The way you produce things other than traces is to attach appropriate metadata to events that are to be turned into metrics or requests:
•	https://github.com/Azure/diagnostics-eventflow#metadata (in particular take a look at some examples at the end of this paragraph)
•	https://github.com/Azure/diagnostics-eventflow#standard-metadata-types (describes all the properties supported by “request” and “metric” metadata)
