### ISSUE TITLE
Default config file is not delivered through Microsoft.Diagnostics.EventFlow nuget on .NETCore

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/diagnostics-eventflow#6]

**Comment by karolz-ms** [comment]
This probably requires placing the config file under contentFiles directory, see https://docs.nuget.org/ndocs/schema/nuspec

**Comment by karolz-ms** [comment]
Turns out this is simply _not supported_ with the .NET Core project system :-( As for now there are no plans to add this capability.

I have added some instructions to the docs describing how to add the config file manually to the project and make it work.
