### ISSUE TITLE
Seeing TPL events as traces in AppInsights

### ISSUE THREAD

**Issue by dkkapur** [Azure/diagnostics-eventflow#72]
When deploying an app with Service Fabric and pushing its diagnostics to Application Insights from EventFlow, TPL event traces show up.

![eventflow traces](https://cloud.githubusercontent.com/assets/2343218/24881979/61c58184-1df4-11e7-942e-236f23e61897.jpg)

We were able to use a filter to remove these from showing up, but in general, these should probably be removed anyway.

**Comment by karolz-ms** [comment]
Fixed with EventSource and ETW (NuGet) packages version 1.1.1 or newer.
