### ISSUE TITLE
Support for encrypted Service Fabric settings

### ISSUE THREAD

**Issue by zyrow123** [Azure/diagnostics-eventflow#77]
extend the support for Service Fabric settings and application parameters to allow for encrypted settings as well.

**Comment by zyrow123** [comment]
Just noticed this comment in the code.
// We omit encrypted values due to security concerns--if you need them, use Service Fabric APIs to access them

So it is intentionally committed, so if I wanted to encrypt my instrumentation key for application insights and then still use the ServiceFabricDiagnosticPipelineFactory how would I go about doing that

**Comment by karolz-ms** [comment]
Honestly there is no good way...

Maybe we are too restrictive, let me think about it

**Comment by karolz-ms** [comment]
Resolved with Service Fabric NuGet package version 1.1.3
