### ISSUE TITLE
Need an operator for the "is keyword set" test

### ISSUE THREAD

**Issue by karolz-ms** [Azure/diagnostics-eventflow#80]
In the current implementation none of the operators supported by expression allow for easy testing of individual keywords. We need an operator for that (to test that all bits in the keyword mask are set)

Something like this:
```json
  "filters" : [
    {
      "type": "drop",
      "include": "Keywords &== 0x4"
    }
  ]
```

We probably also need an operator that checks whether none of the bits in the keyword mask are set (perhaps !== makes sense as a symbol for this operation)

**Comment by gperrego** [comment]
Yes Yes Yes Please.

**Comment by yantang-msft** [comment]
#85

**Comment by karolz-ms** [comment]
Core package version 1.1.4 has the operator &== implemented. 

Feel free to reactivate this issue if the !== operator is also necessary in your scenario.
