### ISSUE TITLE
System.ArgumentException: The key already existed in the dictionary

### ISSUE THREAD

**Issue by timomta** [Azure/diagnostics-eventflow#87]
Hello,

I am using the Application Insights output and the EventSource input with an application that I wrote for Service Fabric. My application itself is heathy, but the EventSource pipeline is throwing this exception (copied from the Service Fabric Explorer window):

Error event: SourceId='WeatherAPI-WeatherAPIService-DiagnosticsPipeline', Property='Connectivity'.
Diagnostics data upload has failed.
System.ArgumentException: The key already existed in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary.Add(TKey key, TValue value)
   at Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.AddProperties(ISupportProperties item, EventData e, Boolean setTimestampFromEventData)
   at Microsoft.Diagnostics.EventFlow.Outputs.ApplicationInsightsOutput.SendEventsAsync(IReadOnlyCollection`1 events, Int64 transmissionSequenceNumber, CancellationToken cancellationToken) 

What is this error telling me? I'm not sure what dictionary it is keeping, its keys, or what that has to do with connectivity.

**Comment by karolz-ms** [comment]
@timomta What is the version of the EventFlow.Core package that your application is using?

**Comment by timomta** [comment]
Hello,

Microsoft.Diagnostics.EventFlow.Core 1.1.4

**Comment by karolz-ms** [comment]
@timomta I think I know where the problem might be. Do any of your EventSource methods (event methods) have parameters named "keywords", "level" or "providerName" by any chance?

**Comment by timomta** [comment]
I am using it to capture the events sent by Service Fabric's ServiceEventSource.cs, ServiceEventSource class. If you create a Service Fabric project in visual studio, you'll see this file/class. It does have a static class named Keywords:
        // Event keywords can be used to categorize events. 
        // Each keyword is a bit flag. A single event can be associated with multiple keywords (via EventAttribute.Keywords property).
        // Keywords must be defined as a public class named 'Keywords' inside EventSource that uses them.
        public static class Keywords
        {
            public const EventKeywords Requests = (EventKeywords)0x1L;
            public const EventKeywords ServiceInitialization = (EventKeywords)0x2L;
        }

There are also Event methods that pass in level:

        private const int MessageEventId = 1;
        [Event(MessageEventId, Level = EventLevel.Informational, Message = "{0}")]
        public void Message(string message)
        {
            if (this.IsEnabled())
            {
                WriteEvent(MessageEventId, message);
            }
        }

Is this what you were looking for?

**Comment by karolz-ms** [comment]
@timomta Not exactly. I am asking about event methods in your EventSource class (the ones decorated with Event attribute). Do any of these methods have parameters named "keywords", "level" or "providerName". For example

```csharp
[Event(15, Level = EventLevel.Informational)]
public void ReportStuff(int param1, int level)
{
  if (this.IsEnabled())
  {
    WriteEvent(15, param1, level);
  }
}
```

**Comment by timomta** [comment]
I searched using VS and I cannot find any methods that have parameters named "keywords", "level" or "providerName" in the generated ServiceEventSource class. Those words are in the attributes that decorate the methods (ie [Event ... ] ).

**Comment by karolz-ms** [comment]
Roger.

I will try to fix this based on the call stack you have observed. Should have a new version of the ApplicationInsights output sometime later today. Will let you know when it is available

**Comment by karolz-ms** [comment]
This should no longer occur with Application Insights output package version 1.1.4 or newer
