### ISSUE TITLE
The ability to add Nested Scopes when using MicrosoftLogging input

### ISSUE THREAD

**Issue by JoeL1862** [Azure/diagnostics-eventflow#93]
Would it be possible to add the ability to add all nested scopes in the payload.

`using (logger.BeginScope("Test:{Test}", "Test"))
                    {
logger.LogInformation("Test Scoped Info");
                        using (logger.BeginScope("Test1:{Test1}", "Test1"))
                        {
                            logger.LogInformation("Test Scoped 2 Info");
                        }
                        logger.LogInformation("Test Scoped Info");
                    }`

Here it would be nice for the payload to have a property of "Test" with value "Test" for log entries before and after the nested scope. Then the log entry in the nested scope would have a payload with properties, "Test" = "Test" and "Test1" = "Test1".

**Comment by karolz-ms** [comment]
This is great suggestion, thanks. We'll look into it!

**Comment by karolz-ms** [comment]
Resolved by https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.Inputs.MicrosoftLogging/1.1.1 or newer
