### ISSUE TITLE
Service Fabric overrides don't allow null

### ISSUE THREAD

**Issue by JoeL1862** [Azure/diagnostics-eventflow#97]
In some sections eg the drop filter it seems that null is a valid value for the include property

if (string.IsNullOrWhiteSpace(value))
                {
                    this.Evaluator = PositiveEvaluator.Instance.Value; // Empty condition == include everything
                }

However in the service fabric settings overrides, null gets ignored when using replacement

string newValue = configurationRoot[valueReferencePath];
if (string.IsNullOrEmpty(newValue))
                        {
                            healthReporter.ReportWarning(
                                $"Configuration value reference '{kvp.Value}' was encountered but no corresponding configuration value was found using path '{valueReferencePath}'", 
                                EventFlowContextIdentifiers.Configuration);
                        }

If i am translating the intention here then this flag check should instead trigger if the setting is not available from configurationRoot and not when the returned value is null or empty

**Comment by karolz-ms** [comment]
@JoeL1862 good question. The problem with Microsoft.Extensions.Configuration is that it will return null when the looked up value is not present. So there is really no way to distinguish between "value not present" and "value is present, but null".

Do you have an example scenario where the null configuration value matters?

**Comment by JoeL1862** [comment]
The example where we would like the use of null, is in the drop include property, where for a local set-up we may want to let all log levels through however on other env we may want to drop Verbose level for example. From the documentation, having no drop would mean having the include property as empty.

**Comment by karolz-ms** [comment]
Makes sense. I guess we could allow empty string (which is different from null) to be used as a configuration value. Let me experiment with that.

**Comment by karolz-ms** [comment]
Resolved by Service Fabric nuget package version 1.1.4 (https://www.nuget.org/packages/Microsoft.Diagnostics.EventFlow.ServiceFabric/1.1.4)
