### ISSUE TITLE
EventHub output should support .NET Core

### ISSUE THREAD

**Issue by karolz-ms** [Azure/diagnostics-eventflow#99]
There is a new NuGet package for EventHub that supports .NET Core https://www.nuget.org/packages/Microsoft.Azure.EventHubs/ we should leverage it.

**Comment by alexvy86** [comment]
@karolz-ms this seems up for grabs and I'm interested on seeing it addressed. Unless there are any other plans for it (in which case let me know), I'll try to tackle it.

**Comment by karolz-ms** [comment]
Hey @alexvy86 , thanks for your offer. I have the change coded up, just need some help with testing, so if you are willing to help me with that, it would be very much appreciated! Let me just make sure the change is based on the main branch properly...

**Comment by alexvy86** [comment]
Sure! I just cloned master but I don't see the separate dependencies for .NET Standard there so I guess it's on a local branch. Let me know when it's up or where can I grab it.

**Comment by karolz-ms** [comment]
Here is the branch: https://github.com/karolz-ms/diagnostics-eventflow/tree/dev/karolz/eventhub-netcore 

Thanks again!

**Comment by karolz-ms** [comment]
Use EventHub output NuGet package version 1.2.0 or newer
